containerd/cri

.travis.yml
Makefile

Signed-off-by: heartlock <21521209@zju.edu.cn>
ref: #4 
@Random-Liu  Please enable travis hook and test.

enable travis CI

---

README.md

Add build status and go report cards.
Signed-off-by: Random-Liu <lantaol@google.com>

Add travis build and golang report icons.

---

pkg/server/testing/fake_execution_client.go

This is part of #19.
Extract this out to:
1) Make #19 a little bit smaller.
2) Get this merged soon so that https://github.com/kubernetes-incubator/cri-containerd/pull/30 can reuse some of the code.

Enhance fake execution client.

---

pkg/server/testing/fake_rootfs_client.go

Signed-off-by: mozhuli <21621232@zju.edu.cn>
ref:  #20

Add fake rootfs service

---

pkg/server/testing/fake_images_client.go

Signed-off-by: mozhuli <21621232@zju.edu.cn>
ref: #20

Add fake images service

---

pkg/server/testing/fake_execution_client.go
pkg/server/testing/fake_rootfs_client.go

Signed-off-by: mozhuli <21621232@zju.edu.cn>

Enhance fake services

---

pkg/server/container_stop.go
pkg/server/container_stop_test.go

Cancel `StopContainer` when the passed in context is cancelled.
/cc @yujuhong 

Stop waiting on cancellation.

---

Godeps/Godeps.json
cmd/cri-containerd/cri_containerd.go
pkg/server/events.go
pkg/server/service.go
vendor/github.com/jpillora/backoff/LICENSE
vendor/github.com/jpillora/backoff/README.md
vendor/github.com/jpillora/backoff/backoff.go

Retry to reconnect containerd event stream when containerd is down.

Retry and backoff when lost connection with containerd.

---

pkg/server/image_pull.go
pkg/server/sandbox_run.go
pkg/server/service.go

Remove some out-dated TODOs and code.

Cleanup code.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Add sandbox `/dev/shm`.
This is also very similar with https://github.com/kubernetes-incubator/cri-containerd/pull/50.

Add sandbox dev shm

---

pkg/server/container_stop.go
pkg/server/container_stop_test.go

Based on [CRI Defination](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L652-L654), timeout 0 means `forcibly terminate the container immediately`.
So skip graceful deletion when timeout is 0.

Kill container directly if timeout is 0.

---

pkg/server/events.go
pkg/server/events_test.go
pkg/server/helpers.go

Handle OOM event.

---

pkg/server/container_create_test.go
pkg/server/version_test.go

Remove unused fields to fix `make verify`.

Remove unused fields and comments.

---

README.md

Adds a user guide to the readme.

README.md updates for the alpha

---

docs/testing.md

@mikebrow This PR added document for all kinds of test for `cri-containerd`.

Add cri-containerd test document for developer.

---

pkg/server/container_create.go
pkg/server/image_remove.go
pkg/server/sandbox_run.go

Remove out-of-date TODOs.

---

README.md

Fix deadlink of travis.yml.

---

hack/test-cri.sh

Adds a loop that increases in delay five times while attempting to wait for the containerd server to come up enough that it can respond to a version request from the client.

loop waiting for containerd server to respond to client connection 

---

pkg/server/container_execsync.go

I'll be using new containerd client when implementing containerd streaming, so update container execsync first.
/cc @abhinandanpb 
Note that I'm not using `process.Wait`. Will use it after https://github.com/containerd/containerd/pull/1287 and https://github.com/containerd/containerd/pull/1279 are merged.

Use containerd client for container execsync

---

pkg/server/sandbox_run.go

Tested via e2e node.. results attached.

Sets sysctls from pod config annotations

---

.travis.yml

Split the travis Build to different logical stages so that it's easy to understand what went wrong in CI

Split the travis Build in different Build and Test Stage

---

.travis.yml

Fixing the go versions being tested against after the last travis PR introducing stages.

Putting in the go versions we want to test against

---

cmd/cri-containerd/options/options.go
pkg/server/service.go

The parameters of InitCNI should be filled in reverse order

---

vendor.conf
vendor/github.com/containerd/containerd/container.go
vendor/github.com/containerd/containerd/process.go
vendor/github.com/containerd/containerd/task.go

fixes #140
ref containerd/containerd#1386

Update containerd version to f79981c

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Related to https://github.com/kubernetes-incubator/cri-containerd/blob/dcc3cb2a05400b4dbc565d153127f23c06c823a1/pkg/server/container_create.go#L195
/cc @Random-Liu 

Group all privileged logic together

---

pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go

Checkpoint and restart recovery

---

hack/test-cri.sh
pkg/server/container_create.go

set uid if runAsUser has been seted.

add the user id support of runAsUser

---

pkg/server/sandbox_list_test.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go
pkg/server/sandbox_status.go
pkg/server/sandbox_stop.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/netns.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go
vendor.conf
vendor/github.com/containernetworking/plugins/LICENSE
vendor/github.com/containernetworking/plugins/README.md
vendor/github.com/containernetworking/plugins/pkg/ns/README.md
vendor/github.com/containernetworking/plugins/pkg/ns/ns.go
vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
vendor/github.com/containernetworking/plugins/pkg/ns/ns_unspecified.go

This commit contains changes to create/delete permanent namespace
for a sandbox container.

Creating sandbox namespace

---

hack/install-deps.sh

Remove unused code.

---

pkg/server/sandbox_stop.go

Do not teardown when network namespace is removed already.

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/133.

Disable pid namespace sharing

---

pkg/server/image_remove.go

An image tag may correspond to different images over time.
After downloading a new image with existing tag, both the old and new image will have the tag in `RepoTags` list.
When removing image, we want to remove all the references to the image. However, we may not want to remove the tag when removing the old image, because the tag is actually used by the new image then.
@abhinandanpb @crosbymichael 

Do not remove out dated image tag.

---

hack/test-e2e-node.sh

Kubernetes node need to accept all TCP/UDP/ICMP packets. However, by default on travis trusty node, `FORWARD` is `DROP`. That's why all intra-pod communication tests are failing:
```
[91m[1m[Fail] [0m[90m[k8s.io] Networking [0m[0m[k8s.io] Granular Checks: Pods [0m[91m[1m[It] should function for intra-pod communication: udp [Conformance] [0m
[37m/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:217[0m
[91m[1m[Fail] [0m[90m[k8s.io] Networking [0m[0m[k8s.io] Granular Checks: Pods [0m[91m[1m[It] should function for intra-pod communication: http [Conformance] [0m
[37m/home/travis/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/networking_utils.go:217[0m …
```

Configure iptables to accept all TCP/UDP/ICMP packets.

---

hack/install-deps.sh
hack/test-cri.sh
hack/test-e2e-node.sh

The build doesn't work if I have GOPATH like this `/path/a:/path/b`.

Fix build for multiple GOPATHs

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/util/strings.go
pkg/util/strings_test.go

For https://github.com/kubernetes/kubernetes/issues/51980.
Support "ALL" capabilities.
/cc @ijc 

Add "ALL" capabilities support.

---

pkg/server/container_create.go
pkg/server/container_list_test.go
pkg/server/container_remove_test.go
pkg/server/container_status_test.go
pkg/server/container_stop_test.go
pkg/store/container/container.go
pkg/store/container/container_test.go
pkg/store/container/fake_status.go
pkg/store/container/status.go
pkg/store/container/status_test.go
vendor/github.com/docker/docker/pkg/ioutils/buffer.go
vendor/github.com/docker/docker/pkg/ioutils/bytespipe.go
vendor/github.com/docker/docker/pkg/ioutils/fswriters.go
vendor/github.com/docker/docker/pkg/ioutils/readers.go
vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go
vendor/github.com/docker/docker/pkg/ioutils/temp_windows.go
vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
vendor/github.com/docker/docker/pkg/ioutils/writers.go
vendor/github.com/docker/docker/pkg/longpath/longpath.go

Checkpoint container status onto disk. With this we could recover container state from container metadata store and status checkpoint during restart.

Checkpoint container status onto disk.

---

cmd/cri-containerd/options/options.go

Format the code a bit.

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go

Add a default config file

---

pkg/server/io/logger.go

Fix one line of log, we are writing not reading.

---

pkg/server/sandbox_status.go

Since sandboxes which use the host network have no network namespace path this
would result in an invalid invocation of nsenter.
Rework the fetching of the sandbox to take this into account and also avoid
trying to get an IP when the network plugin is not yet ready.
Fixes #245.

Do not attempt to retrieve IP from host network namespace

---

vendor.conf
vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go

Update ocicni to include a minor fix.

Update ocicni to fc9c77cc55795c09bf1f74b2afd92078a793a69e

---

.travis.yml
cmd/cri-containerd/options/options.go
hack/test-utils.sh
pkg/server/container_create.go

Address TODOs for apparmor, and also fixes the empty case based on https://github.com/kubernetes/kubernetes/issues/51746#issuecomment-327856825.
@mikebrow 

Fix apparmor empty case.

---

Makefile
pkg/server/helpers.go
pkg/server/helpers_selinux_test.go

- Add build tags in Makefile
- Fixes a bug because of my negligence
- Improve the test case of `InitSelinuxOpts`

Add build tags and Improve the test case of selinux

---

contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

@abhinandanpb 
My node could not talk with my VMs, thus I haven't validated this PR yet.
Sent it our first, and I'll verify it again tomorrow.

Use systemd units in tar

---

contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/k8s.yaml

Minor format error and adding gpg key for kube component repos

Fixing ansible playbook for centos installation

---

docs/testing.md

Ref https://github.com/kubernetes-incubator/cri-containerd/issues/5
Update testing doc.

Update testing doc

---

contrib/linuxkit/README.md

Just a simple README with a pointer to the project.

contrib: add reference to LinuxKit project

---

contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

Feels good to remove code. Realised I can leverage our bundle structure to untar.

Ansible Cleanup: Combining few tasks into one

---

pkg/server/container_stats_list.go

Setting the cpu and memory stats of containers in nanoseconds

---

pkg/os/os.go

I implemented /dev/disk/by-uuid on my platform but using absolute links (where
udev typically uses relative) which broke the code in `os.DeviceUUID`.
Rather than just patch that up directly instead stat both the target and
candidate devices and pick one with matching major:minor in st_rdev. This saves
manually building paths to resolve symlinks and I think should be more robust
overall.
I also removed the initial stat of /dev/disk/by-uuid, I believe
`ioutil.Readdir` will correctly return an error if the path does not exist.

Use stat_t.st_rdev to compare block devices

---

README.md

minor update to the readme

---

hack/test-e2e-node.sh

https://github.com/containerd/containerd/issues/1512 is fixed by GCR, we could run the test now.

Run repodigest test.

---

hack/push.sh
test/e2e_node/build.sh
test/e2e_node/configure.sh
test/e2e_node/gci-init.sh
test/e2e_node/image-config.yaml
test/e2e_node/init.yaml

Add node e2e test framework for prow.
@krzyzacy @yguo0905

Add prow node e2e test.

---

test/e2e_node/image-config.yaml

There is no `jenkins` directory.

Fix node e2e test.

---

pkg/server/image_pull.go
test/e2e_node/init.yaml

Fix a log line and also set containerd log level to debug in node e2e.

---

pkg/server/snapshots.go

See https://github.com/containerd/containerd/pull/1706#issuecomment-340992262.
Call `Usage` during `Walk` will cause a deadlock in current version of containerd.

Do not call `Usage` inside `Walk`.

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
pkg/server/service.go

this pr is try to implement #369 
@Random-Liu  I have try to implement it, Please have a look.
Signed-off-by: zhangzhenhao <zhangzhenhao@outlook.com>

add pprof endpoint

---

cmd/cri-containerd/cri_containerd.go
pkg/client/client.go
vendor.conf
vendor/github.com/renstrom/dedent/LICENSE
vendor/github.com/renstrom/dedent/README.md
vendor/github.com/renstrom/dedent/dedent.go

Adds load command help see issue #367

adds help for load command

---

hack/install-deps.sh
pkg/server/container_attach.go
test/configure.sh

Add a default `crictl` confg. @yanxuean 
Also remove a redundant log.

Add crictl config.

---

pkg/server/container_create.go

Add comment for #398.

---

integration/container_stats_test.go
pkg/server/container_list.go
pkg/server/container_list_test.go
pkg/server/container_stats_list.go
pkg/server/sandbox_list.go
pkg/server/sandbox_list_test.go

Add truncindex for filter in List and Stat

---

.travis.yml
README.md

Update golang version to 1.9.x

---

pkg/server/helpers_test.go

Add simple unit test.

---

integration/sandbox_clean_remove_test.go
pkg/server/sandbox_remove.go
pkg/store/sandbox/netns.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/164.
For https://github.com/kubernetes-incubator/cri-containerd/issues/238.

Do not remove sandbox when netns is not closed.

---

pkg/containerd/importer/importer.go
pkg/server/container_stats_list.go

fixing vet errors

---

pkg/containerd/importer/importer.go
pkg/server/image_load.go

add lease for importer

---

pkg/server/container_status.go
pkg/server/container_status_test.go

To address the container portion of #359

adding some verbose debug

---

contrib/systemd-units/containerd.service
contrib/systemd-units/cri-containerd.service
test/e2e/master.yaml
test/e2e/node.yaml
test/e2e_node/init.yaml

Ref https://github.com/kubernetes-incubator/cri-containerd/issues/448.

Add LimitNPROC, LimitNOFILE and LimitCORE for containerd and cri-containerd.

---

vendor/github.com/containerd/containerd/client.go
vendor/github.com/containerd/containerd/container_opts.go
vendor/github.com/containerd/containerd/container_opts_unix.go
vendor/github.com/containerd/containerd/image.go
vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
vendor/github.com/containerd/containerd/remotes/handlers.go
vendor/github.com/containerd/containerd/task.go

This reverts commit 66ecfa70ad0b2d14a95f7c484297ca65eeff8101.

Revert "Add gc.root back in vendored containerd client."

---

pkg/server/container_start.go
pkg/server/sandbox_run.go

CI has been red after this change. Removing this until further investigation.

Revert: Setting containerd shim cgroup same as pod cgroup

---

pkg/server/container_create.go
pkg/server/container_start.go
pkg/server/image_pull.go
pkg/server/remove_soon.go

@mikebrow @abhi 
This is for debugging https://github.com/containerd/containerd/issues/1785.
We should revert this PR after we figure the issue out.

Check and dump rootfs.

---

hack/boilerplate/boilerplate.py
hack/cri-reset.sh
hack/test-cri.sh
hack/test-e2e-node.sh
hack/test-integration.sh
pkg/containerd/importer/importer.go
pkg/containerd/opts/container.go
pkg/containerd/opts/task.go
pkg/server/image_load.go

Commit 1 is the fix for the boilerplate test.
Commit 2 updates the files with a bad boilerplate.

fixes for boilerplate

---

integration/truncindex_test.go

Add integration test for truncindex

---

integration/truncindex_test.go

/cc @yanxuean 
From https://github.com/kubernetes-incubator/cri-containerd/pull/352.

Fix typos.

---

pkg/containerd/opts/container.go

ref: https://github.com/containerd/containerd/issues/1785
1. sync Unmount for snapshot
2. best effort to remove temp dir for snapshot
Signed-off-by: yason <yan.xuean@zte.com.cn>

Improve unmount for snapshot

---

hack/install-deps.sh
hack/release.sh

Switch to a tmp GOPATH for `make install.deps`

---

pkg/server/container_stats.go
pkg/server/container_stats_list.go
pkg/server/helpers.go
pkg/server/image_load.go
pkg/server/image_pull.go
pkg/server/image_remove.go
pkg/server/restart.go
pkg/server/sandbox_list.go
pkg/server/service.go

Signed-off-by: yason <yan.xuean@zte.com.cn>
1. improve calling for content and remove contentStoreService in criContainerdService
2. remove taskService and imageStoreService from criContainerdService
3. reliably remove image when content missing(e.g. missing image.config)

improve image

---

pkg/server/image_remove.go

Signed-off-by: yason <yan.xuean@zte.com.cn>

cleanup some comment for removeImage

---

docs/kube-up.md

Fix kube-up document.

---

pkg/server/container_create.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/515.

Remove default rlimits

---

hack/update-vendor.sh

Update `hack/version` again after update vendor.conf.
Sometimes containerd update also updates the runc version, this could automate that.

Change hack/update-vendor.sh to sync again with new vendor

---

pkg/annotations/annotations.go
pkg/server/container_create_test.go

Minor code cleanup after https://github.com/containerd/cri-containerd/pull/546.
/cc @jcvenegas 

Minor code cleanup.

---

pkg/server/container_stop.go
pkg/server/container_stop_test.go
pkg/server/events.go
pkg/store/container/container.go

Fixes #569
/cc @Random-Liu @yanxuean 

Use channel to pass the stop info instead of polling for container stop

---

pkg/server/container_stop.go
pkg/server/container_stop_test.go
pkg/server/events.go
pkg/server/sandbox_stop.go
pkg/server/sandbox_stop_test.go
pkg/store/container/container.go
pkg/store/container/fake_status.go
pkg/store/sandbox/sandbox.go
pkg/store/util.go

Address this [comment ](https://github.com/containerd/cri-containerd/pull/571#discussion_r163731014) in #571
Related to #569 

Use channel to propagate the stop info of sandbox

---

test/e2e_node/benchmark-config.yaml

Add node e2e image config for node e2e.

Add image config for benchmark.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Fix an error in privileged check, and add corresponding unit test.

Fix a privileged check.

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
test/e2e_node/init.yaml

Use registry mirror added in https://github.com/containerd/cri-containerd/pull/531.
@abhi 
Let's see whether the test passes.

Set registry mirror.

---

pkg/containerd/resolver/fetcher.go
pkg/containerd/resolver/resolver.go

Fix registry mirror.

---

cluster/gce/cloud-init/node.yaml
docs/installation.md
vendor.conf
vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go

Update ocicni to main stream. All PRs we need are merged.

Update ocicni to main stream.

---

.travis.yml

fix travis golang issue

---

pkg/containerd/importer/importer.go
pkg/containerd/util/util.go
pkg/server/container_create.go
pkg/server/container_execsync.go
pkg/server/container_start.go
pkg/server/container_update_resources.go
pkg/server/sandbox_run.go

Fixes https://github.com/containerd/cri-containerd/issues/142.
Ref https://github.com/containerd/cri-containerd/issues/642.
/cc @miaoyq Can you help me review this?

Fix cleanup context.

---

pkg/store/util.go

Signed-off-by: Stephen J Day <stephen.day@docker.com>

pkg/store: use a sync.Once to synchronize channel close

---

pkg/server/events.go
pkg/server/events_test.go

Address comments in https://github.com/containerd/cri/pull/628.
@yanxuean 

Cleanup event backoff.

---

contrib/ansible/cri-containerd.yaml
integration/test_utils.go
pkg/config/config.go

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

Bump pause container to multi-arch gcr.io/google-containers/pause:3.1

---

pkg/server/streaming.go

Address https://github.com/containerd/cri/pull/681#discussion_r176612296.

Make const private.

---

docs/config.md

Add a document for cri plugin config

---

contrib/ansible/cri-containerd.yaml
docs/config.md
docs/crictl.md
integration/test_utils.go
pkg/config/config.go

See https://github.com/containerd/cri/commit/6a542c596bfef139dde203d9359cadf6c48ad778#commitcomment-28223600

Use pause image from new source.

---

contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

Upgrade the release tarball version used in ansible.

Upgrade the tarball version in ansible.

---

hack/utils.sh

Update cri test to include RunAsGroup test.

---

README.md

relates to https://github.com/containerd/cri/issues/718

Update readme on how to configure cri plugin

---

pkg/containerd/resolver/resolver.go

Port https://github.com/containerd/containerd/pull/2276 to the resolver package we are using.
Fixes https://github.com/containerd/cri/issues/722.

Fix resolver race

---

contrib/ansible/tasks/bootstrap_ubuntu.yaml

Minor cleanup of comment in ansible

---

cluster/gce/configure.sh

Try using preloaded containerd if no version is specified.

---

docs/release.md
hack/install/install-deps.sh
hack/release.sh

Cherrypick the release script fixes into `release/1.0` to make it easier to cut future 1.0 release.

Cherry pick #750 and #751

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Fixes https://github.com/containerd/cri/issues/753.

Explicitly set `rw` for privileged container.

---

pkg/server/container_stats_list.go
pkg/server/container_stats_list_test.go

Cherrypick #766 into release/1.0 branch.

Cherrypick #766 into release/1.0 branch.

---

hack/utils.sh

Chery-pick #768 to release/1.0.

Upgrade cri-tools to v1.0.0-beta.1

---

pkg/server/sandbox_run_test.go

Signed-off-by: Ricardo Aravena <raravena80@gmail.com>

Minor typo

---

README.md

Cherrypick #775

---

contrib/ansible/README.md

Another logo fix.

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml

I forgot to enable the service, sorry.

Fix kube-container-runtime-monitor.

---

test/containerd/build.sh

Make DEPLOY_PATH configurable.

---

pkg/containerd/resolver/fetcher.go
pkg/containerd/resolver/fetcher_test.go

Cherry-pick #793 into release/1.0 branch.

Port docker resolver fix #2364.

---

pkg/server/events.go
pkg/server/service.go

Cherrypick #794 into release/1.0.

Generate fatal error when cri plugin fail to start.

---

pkg/server/sandbox_portforward.go

Ref https://github.com/containerd/cri/issues/524.
This should be equivalent to `netns.Do + localhost`, but this works with kata and gvisor. Because they steal ip from veth.
@abhi @jingax10

Use pod ip instead of localhost in pod netns for portforward.

---

pkg/server/container_create.go
pkg/server/sandbox_run.go

Fix double /dev/shm mount.

---

hack/utils.sh

Update crictl to v1.11.0.

---

docs/kube-up.md

Fix another `kube-up.sh` link.

Fix another link.

---

vendor/github.com/docker/docker/contrib/README.md
vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c
vendor/github.com/docker/docker/contrib/syscall-test/acct.c
vendor/github.com/docker/docker/contrib/syscall-test/exit32.s
vendor/github.com/docker/docker/contrib/syscall-test/ns.c
vendor/github.com/docker/docker/contrib/syscall-test/raw.c
vendor/github.com/docker/docker/contrib/syscall-test/setgid.c
vendor/github.com/docker/docker/contrib/syscall-test/setuid.c
vendor/github.com/docker/docker/contrib/syscall-test/socket.c
vendor/github.com/docker/docker/contrib/syscall-test/userns.c
vendor/golang.org/x/crypto/otr/libotr_test_helper.c
vendor/golang.org/x/crypto/otr/otr.go
vendor/golang.org/x/crypto/otr/smp.go
vendor/golang.org/x/crypto/ssh/test/doc.go
vendor/golang.org/x/crypto/ssh/test/sshd_test_pw.c
vendor/golang.org/x/sys/windows/svc/event.go
vendor/golang.org/x/sys/windows/svc/go12.c
vendor/golang.org/x/sys/windows/svc/go12.go
vendor/golang.org/x/sys/windows/svc/go13.go
vendor/golang.org/x/sys/windows/svc/security.go
vendor/golang.org/x/sys/windows/svc/service.go
vendor/golang.org/x/sys/windows/svc/sys_386.s
vendor/golang.org/x/sys/windows/svc/sys_amd64.s
vendor/k8s.io/kubernetes/build/README.md
vendor/k8s.io/kubernetes/build/pause/orphan.c
vendor/k8s.io/kubernetes/build/pause/pause.c

My local `vndr` version is too old. It removed these vendor files by mistake in https://github.com/containerd/cri/pull/838.

Add missing vendor back.

---

docs/installation.md
hack/release.sh

Cherrypick #843 to release/1.11 to avoid issues for future 1.11 releases.

Cherrypick #843 to release/1.11

---

docs/installation.md
hack/release.sh

Cherrypick #843 to release/1.0 to avoid issues for future 1.0 releases.

Cherrypick #843 to release/1.0

---

docs/config.md
pkg/config/config.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

[cherry-pick]support no_pivot option for runc

---

hack/verify-lint.sh

Cherrypick the lint fix.

---

hack/verify-lint.sh

Cherrypick #867 to release/1.0 branch.

---

cluster/gce/configure.sh

Cherrypick #869 into release/1.11

Cherrypick #869 into release/1.11

---

docs/config.md
pkg/config/config.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

[cherry-pick] support no_pivot option for runc

---

pkg/server/helpers.go
pkg/server/helpers_selinux_test.go
vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

Fixes #871
@vitt-bagal  Could you verify this pr on your environment?
Update selinux util to b6fa367
/cc @Random-Liu @mikebrow 

Verify selinux level format

---

pkg/server/helpers.go
pkg/server/helpers_selinux_test.go
vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

Cherrypick #873
Signed-off-by: Yanqiang Miao miao.yanqiang@zte.com.cn

Cherry pick #873 into release-1.11

---

pkg/server/helpers.go
pkg/server/helpers_selinux_test.go
vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

Cherry pick #873 into release-1.0

---

pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Today, I found that some containers on my workstation can't be stopped with `crictl stop`.
It turns out that the container processes are moved to `/user.slice` from the original container cgroups. I guess it is because I simply run `./containerd` to test containerd, without setting `Delegate=true` on my systemd node.
```console
$ /usr/local/bin/ctr -n=k8s.io task ls | grep 206190
6f757ff0e1c2b544da02c3ab17488be73b843dcc780847ae32ca4ae756be936f    206190    RUNNING
$ cat /sys/fs/cgroup/cpu,cpuacct/user.slice/cgroup.procs | grep 206190
206190
$ cat /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podcedaeae7-a4e4-11e8-a6f6-8cdcd43ac064/6f757ff0e1c2b544da02c3ab17488be73b843dcc780847ae32ca4ae756be936f/cgroup.procs
```
Although what I did was not best practice, I still think we should handle this …

Fix an issue that container/sandbox can't be stopped.

---

pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Cherrypick #885 to release/1.11

---

pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Cherrypick #885 to release/1.0

---

vendor.conf
vendor/github.com/containerd/go-cni/opts.go

Fixes https://github.com/containerd/cri/issues/889.

Update go-cni to 6d7b509a054a3cb1c35ed1865d4fde2f0cb547cd.

---

pkg/server/container_create.go

[release/1.11] Cherrypick: add HOSTNAME to env

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Ref https://github.com/containerd/cri/pull/898#issuecomment-419991978
Add `HOSTNAME` back. /cc @estesp 

Fix hostname env.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Revert #902.
Cherrypick #901 to release/1.0.

Cherrypick #901 to release/1.0

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Revert #902.
Cherrypick #901 to release/1.0.

Cherrypick #901 to release/1.11

---

integration/pod_hostname_env_test.go
integration/test_utils.go

Fixes https://github.com/containerd/cri/issues/904.
Add hostname env integration test.

Add hostname env integration test.

---

docs/config.md

The indent is wrong.

---

vendor.conf
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-tools/README.md
vendor/github.com/opencontainers/runtime-tools/generate/config.go
vendor/github.com/opencontainers/runtime-tools/generate/generate.go

Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>

Vendor in runtime-spec & runtime-tools from github.com/opencontainers 

---

hack/utils.sh

Cherrypick #928 release/1.2

---

pkg/server/sandbox_run.go

Add the Container Network Interface result output to the debug logs.
Output of this change:
```
time="2018-10-03T14:05:55.532915608+02:00" level=debug msg="cni result for sandbox "7db4d671ab60113bcec40ae9ca29dd059f6d22d44ca7b90bc9e379294b148edc"" cni-result="{"Interfaces":{"eth0":{"IPConfigs":[{"IP":"192.168.253.3","Gateway":"192.168.253.1"}],"Mac":"","Sandbox":""}},"DNS":[{},{}],"Routes":[{"dst":"0.0.0.0/0","gw":"192.168.253.1"}]}"
```

cni result: add a debug message

---

pkg/server/image_pull.go
vendor.conf
vendor/github.com/Microsoft/hcsshim/hnsendpoint.go
vendor/github.com/containerd/containerd/archive/compression/compression.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/resolver.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_unix.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/signals.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/tasks/kill.go
vendor/github.com/containerd/containerd/container_opts.go
vendor/github.com/containerd/containerd/images/archive/importer.go
vendor/github.com/containerd/containerd/images/image.go
vendor/github.com/containerd/containerd/metadata/content.go
vendor/github.com/containerd/containerd/oci/spec_opts.go
vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
vendor/github.com/containerd/containerd/remotes/docker/resolver.go
vendor/github.com/containerd/containerd/runtime/v2/binary.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go
vendor/github.com/containerd/containerd/runtime/v2/shim/shim_windows.go
vendor/github.com/containerd/containerd/runtime/v2/shim/util_windows.go
vendor/github.com/containerd/containerd/signal_map_linux.go
vendor/github.com/containerd/containerd/signal_map_unix.go
vendor/github.com/containerd/containerd/signal_map_windows.go
vendor/github.com/containerd/containerd/signals.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go

Fixes https://github.com/containerd/cri/issues/942.

Use authorizer

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_start.go
pkg/server/container_status.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go

Cherrypick #943 to release/1.2

---

README.md
contrib/ansible/README.md

link to new icon location

---

README.md

see... https://github.com/containerd/containerd/pull/2754

update the slack information

---

pkg/server/helpers.go

Update code based on golang 1.11 gofmt result.

Update code for golang 1.11 gofmt.

---

pkg/server/events.go

Use the `ID` field instead of `ContainerID`.
In this way, `TaskExit` event for exec will be filtered out, and we don't need to compare pid any more.
For more background: https://github.com/kata-containers/runtime/pull/572#issuecomment-438041382
I'd like to cherry-pick this into containerd 1.2, because this makes it easier to implement a shim v2 runtime.
@sboeuf @crosbymichael 

Use the `ID` field of `TaskExit` event.

---

pkg/server/events.go

Cherrypick #973 release 1.2

---

.travis.yml

Only install necessary tools.

---

pkg/server/events.go

This PR:
- Cherrypick #984 into release/1.2 branch;
- Resolves issue firecracker-microvm/firecracker-containerd#35

Cherrypick #984 release 1.2

---

integration/containerd_image_test.go

Fixes https://github.com/containerd/cri/issues/986.

Test that CRI plugin should not see image in other namespaces.

---

hack/test-cri.sh

Cherrypick #997 release 1.2

---

hack/test-cri.sh

Cherrypick #997 release 1.0

---

test/build-utils.sh

Cherrypick #1004 release 1.0

---

test/build-utils.sh

Cherrypick #1004 release 1.2

---

hack/test-cri.sh

This reverts commit d7f6721de591f9a46ebfdc8ed8de83a71d80743c.

Revert "Temporary fix for golang regression #29241."

---

hack/test-cri.sh

This reverts commit 298c7fd93eaabf1d0f75fef65a0e800596fae937.

Revert #999 release 1.2

---

hack/test-cri.sh

This reverts commit 2b2ca4c472915caf3919d64ce34d5db315de9406.

Revert #998 release 1.0

---

integration/container_create_test.go
integration/sandbox_run_test.go

Fixes: #1009
Signed-off-by: Hui Zhu <teawater@hyper.sh>

Add integration test for RunPodSandbox and CreateContainer

---

integration/pod_hostname_env_test.go

Don't use string when there is a constant.

---

integration/container_log_test.go
integration/image_load_test.go
pkg/server/events.go
pkg/server/io/logger.go
pkg/server/io/logger_test.go
pkg/util/strings.go

For https://github.com/containerd/cri/issues/1026.

Cherrypick #1027 release 1.2

---

integration/container_log_test.go
pkg/server/events.go
pkg/server/io/logger.go
pkg/server/io/logger_test.go
pkg/util/strings.go

Cherrypick #1027 release 1.0

---

Makefile
hack/verify-vendor.sh

use containerd/project script to detect dirty vendor.
close: #1012
Signed-off-by: Wei Fu <fuweid89@gmail.com>

hack/Makefile: detect dirty vendor

---

hack/verify-vendor.sh

remove the `unset` in the script.
Signed-off-by: Wei Fu <fuweid89@gmail.com>
cc @Random-Liu

hack: handle additional cleanup from #1028

---

integration/pod_hostname_test.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Fixes https://github.com/containerd/cri/issues/1041.
/cc @ibuildthecloud

Set /etc/hostname.

---

integration/pod_hostname_test.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Cherrypick #1042 release 1.2

---

integration/pod_hostname_test.go
integration/test_utils.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Cherrypick #1042 release 1.0

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/instrumented_service.go
pkg/server/sandbox_run.go

Cherrypick #1045 release 1.2

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/instrumented_service.go
pkg/server/sandbox_run.go

Cherrypick #1045 release 1.0

---

README.md
docs/kube-up.md

Address #1052
heads up regarding k8s 1.10 eol.
@dmcgowan @crosbymichael @estesp @Random-Liu 

update support statment reflecting eol for k8s 1.10

---

docs/architecture.md

Network namespace is created before the pause container.

Fix architecture doc

---

docs/config.md

/cc @haiyanmeng Hope this works better for you now. :)

Add more explanation about the CRI config.

---

cri.go
docs/config.md
pkg/config/config.go
pkg/server/service.go
pkg/server/streaming.go

Fixes https://github.com/containerd/cri/issues/1057.

Support stream idle timeout.

---

pkg/server/container_create.go

Cherrypick #1055 release 1.2

---

pkg/server/container_create.go

Cherrypick #1055 release 1.0

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Cherrypick #1072 release 1.0

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Cherrypick #1072 release 1.2

---

pkg/annotations/annotations.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Cherrypick #1056 release 1.2

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Cherrypick #1085 release 1.2

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Cherrypick #1085 release 1.0

---

docs/installation.md

clarify the versioning for the tarball

---

integration/container_stop_test.go
pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Fixes https://github.com/containerd/cri/issues/1098.

Do not SIGKILL container if container stop is cancelled.

---

integration/container_stop_test.go
pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Cherrypick #1099 release 1.2
For https://github.com/containerd/cri/issues/1098

Cherrypick #1099 release 1.2

---

integration/container_stop_test.go
integration/test_utils.go
pkg/server/container_stop.go
pkg/server/sandbox_stop.go

Cherrypick #1099 release 1.0
For #1098

Cherrypick #1099 release 1.0

---

pkg/server/helpers.go
vendor.conf
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

This repository now started doing tagged releases.

bump opencontainers/selinux to v1.2

---

vendor.conf

Cherrypick #1108 release 1.2

---

vendor.conf

Cherrypick #1108 release 1.0

---

integration/pod_hostname_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Cherrypick #1102 release 1.2

---

integration/pod_hostname_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Cherrypick #1102 release 1.0

---

hack/utils.sh

Cherrypick #1118 release 1.0
This is to fix containerd build.

Cherrypick #1118 release 1.0

---

hack/utils.sh

Cherrypick #1118 release 1.2
This is to fix containerd build.

Cherrypick #1118 release 1.2

---

pkg/server/testing/fake_cni_plugin.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/cni.go
vendor/github.com/containerd/go-cni/errors.go
vendor/github.com/containerd/go-cni/opts.go
vendor/github.com/containerd/go-cni/result.go

Update go-cni to 891c2a41e18144b2d7921f971d6c9789a68046b2.

---

cluster/gce/env
docs/crictl.md

For https://github.com/containerd/cri/issues/909.
I've validated `ctr images import`, I think it should work for us.

Use ctr images import.

---

pkg/server/image_pull.go

This can help users understand issues like https://github.com/containerd/containerd/issues/3236#issuecomment-490767549.

Log failed registry mirror attempt in debug.

---

pkg/server/helpers.go
pkg/server/sandbox_run.go

Forward sandbox config to PullImage request

---

pkg/containerd/opts/spec.go

Fix typo in WithoutRunMount

---

pkg/server/sandbox_run.go

Minor typo in toCNIBandWidth

---

docs/registry.md
pkg/config/config.go
pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1143
@Random-Liu here is the PR, feel free to give it a review.

Add TLS auth registry support

---

pkg/server/container_execsync.go

Cherrypick #1156 release 1.2

---

pkg/store/container/status.go

Remove an unused TODO.

---

docs/config.md
pkg/config/config.go
pkg/server/service.go
vendor.conf
vendor/github.com/containerd/go-cni/cni.go
vendor/github.com/containerd/go-cni/opts.go
vendor/github.com/containerd/go-cni/types.go

Make cni plugin config file num configurable， let containerd can make mutil network card
#1154

add cni plugin config file max num config

---

README.md

Signed-off-by: zhangyue <zy675793960@yeah.net>
fix #1164

fix: fix CRI dead link

---

docs/config.md
pkg/config/config.go

doc update for cni max num

---

pkg/server/image_pull.go

Fixes #1161.
Cherrypick #1162 release 1.2

Cherrypick #1162 release 1.2

---

pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1169.
Support http proxy env.
The transport is the same with https://github.com/containerd/containerd/blob/master/cmd/ctr/commands/resolver.go#L82

Fix http proxy ENV when TLS is enabled.

---

pkg/server/instrumented_service.go

Return gRPC errors from instrumentedService

---

Makefile
cri.go

Just modifying the containerd/cri Makefile so it has more synergy with the containerd/containerd Makefile
First PR doing some work on #1174 

synching up a bit with containerd Makefile

---

docs/config.md

Update docs to v2 config

---

Makefile

Add containerd font art.
For https://github.com/containerd/cri/pull/1173.
I like it! :P 

Add containerd font art.

---

pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/store/image/image.go

/cc @sofat1989 
Fixes https://github.com/containerd/containerd/issues/3401.

Do not cache image handler.

---

cri.go
docs/config.md
pkg/server/container_start.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go

Generate warning message or error for deprecated fields.

Print warning message for deprecated options.

---

pkg/server/container_create_test.go

Add test for `disable_proc_mount`.
This should also be cherry-picked to fix test in https://github.com/containerd/cri/pull/1216.

Add test for disable_proc_mount.

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_create_test.go

For #1208
Cherrypick #1209 release/1.2
Cherrypick https://github.com/containerd/cri/pull/1218 release/1.2

Cherrypick #1209 release/1.2

---

README.md

Fixes https://github.com/containerd/cri/issues/1222.

Update support metrics to reflect 1.11 EOL.

---

pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1229.

Remove extra roundtrip for checking schema1.

---

pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1201.
This ported part of https://github.com/containerd/cri/pull/1227 to releaes/1.2

Fix unnecessary https trial in release/1.2.

---

pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
pkg/server/testing/fake_cni_plugin.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/cni.go
vendor/github.com/containerd/go-cni/helper.go
vendor/github.com/containerd/go-cni/namespace.go
vendor/github.com/containerd/go-cni/opts.go
vendor/github.com/containerd/go-cni/result.go
vendor/github.com/containerd/go-cni/vendor.conf
vendor/github.com/containernetworking/cni/README.md
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/version/plugin.go
vendor/github.com/containernetworking/cni/pkg/version/version.go

Closes #1236
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Update cni and go-cni to the v0.7.1 release

---

vendor.conf

For https://github.com/containerd/containerd/issues/3507

Update cni plugins to v0.7.6.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

For https://github.com/containerd/cri/issues/1239
Cherrypick #1240 release 1.2

Cherrypick #1240 release 1.2

---

pkg/server/io/container_io.go
pkg/server/io/helpers.go

Similar with https://github.com/containerd/containerd/pull/3611.

Fix panic for task in unknown state.

---

pkg/server/container_execsync.go

Dockershim leaves long running `kubectl exec -it` process running in the background after io is detached.
We have the different behavior in that case. The `execInContainer` function will wait until the exec process exits, thus `kubectl exec -it` will also hang until that even after io is detached.
The expected behavior is not defined. This PR added a comment to clarify that behavior. If this causes issue to anyone, we can address it in the future.

Clarify exec behavior in some edge cases

---

hack/release.sh

For https://github.com/containerd/containerd/issues/3627
Support using locally built containerd release tarball. This will be used to build the gcs tarball from containerd repo.

Support local containerd release.

---

pkg/server/io/container_io.go
pkg/server/io/helpers.go

Cherrypick https://github.com/containerd/cri/pull/1259 into release 1.3

[release/1.3] Fix panic for task in unknown state.

---

hack/release.sh

For containerd/containerd#3627
Cherrypick #1266 to release/1.3.

[release/1.3] Support local containerd release.

---

test/windows/runner.sh

Fixes https://github.com/containerd/cri/issues/1288.
The current windows ssh setup can't avoid the occasional "permission denied" error, because it have to periodically update the ssh key file with the latest ssh keys from GCP. To avoid flaky test, let's retry on the "Permission Denied" error.

Ignore temporary permission denied error.

---

cluster/gce/cni.template

Fix indent in cni.template.

---

hack/utils.sh
pkg/config/config_windows.go
pkg/server/container_execsync.go
pkg/server/sandbox_portforward.go
pkg/server/sandbox_portforward_unix.go
pkg/server/sandbox_portforward_windows.go
pkg/server/streaming.go
test/windows/test.sh

Fixes https://github.com/containerd/cri/issues/1273

Add windows port forward support

---

test/windows/runner.sh

For https://github.com/containerd/cri/issues/1257
The recent test run failed with the reason:
```
packet_write_wait: Connection to 35.247.47.2 port 22: Broken pipe
```
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1176596196945301504
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1176611544612474882
The reason is that GCE instance has a default 10min timeout, we have to set the keep alive for long running ssh. See:
* https://askubuntu.com/questions/127369/how-to-prevent-write-failed-broken-pipe-on-ssh-connection
* https://stackoverflow.com/questions/30078348/google-cloud-ssh-timeout-how-to-increase-session-time

Set keepalive for ssh in windows test.

---

hack/release.sh

I discussed with @dmcgowan offline about this.
Let's add [Automate deployment of CRI containerd release](https://github.com/containerd/containerd/issues/3627) support to release/1.2 as well. We still need to maintain release/1.2 for half a year, and may even extend the support. Let's make things automated.
NOTE that this doesn't need to block 1.2.10 release. I can do manually push once more. :D 

[release/1.2] Support local containerd release.

---

.travis.yml

Cherrypick https://github.com/containerd/cri/pull/1312 to release/1.2

[release/1.2] Update based on default xenial distro.

---

cri.go

Logrus supports trace level natively now https://github.com/sirupsen/logrus/pull/844.

logrus supports trace level now.

---

README.md

minor update regarding HEAD support

missed the release version for HEAD in table-1

---

pkg/containerd/opts/spec_unix.go
pkg/server/container_create_unix.go

Fixes #1316 
Signed-off-by: bpopovschi <zyqsempai@mail.ru>

Use containerD WithHostDevices

---

pkg/server/events.go
pkg/server/helpers.go
pkg/server/restart.go
pkg/store/container/status.go
pkg/store/container/status_test.go

[release/1.2] Better handle unknown state.

---

pkg/server/events.go
pkg/server/helpers.go
pkg/server/restart.go
pkg/store/container/status.go
pkg/store/container/status_test.go

[release/1.3] Better handle unknown state.

---

.appveyor.yml
.travis.yml
pkg/server/container_create_unix.go

Fix privileged support

---

pkg/server/sandbox_run.go

Partially cherry-pick aaddaa27320bfe89959d838205a7117af825361e (#1359)
https://github.com/containerd/cri/pull/1359#discussion_r358981963

[release/1.3] fix NoPivot for RuntimeRuncV2

---

cri.go

[release/1.3] Validate and update the right config

---

vendor.conf
vendor/gopkg.in/yaml.v2/LICENSE
vendor/gopkg.in/yaml.v2/NOTICE
vendor/gopkg.in/yaml.v2/README.md
vendor/gopkg.in/yaml.v2/apic.go
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/emitterc.go
vendor/gopkg.in/yaml.v2/encode.go
vendor/gopkg.in/yaml.v2/go.mod
vendor/gopkg.in/yaml.v2/parserc.go
vendor/gopkg.in/yaml.v2/readerc.go
vendor/gopkg.in/yaml.v2/resolve.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/gopkg.in/yaml.v2/sorter.go
vendor/gopkg.in/yaml.v2/writerc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go

full diff: https://github.com/go-yaml/yaml/compare/53feefa2559fb8dfa8d81baad31be332c97d6c77...v2.2.8
Includes https://github.com/go-yaml/yaml/commit/bb4e33bf68bf89cad44d386192cbed201f35b241
to address CVE-2019-11253

[release/1.2] vendor: bump gopkg.in/yaml.v2 v2.2.8

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

Here's the full diff:
https://github.com/opencontainers/selinux/compare/3a1f366feb7aecbf7a0e71ac4cea88b31597de9e...5215b1806f52b1fcc2070a8826c542c9d33cd3cf
(cherry picked from commit 5f0bf0523952f3c0044d4a0faf3cf7d65440a1de)

pick up fix for CVE-2019-19921 in opencontainers/selinux

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
vendor/github.com/opencontainers/selinux/go.mod

Here are the differences:
https://github.com/opencontainers/selinux/compare/3a1f366feb7aecbf7a0e71ac4cea88b31597de9e...5215b1806f52b1fcc2070a8826c542c9d33cd3cf
Found this when reviewing dependencies in kubernetes

Update to a released version of opencontainers/selinux (1.3.3)

---

.appveyor.yml
.travis.yml
README.md

update to golang 1.13.8

---

Makefile
README.md
hack/install/utils.sh
vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md
vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go

docker-ce seems to be building runc with selinux support, let us follow
the same pattern here please:
https://github.com/docker/docker-ce/search?p=1&q=RUNC_BUILDTAGS&unscoped_q=RUNC_BUILDTAGS

Build runc with selinux support

---

.github/workflows/ci.yml

address #1444
Will delete our .travis.yml tests after we merge this

adds git hub actions for linux CI

---

.github/workflows/ci.yml

split tests and some refactoring

---

Makefile

resolves #1448 step: modify makefile validation testing to use /project

use project dco test locally

---

README.md
docs/crictl.md
docs/testing.md

Some small improvements to docs of things I found while using the docs.

Add improvement to docs

---

hack/utils.sh
pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go

Address https://github.com/containerd/cri/issues/1461

move up to latest critools; add apparmor profile check

---

pkg/server/sandbox_run.go

Should destroy the pod network if fails to setup or return invalid
net interface, especially multiple CNI configurations.
Signed-off-by: Wei Fu <fuweid89@gmail.com>

RunPodSandbox: destroy network if fails or invalid

---

vendor.conf
vendor/k8s.io/api/go.mod
vendor/k8s.io/apimachinery/pkg/util/net/http.go
vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
vendor/k8s.io/apiserver/go.mod
vendor/k8s.io/client-go/go.mod
vendor/k8s.io/client-go/rest/request.go

Fix client watch reestablishment handling of client-side timeouts

vendor: kubernetes v1.18.2

---

pkg/server/image_pull.go

Address issue #1421
@Random-Liu

removes the error when tls is configured for https but http is tried first

---

README.md

- to sig-node
- to sig-testing
fixes #1493

docs moved

---

vendor.conf

No code changes, just referencing the tag
Signed-off-by: Michael Crosby <michael@thepasture.io>

Use go-cni tag

---

.github/workflows/ci.yml

adding the pull request sha to the log filenames

would like to have the commit sha in the log file names

---

docs/registry.md

Addressing at least a portion of #1482
Needed some documentation for _json_key authentication with a registry.

add a registry auth tutorial

---

hack/utils.sh

see https://github.com/containerd/containerd/pull/4299#issuecomment-638420503

move up to latest cri-tools - pick up nginx fix

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

Includes fixes for the category range and mount labeling.
Signed-off-by: Michael Crosby <michael@thepasture.io>

bump selinux dep

---

.appveyor.yml
.github/workflows/ci.yml
README.md

Changes: https://github.com/golang/go/milestone/148?closed=1

Bump Golang 1.13.12

---

hack/utils.sh
integration/sandbox_clean_remove_test.go
pkg/server/container_remove.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_stop.go

carry...https://github.com/containerd/cri/pull/1128 to help out @adk9 a bit
resolves:
https://github.com/containerd/cri/issues/1127
Test here:
https://github.com/kubernetes-sigs/cri-tools/pull/637
Fail here:
https://github.com/containerd/cri/pull/1526
ready to merge on green..
Thanks @adk9

Forcibly remove sandbox container

---

docs/config.md

Signed-off-by: Hsuan-Chi Kuo <hckuo2@illinois.edu>

Fix doc for runtime specific options

---

docs/decryption.md

Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Update doc cri plugin convention

---

docs/registry.md

Signed-off-by: Takumasa Sakao <sakataku7@gmail.com>

Update config syntax in registry.md (GCR example)

---

pkg/server/container_list.go

Resolves issue: #1546 
After pull request output:
```
mike@mike-VirtualBox:~/go/src/crictl-test$ sudo crictl ps -all -p a3
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
8b74f21338a65       busybox             10 days ago         Running             busybox             0                   a3c9b2d234556
mike@mike-VirtualBox:~/go/src/crictl-test$ sudo crictl ps -all -p a4
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
mike@mike-VirtualBox:~/go/src/crictl-test$ sudo crictl ps -all -p a3c9b2d234556
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID …
```

adds support for pod id lookup for filter

---

vendor.conf
vendor/github.com/containerd/containerd/container.go
vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
vendor/github.com/containerd/containerd/remotes/docker/registry.go
vendor/github.com/containerd/containerd/remotes/docker/resolver.go
vendor/github.com/containerd/containerd/remotes/docker/scope.go
vendor/github.com/containerd/containerd/services/tasks/local.go
vendor/github.com/containerd/containerd/task.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go
vendor/github.com/containerd/continuity/context.go
vendor/github.com/containerd/continuity/devices/devices_unix.go
vendor/github.com/containerd/continuity/digests.go
vendor/github.com/containerd/continuity/driver/driver_windows.go
vendor/github.com/containerd/continuity/fs/path.go
vendor/github.com/containerd/continuity/go.mod
vendor/github.com/containerd/continuity/groups_unix.go
vendor/github.com/containerd/continuity/hardlinks.go
vendor/github.com/containerd/continuity/hardlinks_unix.go
vendor/github.com/containerd/continuity/manifest.go
vendor/github.com/containerd/continuity/sysx/xattr_unsupported.go
vendor/github.com/opencontainers/runc/go.mod
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device_unix.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device_windows.go
vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go

See individual commits for details

Bump containerd v1.4.0 rc.0

---

README.md
vendor.conf
vendor/github.com/containerd/containerd/cmd/containerd/command/oci-hook.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go
vendor/github.com/opencontainers/runc/go.mod
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/state.go

Update support table and containerd 1.4 vendor... to prepare for 1.4 branch.

Prepare 1.4

---

hack/install/install-cni-config.sh
hack/install/install-cni.sh
pkg/server/update_runtime_config_test.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/go.mod
vendor/github.com/containernetworking/cni/README.md
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/args.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/utils/utils.go
vendor/github.com/containernetworking/plugins/README.md
vendor/github.com/containernetworking/plugins/go.mod
vendor/github.com/containernetworking/plugins/pkg/ns/README.md
vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go

Use the new release versions of cni and keep it in sync with the rest of the containerd ecosystem
xref: https://github.com/containerd/containerd/pull/4308

bump cni dependencies

---

hack/install/install-cni-config.sh
hack/install/install-cni.sh
pkg/server/update_runtime_config_test.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/go.mod
vendor/github.com/containernetworking/cni/README.md
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/args.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/utils/utils.go
vendor/github.com/containernetworking/plugins/README.md
vendor/github.com/containernetworking/plugins/go.mod
vendor/github.com/containernetworking/plugins/pkg/ns/README.md
vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go

Cherrypick #1556 release 1.4
Signed-off-by: Antonio Ojea <aojea@redhat.com>

[release/1.4] bump cni dependencies #1556

---

hack/install/install-cni-config.sh

See: https://github.com/containerd/containerd/pull/4308/files#diff-bc3ee81027bc2e27f4df56465b4290e1R37
https://github.com/containerd/containerd/pull/4308

update cni config version

---

hack/install/install-cni-config.sh

[release/1.4] update cni config version #1573

---

cluster/gce/configure.sh

Signed-off-by: Varsha Teratipally teratipally@google.com

Make script work for both python2.7 and 3.6

---

docs/config.md

Reverts containerd/cri#1530 , seems merged by mistake

Revert "Fix doc for runtime specific options"

---

docs/registry.md

While using the "Configure image registry" doc, I noticed some improvements which could help users. This PR adds these improvements.

Doc (registry): Update to the image registry doc

---

.golangci.yml
integration/addition_gids_test.go
integration/container_log_test.go
integration/container_restart_test.go
integration/container_stats_test.go
integration/container_stop_test.go
integration/container_update_resources_test.go
integration/container_without_image_ref_test.go
integration/containerd_image_test.go
integration/duplicate_name_test.go
integration/image_load_test.go
integration/imagefs_info_test.go
integration/main_test.go
integration/no_metadata_test.go
integration/pod_dualstack_test.go
integration/pod_hostname_test.go
integration/remote/remote_image.go
integration/remote/remote_runtime.go
integration/restart_test.go
integration/runtime_handler_test.go
integration/sandbox_clean_remove_test.go
integration/truncindex_test.go
integration/volume_copy_up_test.go
pkg/api/runtimeoptions/v1/api.proto
pkg/server/container_create_unix_test.go
pkg/server/image_pull_test.go
pkg/store/sandbox/status_test.go
test/verify.sh

Adds some stricter linting with fewer file exceptions

Align lint with containerd

---

README.md

Let's have this update in the master and `release/1.4` branch.

update README to clarify the current status of this repo
