.travis.yml
Makefile
hack/lint.sh

The first commit enables unit testing in travis.  
The second commit addresses a few nits in Makefile regarding spacing and comment descriptions.
The third commit addresses issue #13 by extending the timeout from 30sec to 5min.

Enables unit tests for Travis build; address nits in Makefile; increase lint timeout to 5min

---

pkg/metadata/sandbox.go
pkg/metadata/sandbox_test.go
pkg/metadata/store/metadata_store.go
pkg/metadata/store/metadata_store_test.go

For https://github.com/kubernetes-incubator/cri-containerd/issues/6.
This PR added:
* The metadata store interface;
* An in-memory implementation;
* A sandbox metadata store based on the metadata store.
In the future, we need to have an on-disk implementation. The `TODOs` in `memory_store.go` describes how to implement a [file-based checkpoint](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/checkpoint_store.go).
The metadata store interface is defined as follows:
```go
// All byte arrays are expected to be read-only. User MUST NOT modify byte
// array element directly!!
// UpdateFunc is function used to update a specific metadata. The value
// passed in is the current value. The updated value should be returned.
// If there is an error, the update will be …
```

Add the metadata store interface and an in-memory implementation.

---

pkg/os/os.go
pkg/os/testing/fake_os.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/24.
Just a very small PR adding the OS interface for unit testing. So far, I mainly used `MkdirAll` and `RemoveAll` in the sandbox and container lifecycle PRs. So only added those 2 functions for now. We could always extend in the future.
I'm not using mockgen because the code generated could not pass lint...
Signed-off-by: Random-Liu <lantaol@google.com>

Add OS interface and fake implementation.

---

Godeps/Godeps.json
pkg/server/image_pull.go
pkg/server/image_pull_test.go
vendor/github.com/docker/distribution/AUTHORS
vendor/github.com/docker/distribution/LICENSE
vendor/github.com/docker/distribution/digestset/set.go
vendor/github.com/docker/distribution/reference/helpers.go
vendor/github.com/docker/distribution/reference/normalize.go
vendor/github.com/docker/distribution/reference/reference.go
vendor/github.com/docker/distribution/reference/regexp.go

We are using new `docker/distribution` instead of previous `docker/docker/reference` because the later will introduce too many unnecessary dependencies, and also cause runc version conflict.
With this PR, I could pull image now, but there are other problems still. cri-containerd panics during the cri validation image test, will fix them one by one.
```
Running Suite: E2ECRI Suite
===========================
Random Seed: 1494610089 - Will randomize all specs
Will run 6 of 36 specs
SSS
------------------------------
[k8s.io] Image Manager 
public image with digest should be pulled and removed [Conformance]
/usr/local/google/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/image.go:60
[BeforeEach] [k8s.io] Image Manager …
```

Use docker/distribution library used by docker 17.05.x to support all docker image reference.

---

pkg/metadata/image_metadata.go
pkg/metadata/image_metadata_test.go
pkg/metadata/sandbox.go
pkg/metadata/sandbox_test.go
pkg/metadata/store/metadata_store.go
pkg/metadata/store/metadata_store_test.go
pkg/metadata/util.go
pkg/metadata/util_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_remove_test.go
pkg/server/sandbox_status.go
pkg/server/sandbox_stop.go

Let metadata store return not exist error instead of `nil, nil`.
We made this change to:
1) Make it more convenient and intuitive to use the metadata store;
2) We need the not exist error for `Update` function in container lifecycle management.

Return not exist error in metadata store

---

pkg/server/events.go
pkg/server/helpers.go
pkg/server/image_remove.go
pkg/server/image_status.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go
pkg/server/sandbox_stop.go
pkg/server/service.go
pkg/server/service_test.go
pkg/server/testing/fake_rootfs_client.go

Based on https://github.com/kubernetes-incubator/cri-containerd/pull/41 and https://github.com/kubernetes-incubator/cri-containerd/pull/46.
This PR let sandbox container use pause image and applies image config.
Only the last commit is new. Will rebase the PR and previous PRs soon.

Apply sandbox image config

---

cmd/cri-containerd/cri_containerd.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Based on #41, #46 and #48.
This PR pulls container image and applies image config.
Only the last commit is new. Will rebase the PR and previous PRs soon.

Apply container image config

---

.travis.yml

Both containerd and kubernetes dropped the support for golang 1.7.
Remove golang 1.7.
/cc @mikebrow

Remove golang 1.7 from ci.

---

pkg/server/agents/agents.go
pkg/server/agents/logger.go
pkg/server/agents/logger_test.go
pkg/server/agents/testing/fake_agent_factory.go
pkg/server/container_start.go
pkg/server/sandbox_run.go
pkg/server/service.go
pkg/server/service_test.go

Based on #53, #52 and #48. Only the last 2 commits are new.
This PR added container logging support.

Add container logging support.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Add sandbox `/etc/hosts` and mount it inside each container of the sandbox.
Currently, in Kubelet,
* For `/etc/hosts`, we mount it when the sandbox is not using host network, and rely on the runtime to maintain it if the sandbox is using host network.
* For `/etc/resolv.conf`, we rely on the runtime to maintain it (dockershim overwrites it after creates sandbox container).
From the perspective of a runtime, it's weird that we only maintain the file in some cases, and not in other cases.
So in this PR, I'll let `cri-containerd` always maintain `/etc/hosts` no matter the sandbox is using host network or not.
In the future, we should make it consistent:
1) Either let kubelet manage all those files;
2) Let runtime manage all those files.
/cc @yujuhong

Add sandbox /etc/hosts.

---

pkg/server/version.go
pkg/server/version_test.go

A small PR to use containerd version returned by version service.
As is mentioned in https://github.com/kubernetes-incubator/cri-containerd/issues/62#issuecomment-306638697, containerd will return proper version after a tag with description is created.
Now version service returns commit number. It's fine for now, only problem is that runtime version will be shown as `Unknown` by kubernetes, because it's not a semver.

Use containerd version returned by version service.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

This is implement part of #28, I'll continue to write some related unit test for this.
> And we may need to maintain it for hostNetwork pod, let me double check it and rely later.
@Random-Liu I copy a host resolv.conf for each pod with hostNetwork, since user may change this file in container. Let me know if you change your mind.
Signed-off-by: Crazykev <crazykev@zju.edu.cn>

Generate and maintain resolv.conf for sandbox

---

Godeps/Godeps.json
pkg/server/container_start.go
vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_windows.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config_unix.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
vendor/github.com/opencontainers/runc/libcontainer/configs/device_defaults.go
vendor/github.com/opencontainers/runc/libcontainer/configs/hugepage_limit.go
vendor/github.com/opencontainers/runc/libcontainer/configs/interface_priority_map.go
vendor/github.com/opencontainers/runc/libcontainer/configs/mount.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unix.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/configs/network.go
vendor/github.com/opencontainers/runc/libcontainer/devices/devices_unix.go
vendor/github.com/opencontainers/runc/libcontainer/devices/devices_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/devices/number.go

When `privileged` is true:
- Enable all capabilities
- Add all host devices
- Clear readonly on some volumes, e.g. cgroups and /sys volumes
ref: #29 @Random-Liu Ready for review.

Support privileged

---

pkg/server/container_start.go
pkg/server/container_start_test.go

The capabilities in CRI and docker doesn't have the `CAP_` prefix. However, we need to add it when generating the runtime spec.
With another `ExecSync` PR I'll send out soon, we can pass the capabilities cri validation test now:
```
Running Suite: E2ECRI Suite
===========================
Random Seed: 1497147284 - Will randomize all specs
Will run 1 of 36 specs
SSSSSSSSSSSSSSSSS
------------------------------
[k8s.io] Security Context runtime should support container with security context 
runtime should support setting Capability
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:369
[BeforeEach] [k8s.io] Security Context
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:50
[BeforeEach] …
```

Fix capabilities support.

---

pkg/server/container_start.go
pkg/server/container_start_test.go

This PR:
1) Mount cgroup into the container, which inherits the [docker's behavior](https://github.com/moby/moby/blob/master/oci/defaults_linux.go#L67-L72).
2) Add unit test left from [Privileged PR](#51). /cc @heartlock 

Mount cgroup into the container and add unit test for privileged mount.

---

pkg/server/events.go

I missed the event loop in https://github.com/kubernetes-incubator/cri-containerd/pull/59. Added it back.

Add the missing loop in event handler.

---

pkg/server/testing/fake_execution_client.go

We should clear the client list after close all event client channels. Or else [this line](https://github.com/Random-Liu/cri-containerd/blob/2ae22b33b7de6d327369aa35da66f6d4acd9c194/pkg/server/testing/fake_execution_client.go#L102) may send event to the closed channel which causes a panic.

Fix a race that fake execution client sends event to closed channel.

---

pkg/server/container_stop.go
pkg/server/container_stop_test.go
pkg/server/helpers.go
pkg/server/testing/fake_execution_client.go

1. Fix a `Delete` race between `container_stop.go` and `event.go`.
Initially, I thought `Delete` is thread safe. However, I found that if there are 2 on-going `Delete`s, one may stop the shim already, but the other one may have get the container index from containerd and try to access shim and get a `"transport is closing"` error. This seems to be expected behavior. /cc @crosbymichael
Actually I think we should not let `container_stop.go` `Delete` the container before event handler properly handles the exit event, so we should use `Kill` in `container_stop.go`.
2. Ignore `Kill` errors.
Another change made by this PR is to ignore `Kill` error, because when process is already stopped, `Kill` will return an `os: process already finished` error, [which is …

Fix Delete race.

---

Godeps/Godeps.json
pkg/os/os.go
pkg/server/container_stop.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_remove_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
pkg/server/sandbox_stop_test.go
vendor/github.com/docker/docker/pkg/mount/flags.go
vendor/github.com/docker/docker/pkg/mount/flags_freebsd.go
vendor/github.com/docker/docker/pkg/mount/flags_linux.go
vendor/github.com/docker/docker/pkg/mount/flags_unsupported.go
vendor/github.com/docker/docker/pkg/mount/mount.go
vendor/github.com/docker/docker/pkg/mount/mounter_freebsd.go
vendor/github.com/docker/docker/pkg/mount/mounter_linux.go
vendor/github.com/docker/docker/pkg/mount/mounter_solaris.go
vendor/github.com/docker/docker/pkg/mount/mounter_unsupported.go
vendor/github.com/docker/docker/pkg/mount/mountinfo.go
vendor/github.com/docker/docker/pkg/mount/mountinfo_freebsd.go
vendor/github.com/docker/docker/pkg/mount/mountinfo_linux.go
vendor/github.com/docker/docker/pkg/mount/mountinfo_solaris.go
vendor/github.com/docker/docker/pkg/mount/mountinfo_unsupported.go
vendor/github.com/docker/docker/pkg/mount/mountinfo_windows.go
vendor/github.com/docker/docker/pkg/mount/sharedsubtree_linux.go
vendor/github.com/docker/docker/pkg/mount/sharedsubtree_solaris.go

Based on https://github.com/kubernetes-incubator/cri-containerd/pull/73. The last 2 commits are new.
1) The 2nd commit unmount sandbox `/dev/shm` when stop sandbox.
2) The 3rd commit stop/remove containers inside sandbox when stop/remove sandbox.

Unmount dev shm and cleanup container when stop/remove sandbox

---

pkg/metadata/container.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/container_execsync.go
pkg/server/helpers.go

Add simple `ExecSync` based on current containerd api.
Some TODOs in the future which will be addressed in future PRs:
1) Switch to containerd client and add unit test.
2) Add `ExecSync` timeout support, including timeout waiting and graceful termination after timeout.

Add ExecSync.

---

pkg/server/helpers.go

Now we support schema 1 image, we could use official pause image now.

Use gcr.io/google_containers/pause:3.0

---

pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/image_pull.go

Register both repo tag and repo digest when pulling image.
Currently, Kubelet assumes that once image is pulled with repo tag, the repo digest also needs to be stored as existing reference.

Register all possible repo tags and repo digests.

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/58.
I've tried this PR with a private image `taotaotheripper/node-problem-detector:v0.2`, it works.
However, [the node e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/runtime_conformance_test.go#L296) is still failing because of https://github.com/containerd/containerd/issues/1064, which should possibly be fixed in containerd.

Add pull image authentication.

---

Makefile

Fixes the issue where we could not use the `v` prefix for release tags.  semver 2.0 removed support for the v prefix.  Still the v prefix is commonly used and expected on release tags in git repos. 
The solution here is to allow for the v prefix on the release tag, but to remove the prefix before setting the version variable in the version package. This way the reported version is sans the v.. but the displayed version includes the v in git hub. 

adds support for v prefix in release tags

---

pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Set default resource limit for sandbox container.
The default value comes from:
* [PodInfraOOMAdj](https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/kubelet/qos/policy.go#L29)
* [defaultSandboxCPUshares](https://github.com/kubernetes/kubernetes/blob/7560142e27ba9c0c535695356a14ac169acd7476/pkg/kubelet/dockershim/docker_sandbox.go#L42)

Set sandbox container resource limit.

---

pkg/server/sandbox_stop.go

We should not teardown pod network when sandbox is using host network.
@xlgao-zju Could you help me review this?

Do not teardown network namespace when using host network.

---

hack/test-cri.sh

CHange containerd log level to debug for better debugging.

Change containerd log level to debug for cri validation test.

---

README.md

So that it won't be out-of-sync again.

Link dependency versions in README.md to code.

---

hack/update-vendor.sh
vendor/github.com/docker/docker/pkg/signal/trap.go
vendor/github.com/kubernetes-incubator/cri-o/pkg/ocicni/ocicni.go

`sirupsen` was changed to upper case in https://github.com/kubernetes-incubator/cri-containerd/pull/110, which causes problem.
Travis could still build, because there is `Sirupsen` cached in `$GOPATH`, and upper case `Sirupsen` in `$GOPATH` still works but doesn't work in `vendor`, which seems to be a golang problem.
Anyway, we need to rewrite until https://github.com/kubernetes-incubator/cri-containerd/issues/106 is fixed.

Add script to rewrite `Sirupsen` to `sirupsen` in vendor.

---

pkg/server/container_create.go
pkg/server/helpers.go

I found that cri-containerd prints out a lot of following logs when running privileged container test:
```
WARNING: The same type, major and minor should not be used for multiple devices.
```
It turns out that device list returned by `HostDevices` also contains all the device symlinks with 0 major & minor.
This PR:
1) Skip these 0 major minor devices for privileged container;
2) Follow symlink for non-privileged container, which is [the same with docker](https://github.com/moby/moby/blob/7238cca42c3d024adfa030306ad3e3ec4232baed/oci/devices_linux.go#L45).
/cc @kubernetes-incubator/maintainers-cri-containerd 

Handle device symlink.

---

Makefile

To allow e.g. building a static binary with:
make binaries GO_GCFLAGS="--ldflags '-extldflags \"-fno-PIC -static\"'"

Allow setting of compiler options

---

pkg/server/container_create.go
pkg/server/sandbox_run.go

The original default spec contain `seccomp` configuration, but some OS do not support this feature, such as ubuntu14.04, and `make test-cri` always fail. The containerd default spec dosen't contain `seccomp`, so I think we could replace the default spec with containerd default spec.
The difference between original default spec and containerd default spec:
| original default spec | containerd default spec |
|---------------------------|-------------------------------|
| - | mounts: /run |
| seccomp | - |
| process.capabilities.ambient | - |
| env: TERM=xterm | - |

Replace the original default spec with containerd default spec

---

pkg/server/container_create.go
pkg/server/container_create_test.go

In https://github.com/kubernetes-incubator/cri-containerd/pull/126, we changed to use containerd default spec.
However, because containerd doesn't add `TERM=xterm` by default, it needs to be added separately when tty is enabled.
This is not done in runtime-tools, but is handled in containerd `WithTTY`, so we'll use containerd spec generator to set TTY.
/cc @miaoyq

Use containerd spec generator to set tty.

---

.travis.yml
README.md
hack/test-cri.sh
pkg/server/container_exec.go
pkg/server/sandbox_portforward.go
pkg/server/streaming.go

Add port forward support. The implementation is the same with [the dockershim](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_streaming.go#L162-L217).

Add portforward support.

---

pkg/server/container_execsync.go
pkg/server/service.go

Some cleanup after switching to new containerd client.

Some cleanup after switching to new client.

---

.travis.yml

Our first cron build fails, because the test command returns exit code 1, which travis thought the test was failing.
@kubernetes-incubator/maintainers-cri-containerd

Fix node e2e test.

---

pkg/server/container_update_resources.go
pkg/server/container_update_resources_test.go

Depends on https://github.com/kubernetes-incubator/cri-containerd/pull/148.
Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/149.
Will rebase after https://github.com/kubernetes-incubator/cri-containerd/pull/148 is merged.

Support update container resources

---

vendor.conf
vendor/github.com/cri-o/ocicni/ocicni.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/158.
Vendor ocicni from upstream, cri-o/ocicni#1 is merged.

Vendor ocicni from upstream.

---

pkg/server/container_create.go
pkg/server/container_exec.go
pkg/server/container_execsync.go
pkg/server/container_list.go
pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/container_status.go
pkg/server/container_stop.go
pkg/server/container_update_resources.go
pkg/server/image_list.go
pkg/server/image_pull.go
pkg/server/image_remove.go
pkg/server/image_status.go
pkg/server/instrumented_service.go
pkg/server/sandbox_list.go
pkg/server/sandbox_portforward.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/server/sandbox_stop.go
pkg/server/service.go
pkg/server/status.go
pkg/server/version.go

Move all grpc handler logs into a instrumented service, so that we don't need to care about it in the real service.

Add instrumented service.

---

pkg/server/sandbox_list.go
pkg/server/sandbox_list_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/server/sandbox_status_test.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/metadata_test.go
pkg/store/sandbox/sandbox_test.go

Addresses a TODO.
Ref https://github.com/kubernetes-incubator/cri-containerd/pull/156#discussion_r134677176. /cc @yanxuean 

Get CreatedAt from containerd instead of maintaining it ourselves.

---

.travis.yml

Latest node e2e failed again because log is too long. Since currently, node e2e is only best effort, let's not print any log for it, just show the test result.
https://travis-ci.org/kubernetes-incubator/cri-containerd/jobs/267875959
If we are going to debug a test failure, we need to reproduce it ourselves. I'll try to set up a node e2e test in Kubernetes test infra as soon as possible.

Not printing any log for node e2e.

---

pkg/server/container_create.go
pkg/server/sandbox_portforward.go
pkg/server/sandbox_run.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/sandbox_test.go

Address TODOs added in https://github.com/kubernetes-incubator/cri-containerd/pull/156.
* On one hand, we don't need to checkpoint sandbox pid, because we use sandbox when it's running, and we'll always be able to its pid from containerd.
* On the other hand, if we want to use containerd label to checkpoint sandbox pid, we have to update the label. Because we usually create label when create container, but we'll only be able to get pid after start task.
/cc @yanxuean 

Do not checkpoint sandbox pid.

---

hack/test-cri.sh
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go
vendor.conf
vendor/github.com/containerd/containerd/README.md
vendor/github.com/containerd/containerd/apparmor.go
vendor/github.com/containerd/containerd/spec.go
vendor/github.com/containerd/containerd/spec_opts.go
vendor/github.com/containerd/containerd/spec_opts_unix.go
vendor/github.com/containerd/containerd/spec_opts_windows.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go

This PR:
1) Update containerd to include the new `WithUsername`.
2) Fix several security related issues, including:
a) Set NoNewPrivs no matter the container is privileged or not (same with [what docker does](https://github.com/moby/moby/blob/master/daemon/oci_linux.go#L832)) https://github.com/kubernetes-incubator/cri-containerd/issues/166#issuecomment-324725784.
b) Set RunAsUser and SupplementalGroups for sandbox container.
c) Return error for privileged container if its corresponding sandbox doesn't allow privilege.
3) Add RunAsUsername support leveraging https://github.com/containerd/containerd/pull/1413.
/cc @zhangzhenhao

Add RunAsUser support

---

pkg/server/events.go

We should exclude the event of sandbox containers from event stream in order to avoid outputting unexpected error print.
related #173
/cc @Random-Liu 

Exclude the event of sandbox containers from event stream

---

pkg/server/container_create.go
pkg/server/container_stop.go
pkg/server/events.go
pkg/server/io/io.go
vendor.conf
vendor/github.com/containerd/containerd/process.go
vendor/github.com/containerd/containerd/spec_opts_unix.go
vendor/github.com/containerd/containerd/task.go
vendor/github.com/containerd/containerd/task_opts.go

This PR:
1) Update containerd to cf09e32618398fc59fcb45bcfe9b4c0335972733 to fix https://github.com/containerd/containerd/issues/1431 and https://github.com/containerd/containerd/pull/1433 (fixes https://github.com/kubernetes-incubator/cri-containerd/issues/176).
2) Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/169 by: a) Attach container stream before delete task, so that containerd client will properly wait and close stream; b) Create fifos inside container root directory, so that remove container root directory will also cleanup those fifo files.

Fix leak files

---

hack/test-e2e-node.sh
pkg/server/container_create.go
pkg/server/container_create_test.go

Use `rbind` and `rpivate` option for bind mount.
The QoS test mount host cgroup inside the container, and check whether QoS cgroups are created as expected. Without `rbind`, this won't work.
Now with this PR we could run QoS test.
Also ref https://github.com/kubernetes-incubator/cri-containerd/issues/185.

Use rbind and rprivate in bind mount.

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
pkg/server/container_create.go
pkg/server/image_pull.go
pkg/server/sandbox_run.go
pkg/server/service.go

This PR:
1) Move `WithNewSnapshotView` before `WithUserID` to fix the failing node e2e test https://travis-ci.org/kubernetes-incubator/cri-containerd/jobs/269887455. The test specifies user id on the sandbox container, but `WithUserID` doesn't work before `WithNewSnapshotView`. (Ref https://github.com/containerd/containerd/issues/1446)
2) Make containerd snapshotter configurable, so that people could use btrfs if they want.
/cc @crosbymichael

Fix sandbox container snapshotter.

---

pkg/opts/task.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

Fixes #118 
Contains fix to set the cgroup for the containerd shim same as the pod cgroup.

Setting containerd shim to Pod cgroup

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_selinux_test.go
pkg/server/sandbox_run.go
vendor.conf
vendor/github.com/opencontainers/selinux/LICENSE
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

Support selinux options/label

---

hack/test-e2e-node.sh
pkg/server/container_status.go
pkg/server/container_status_test.go
pkg/server/image_pull.go

For schema1 image, we should not use it's manifest digest as pullable repo digest, because it is not pullable.
However, the current logic is wrong, because `image.Target().MediaType` has already been converted https://github.com/containerd/containerd/blob/master/remotes/docker/schema1/converter.go#L156.
We could only figure out whether the image is schema1 ourselves.
With this PR and https://github.com/kubernetes/kubernetes/pull/51775, we could pass the image digest node e2e test.

Fix repo digest for schema 1 image.

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
pkg/server/helpers.go
pkg/server/service.go

The default sandbox image is `gcr.io/google_containers/pause:3.0`. However, someone may want to use another one. So make it configurable. Please refer to the issue https://github.com/kubernetes-incubator/cri-containerd/issues/191.
Signed-off-by: Jamie Zhuang <lanchongyizu@gmail.com>

Make sandbox container image configurable

---

.travis.yml
Makefile
hack/install-deps.sh
hack/release.sh

Add `make release` to:
1) Install all dependencies (containerd, runc and cni) into `_output/release-stage`;
2) Create tarball from `_output/release-stage`.
```console
$ tree _output/
_output/
├── cri-containerd
├── cri-containerd-0.1.0-158-g5ea9de0.tar.gz
└── release-stage
├── etc
│   └── cni
│       └── net.d
│           └── 10-containerd-net.conflist
├── opt
│   └── cni
│       └── bin
│           ├── bridge
│           ├── dhcp
│           ├── flannel
│           ├── host-local
│           ├── ipvlan
│           ├── loopback
│           ├── macvlan
│           ├── portmap
│           ├── ptp
│           ├── sample
│           ├── tuning
│           └── vlan
└── usr
└── local
├── bin
│   ├── containerd
│   ├── containerd-shim
│   ├── containerd-stress
│   ├── cri-containerd
│   └── ctr …
```

Add release tarball.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

This avoids errors such as:
spec: invalid environment variable "JAVA_OPTS=-Djava.security.egd=file:/dev/urandom"
use `SplitN(2)` to get the envvar name and value while allowing the value to
contain `=`.
Add some variables to the test data which have one or more `=` in the value.
Since this makes the resulting list of variables to check rather long split the
check in two and check the container config and image config derived values
independently.

Handle environment variables which containe spaces

---

pkg/server/container_create.go
pkg/server/sandbox_run.go

This will be made readonly by runc based on spec.Root.Readonly (which we
already set correctly) but defering until then gives runc the chance to make
any missing mount points as it processes the spec.Mount array.
This is necessary because many container images lack mount points for things
like the /etc/hosts which we want to overbind. This is not noticed with e.g.
Docker because it automatically creates an additional layer containing those.
This is something we may want to do here as well eventually but for now using a
writeable snapshot is both necessary and sufficient.
The same does not apply to the sandbox since we never modify its rootfs or want
to mount anything in it etc, add a comment to clarify.
Fixes #220.
//cc @Random-Liu

Always use a writeable snapshot as the rootfs.

---

pkg/server/service.go

Minor fix: Remove a TODO which has been addressed in https://github.com/kubernetes-incubator/cri-containerd/pull/207.
Simple but not urgent.

Remove an addressed TODO.

---

contrib/systemd-units/containerd.service
contrib/systemd-units/cri-containerd.service
hack/release.sh

@abhinandanpb Feel free to keep working on your systemd setup, and update these files with yours.
This PR:
1) Add the contrib directory, which will be used to place some other useful tools for cri-containerd, e.g. systemd units, default cni config, ansible playbook (@abhinandanpb) etc.
2) Add the systemd unit files for containerd and cri-containerd, and build them into release tarball.

Add systemd unit files for containerd and cri-containerd.

---

.travis.yml
hack/test-e2e-node.sh

Fixes: https://github.com/kubernetes-incubator/cri-containerd/issues/224
Node e2e works well. Here is the test log yesterday: http://gcsweb.k8s.io/gcs/cri-containerd_test-e2e-node/0.1.0-179-g7a75a91-20170907-084526/
Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/224
This PR will enable node e2e as post-submit test, and expose the failure, so that we'll get a node e2e test result each time after a new PR is merged.

Run node e2e for both cron and branch update

---

pkg/server/sandbox_run.go

See https://github.com/containerd/containerd/issues/1495.
Runc doesn't support readonly snapshot now.

Use `WithNewSnapshot` for sandbox container.

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/sandbox_run.go

For https://github.com/containerd/containerd/issues/1494.
Remove `/run` mount because Docker doesn't do that, and there are images relying on this behavior.
In we really want to make `/run` tmpfs in the future, we may need to handle copyup.

Remove `/run` mount for backward compatibility with docker.

---

hack/install-deps.sh
pkg/server/container_create.go

Docker is doing this. And Kubelet is replying on this behavior.
Ref https://github.com/kubernetes/kubernetes/issues/52318.
/cc @abhinandanpb 

Create host path is mount source does not exist.

---

pkg/server/container_create.go

This is docker's behavior, we should keep it for backward compatibility.
Also ref https://github.com/kubernetes/kubernetes/issues/52318#issuecomment-328736840.

Follow symlink for mount host path.

---

pkg/opts/container.go
pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

This carries #241 with additional fixes to the test suite from me. From @Random-Liu's original:
For image volume, currently we only:
1. Create host directory and mount into the image;
2. Change the ownership of the host directory to be the same with mount point inside the image.
What we are going to do in the future:
1. Consider whether we need to copy existing content in the image into the volume. #186.
2. Consider whether we should add the helper into containerd containerd/containerd#1482.
3. Consider how to properly manage these volumes in kubelet kubernetes/kubernetes#52032.

Add image volume support. 

---

pkg/server/container_create.go

This is needed by runc to mount volume for containers that expect
biderectional file updates.

Setting rootfs mount propagation if the mount type is rshared/shared

---

cmd/cri-containerd/cri_containerd.go
pkg/server/container_create.go
pkg/server/container_remove.go
pkg/server/image_pull.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
pkg/server/service.go
pkg/server/service_test.go

Address a TODO, use config in service, so as to get rid of the long arg list.

Use config in service.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

mount with `rshared`, the host path should be shared.
mount with `rslave`, the host pash should be shared or slave.
Based on #246 

Ensure the mount point is propagated

---

pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go
pkg/store/container/metadata.go
pkg/store/container/metadata_test.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/metadata_test.go

Switch to containerd extension

---

pkg/server/container_create.go
pkg/server/container_start.go
pkg/server/helpers.go
pkg/server/io/io.go
pkg/server/restart.go
pkg/server/sandbox_stop.go
pkg/server/service.go
pkg/store/container/container.go
pkg/store/container/container_test.go
pkg/store/container/metadata.go
pkg/store/container/metadata_test.go
pkg/store/container/status.go
pkg/store/container/status_test.go
pkg/store/sandbox/netns.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/120.
Add recovery logic during restart. I've manually tested this, it's working even better than I thought. :)
Based on https://github.com/kubernetes-incubator/cri-containerd/pull/206 and https://github.com/kubernetes-incubator/cri-containerd/pull/179.
@kubernetes-incubator/maintainers-cri-containerd Please review this carefully, especially `pkg/server/restart.go`. This is really important to the production quality.
I'll send another PR to add our own integration test framework, and will add restart test.

Checkpoint recovery

---

pkg/server/restart.go

Without this, we'll be able to create sandbox/container with the same name with sandbox/container created before restart.

Should register container/sandbox name after restart.

---

contrib/ansible/cri-containerd.yaml
contrib/ansible/tasks/binaries.yaml
contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/bootstrap_ubuntu.yaml
contrib/ansible/tasks/k8s.yaml
contrib/ansible/vars/vars.yaml
contrib/systemd-units/containerd.service
contrib/systemd-units/cri-containerd.service

This commit contains ansible playbooks to install kubernetes, cri-containerd and containerd components as well as supporting configurations and dependencies to facilitate the usage of the kubernetes cluster with containerd.
With this change users can bring up k8 cluster in 2 steps 
1) Run the ansible playbook to install the necessary components
2) Run kubeadm init to initialize the cluster and subsequently run kubeadm join on remaining nodes
I will follow up with another PR that will have detailed set of step by step guide to install kubernetes.
There is a lot of scope for improvements and optimization. This is first cut and will gradually update the playbooks and install methods subsequently.
This has been tested on ubuntu clusters. Though the centos playbooks are attached I havent …

kubernetes + cri-containerd + containerd installer

---

pkg/store/sandbox/netns.go
vendor/github.com/docker/docker/pkg/symlink/LICENSE.APACHE
vendor/github.com/docker/docker/pkg/symlink/LICENSE.BSD
vendor/github.com/docker/docker/pkg/symlink/README.md
vendor/github.com/docker/docker/pkg/symlink/fs.go
vendor/github.com/docker/docker/pkg/symlink/fs_unix.go
vendor/github.com/docker/docker/pkg/symlink/fs_windows.go

This PR:
1) Add the `FollowSymlinkInScope` back. We do need it, because `docker.mount.Mounted` is parsing mount table to check whether the netns path is mounted or not. And in the mount table, there is no symlink:
```
nsfs on /run/netns/cni-ae0e9def-11e6-c969-e12d-91087cef2f6a type nsfs (rw)
nsfs on /run/netns/cni-22fecd6d-fb4f-cec1-ecb2-ea56f6ceb83c type nsfs (rw)
nsfs on /run/netns/cni-4e8775b4-cc5e-bfdc-4a94-e1274f1a9c58 type nsfs (rw)
nsfs on /run/netns/cni-cbe0d199-cbe6-7b5a-9458-91a3a1d8cdf6 type nsfs (rw)
nsfs on /run/netns/cni-1d6452b9-1baa-ce6e-6781-0fe443376af8 type nsfs (rw)
tmpfs on /var/lib/kubelet/pods/0a61f550-8f8c-11e7-beef-42010af00002/volumes/kubernetes.io~projected/podinfo type tmpfs (rw,relatime)
nsfs on /run/netns/cni-df8c311c-9c7f-f4d5-77d6-a0ecbc71f659 type nsfs …
```

Fix checkpoint recovery.

---

hack/cri-reset.sh

Adding a reset script to supplement kubeadm reset. Since kubeadm doesnt yet support complete toolset this will be acting as a supplement to kubeadm reset to clear the sandboxes, containers and images.

Adding cri reset script for resetting the states

---

.travis.yml
Makefile
cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
pkg/server/container_create.go
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_disabled.go

Previous behavior:
* If selinux is not supported (not built / OS not support):
* `EnableSelinux=true`: cri-containerd doesn't report any error, but won't set any selinux options. **(Not Expected)**
* `EnableSelinux=false`: cri-containerd doesn't set selinux options.
* If apparmor is not supported (not built / OS not support):
* `EnableAppArmor=true`: cri-containerd always applies default to container and we'll never be able to start a container.**(Not Expected)**
* `EnableAppArmor=false`: cri-containerd won't apply apparmor profile.
With this PR, for either selinux or apparmor, if the feature is not supported, cri-containerd will:
* `EnableXXX=true`: cri-containerd will log an error at start up, and not set corresponding options. The log will be something like:
```
E0922 04:43:31.108763 …
```

Improve apparmor and selinux support.

---

contrib/ansible/cri-containerd.yaml

This PR:
1) Set `net.ipv4.ip_forward=1`, which is required by Kubernetes.
2) Use ansible sysctl support instead. Current code has an extra `\/` in front of the regexp, which will never match, thus ansible will put a sysctl entry each time it runs.
3) Format the indent a little bit.

Add net.ipv4.ip_forward=1 and use ansible sysctl.

---

.travis.yml
Makefile
cmd/cri-containerd/options/options.go
hack/test-e2e-node.sh
hack/test-integration.sh
hack/test-utils.sh
integration/imagefs_info_test.go
integration/test_utils.go
pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/imagefs_info.go
pkg/server/imagefs_info_test.go
pkg/server/instrumented_service.go
pkg/server/service.go
pkg/server/service_test.go
pkg/server/snapshots.go
pkg/store/image/image.go
pkg/store/image/image_test.go
pkg/store/snapshot/snapshot.go
pkg/store/snapshot/snapshot_test.go
vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/services.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/doc.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_image.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/remote_runtime.go
vendor/k8s.io/kubernetes/pkg/kubelet/remote/utils.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/doc.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/util.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unix.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/util_unsupported.go
vendor/k8s.io/kubernetes/pkg/kubelet/util/util_windows.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/195.
Part of https://github.com/kubernetes-incubator/cri-containerd/issues/121.
Depends on https://github.com/kubernetes/kubernetes/pull/52635.
This PR:
1) Update Kubernetes to include CRI stats fix. https://github.com/kubernetes/kubernetes/pull/52635
2) Add `ImageFsInfo` support.
3) Add integration test framework and integration test for `ImageFsInfo`.
@kubernetes-incubator/maintainers-cri-containerd

Add image stats and integration test

---

Makefile
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/sandbox_run.go
pkg/server/service.go
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go
vendor/github.com/seccomp/libseccomp-golang/LICENSE
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

This PR:
1) Use `runc/libcontainer/seccomp` to check whether seccomp is enabled on OS.
2) Move apparmor and seccomp logic into helper functions.
3) Add unit test for apparmor and seccomp logic.
@mikebrow 

Check seccomp enable and add unit test for seccomp/apparmor.

---

hack/install-deps.sh
hack/release.sh

Do not include CNI binaries/configs in release tarball. In real use, user should launch their own CNI daemonset to deploy cni binaries and configs, we should not include one in release tarball.
@abhinandanpb @mikebrow 

Do not include CNI binaries/configs in release tarball.

---

cmd/cri-containerd/options/options.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Add systemd cgroup support.
This is part of https://github.com/kubernetes-incubator/cri-containerd/pull/275 and one of missing features in https://github.com/kubernetes-incubator/cri-containerd/issues/62.

Add systemd cgroup support.

---

contrib/ansible/cri-containerd.yaml
contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/bootstrap_ubuntu.yaml
contrib/ansible/vars/vars.yaml

This PR:
1) Add `modprobe br_netfilter`, which is required by kubelet. Without which `net.bridge.bridge-nf-call-iptables` won't work, either.
2) Stop using dev library, which is not needed for running cri-containerd.
3) Add systemd dropin for cri-containerd, previous solution always report an error during installation, which is confusing to user.
4) Update cri-containerd to newest version.

Improve ansible playbook.

---

integration/container_stats_test.go
integration/test_utils.go
pkg/server/container_stats.go
pkg/server/container_stats_list.go

Built on top of #257 
Review by commits
1) Implements ListContainerStats and ContainerStats to collect metrics from containerd
2) Added couple of integration tests to verify stat collection
This commit does not include caching. Caching will be implemented if the benchmark results go northwards.

Adding container metrics support

---

cmd/cri-containerd/options/options.go
pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/image_pull.go
pkg/server/sandbox_run.go
pkg/server/service.go

Enables changing the defaults used by containerd for the location of runtime state (/var/lib/containerd by default), the name of the runc compatible runtime-engine (runc by default), and whether systemd cgroup support is enabled (false by default).
Note: these are specified in the containerd client api as options on each new container. 

Adds support for configuring the containerd runtime engine

---

pkg/server/container_stats.go
pkg/server/container_stats_list.go

This PR:
1) Fix a potential panic in `ContainerStats`;
2) Fix a incorrect check `r.GetFilter == nil`, `GetFilter` is a function;
3) Refactor the code a little bit, so that we only access container store once to avoid the race;
4) Simplify the code a little bit.

Fix and cleanup container metrics

---

cmd/cri-containerd/cri_containerd.go
pkg/os/os.go
pkg/server/service.go

Information seems not sufficient from https://github.com/kubernetes-incubator/cri-containerd/issues/298.
Format several error mesage. 

Better format several errors

---

pkg/server/container_stats_list.go
pkg/server/instrumented_service.go

`Inodes` and `UsedBytes` are not set correctly.

Fix container stats.

---

cmd/cri-containerd/options/options.go

`pflag` doesn't print default `false` boolean or default empty string, that seems to be how it works.
I'm fine with this behavior.
@mikebrow WDYT? Do you think we should always add default ourselves for all `false` boolean or empty stirng?

Cleanup flag default value

---

contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

Update ansible playbook to use v1.0.0-alpha.0 release.

Update ansible playbook release version.

---

docs/proposal.md

The design proposals were organized according to SIGs in https://github.com/kubernetes/community/pull/1010. This led to a broken link.

Fix link after design proposals move

---

integration/container_update_resources_test.go
integration/test_utils.go
pkg/server/container_attach.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/container_execsync.go
pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/container_stop.go
pkg/server/container_update_resources.go
pkg/server/container_update_resources_test.go
pkg/server/events.go
pkg/store/container/client.go
pkg/store/container/container.go
pkg/store/container/metadata.go
pkg/store/sandbox/sandbox.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/316.
@abhi @mikebrow @kelseyhightower

Fix update container resources

---

hack/test-e2e-node.sh

Add timeout for node e2e test.
The build is red now, it seems that cri-containerd or containerd gets unresponsive during test running. However,
1) I could not reproduce it in my local machine;
2) because of travis 50m test timeout, it doesn't even get a chance to upload test log, so that there is no way to debug it.
This PR added 40m timeout to node e2e test. Usually it only takes 30-31 minutes. If it timeout, test will abort, and we still get the chance to collect test logs.

Add node e2e test timeout.

---

pkg/opts/container.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/317.
See reason https://github.com/kubernetes-incubator/cri-containerd/issues/317#issuecomment-334305411.
/cc @ijc 

Skip not exist image volume directory.

---

pkg/server/container_stats_list.go

Currently, **containerd returns stats with empty contents for stopped task** (See https://github.com/containerd/containerd/blob/master/linux/task.go#L256).
If we access fields of the stats directly, it will cause a panic, and I did see it in my test:
```
I1004 23:26:45.253172     370 instrumented_service.go:290] ImageFsInfo returns filesystem info [&FilesystemUsage{Timestamp:1507159602508004076,StorageId:&StorageIdentifier{Uuid:70045b4a-dd4c-4e37-889c-f1992da26c82,},UsedBytes:&UInt64Value{Value:861907840,},InodesUsed:&UInt64Value{Value:27594,},}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0x1782c1f]
goroutine 770 [running]:
github.com/kubernetes-incubator/cri-containerd/pkg/server.(*criContainerdSer …
```

Fix container stats panic.

---

README.md
docs/installation.md

Added a instruction to install cri-containerd from release tarball.

Add guide for installation from release tarball

---

Makefile
pkg/server/version.go
pkg/version/version.go
pkg/version/version_test.go

Changed `Version` to use cri-containerd version.
We still want to call the runtime `containerd` in the future not to confuse people, but we do need both cri-containerd and containerd version if we don't bundle them well.
This is a problem we need to discuss and fix, but for now just expose cri-containerd version for ease of our development, because we could always infer containerd version from cri-containerd version in our test environment.

Change `Version` to return cri-containerd version instead.

---

.travis.yml
Makefile
hack/push.sh
hack/release.sh

This PR:
1) Add separate tar for node e2e test which contains CNI in the tar.
2) Push a file named `latest` in `cri-containerd-staging`. Other tool could read `latest` to know the latest version. /cc @abhi 
Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/304.

Add staging tar for node e2e.

---

hack/verify-lint.sh

It seems that there is some update on the gometalinter side.
The build is failing because of something like:
```
pkg/store/container/status.go:43:13:warning: struct of size 80 could be 72 (maligned)
```
Personally, I don't think we care about this that much. Code readability is more important for us. For example, we may want to place struct fields in logic order instead of moving them around to make the struct align better.
@abhi @mikebrow WDYT?

Disable maligned check.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/service.go

Use linux device number from `mount.Lookup` to look for uuid.
This may be able to fix https://github.com/kubernetes-incubator/cri-containerd/issues/325.
And I also see the Ubuntu used by GKE, rootfs is mounted from `/dev/root`, which doesn't have real corresponding device file.
With this fix, we get device number from mount directly, and find uuid with the device number. This doesn't assume that the mount source has to be a existing file.

Use device number to find uuid

---

pkg/server/container_attach.go
pkg/server/container_exec.go
pkg/server/container_execsync.go
pkg/server/image_pull.go
pkg/server/restart.go
pkg/server/sandbox_portforward.go
pkg/store/container/container.go
pkg/store/container/container_test.go
pkg/store/image/image.go
pkg/store/image/image_test.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go
vendor.conf
vendor/github.com/docker/docker/pkg/truncindex/truncindex.go
vendor/github.com/tchap/go-patricia/LICENSE
vendor/github.com/tchap/go-patricia/README.md
vendor/github.com/tchap/go-patricia/patricia/children.go
vendor/github.com/tchap/go-patricia/patricia/patricia.go

Add Truncindex for container, sandbox and image

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Address [this comment](https://github.com/kubernetes-incubator/cri-containerd/pull/257#issuecomment-330152858).  

Get the mountInfo by 'LookupMount' in containerd

---

cmd/cri-containerd/options/options.go
pkg/server/service.go

Add a flag to set OOMScore

---

contrib/systemd-units/cri-containerd.service
test/e2e_node/init.yaml

Remove OOMScore from systemd units. The default -999 oom score is set in https://github.com/kubernetes-incubator/cri-containerd/pull/347.

Remove the oom score in systemd unit. cri-containerd sets it by itself.

---

pkg/server/container_create_test.go
pkg/util/strings.go
pkg/util/strings_test.go

I happened to spot this in https://goreportcard.com/report/github.com/kubernetes-incubator/cri-containerd, should take our misspell score from 98% to 100%.

typo: subtract not substract.

---

pkg/server/restart.go

check image readiness when recover

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
vendor.conf
vendor/github.com/inconshreveable/mousetrap/LICENSE
vendor/github.com/inconshreveable/mousetrap/README.md
vendor/github.com/inconshreveable/mousetrap/trap_others.go
vendor/github.com/inconshreveable/mousetrap/trap_windows.go
vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
vendor/github.com/spf13/cobra/LICENSE.txt
vendor/github.com/spf13/cobra/README.md
vendor/github.com/spf13/cobra/bash_completions.go
vendor/github.com/spf13/cobra/cobra.go
vendor/github.com/spf13/cobra/command.go
vendor/github.com/spf13/cobra/command_notwin.go
vendor/github.com/spf13/cobra/command_win.go

Use cobra for cli. With this change, the command will be like:
```console
$ ./_output/cri-containerd --help
_                         __        _                      __
__________(_)      _________  ____  / /_____ _(_)____  ___  _________/ /
/ ___/ ___/ /______/ ___/ __ \/ __ \/ __/ __ `/ // __ \/ _ \/ ___/ __  /
/ /__/ /  / //_____/ /__/ /_/ / / / / /_/ /_/ / // / / /  __/ /  / /_/ /
\___/_/  /_/       \___/\____/_/ /_/\__/\__,_/_//_/ /_/\___/_/   \__,_/
A containerd based Kubernetes CRI implementation.
Usage:
cri-containerd [flags]
cri-containerd [command]
Available Commands:
default-config Print default toml config of cri-containerd.
version        Print cri-containerd version information.
Flags:
--alsologtostderr                    log to standard error as well as files
--cgroup-path …
```

Change to cli

---

pkg/opts/task.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

Fixes #217 
Related to #193 
I checked out #193 and verified this with following sandbox config in my host:
```json
{
"metadata": {
"name": "nginx-sandbox",
"namespace": "default",
"attempt": 10,
"uid": "hdishd83djaidwnduwk28bcsb"
},
"linux": {
"cgroup_parent": "/miaoyq"
}
}
```
Always failed with ` failed to load cgroup /miaoyq: cgroups: cgroup deleted: unknown` error if the cgroup have not been created :
```shell
FATA[0001] Run pod sandbox failed: rpc error: code = Unknown desc = failed to create task for sandbox "9536a3fbaf6119cca433b449b1ea9b3db7c60fe88fbd2dfca88b0fa7de4d1026": failed to load cgroup /miaoyq: cgroups: cgroup deleted: unknown 
FATA[0002] Run pod sandbox failed: rpc error: code = Unknown desc = failed to create task for sandbox …
```

Put containerd-shim into pod cgroup

---

pkg/opts/container.go
pkg/server/container_create.go
pkg/server/image_pull.go
pkg/server/restart.go
pkg/server/sandbox_run.go

To pull an image in containerd, we need to:
1) Download all contents;
2) Write image reference.
3) Unpack image into snapshotter.
Currently, if 3) fails, we don't rollback 1) and 2). If we don't put the image into our list, containerd will not garbage collect it, and the content will be left there forever.
We have 2 options for this:
1) Rollback 1) and 2) ourselves, which is a bit unreliable, expensive and complex.
2) Only do best effort unpack during image pulling, and always check snapshot existence and unpack image before container creation. This is more reliable, and is also recommended by https://github.com/containerd/containerd/pull/1567#issuecomment-333632696 @stevvooe 
This PR goes with option 2.

Also unpack image during creation.

---

pkg/server/container_create.go
pkg/server/sandbox_run.go

Add log for generated id. We need these IDs to map container in containerd.log.

Add log of generated id for debugging.

---

test/e2e_node/configure.sh

Sometimes retrieving latest version may timeout. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e/237
```
Oct 26 19:44:01 tmp-node-e2e-f96385d2-cos-stable-60-9592-84-0 configure.sh[973]: ++ curl --fail --retry 5 --retry-delay 3 --silent --show-error https://storage.googleapis.com/cri-containerd-staging/latest
Oct 26 19:46:09 tmp-node-e2e-f96385d2-cos-stable-60-9592-84-0 configure.sh[973]: curl: (7) Failed to connect to storage.googleapis.com port 443: Connection timed out
Oct 26 19:46:09 tmp-node-e2e-f96385d2-cos-stable-60-9592-84-0 configure.sh[973]: + VERSION=
```
This PR adds `--ipv4` in `curl`, because:
1) Kubernetes scripts are all using `--ipv4` to download from gcs;
2) There seems to be some problem with curl download without specifying …

Add `--ipv4` in `curl`.

---

cmd/cri-containerd/cri_containerd.go

Using the same code with https://github.com/containerd/containerd/pull/292.

Add stack dump.

---

pkg/server/io/logger.go
test/e2e_node/init.yaml

We should not log container output into our error log.
In my cluster, fluentd keeps logging error message, which fills up the disk. After that cri-containerd will not be able to redirect log for it because the disk is full.
In that case,
1) I see tons of error message including container output in cri-containerd.log, which is too spammy. So in this PR, I removed the container output from the error log.
2) I see `/tmp` directory is filled up very soon, because glog is logging into it by default. So in this PR I use `--logtostderr` instead of `--alsologtostderr` to avoid glog writing to `/tmp`.

Do not log container output in error log.

---

pkg/server/container_status.go
pkg/server/container_status_test.go

The field was introduced https://github.com/kubernetes/kubernetes/pull/45580, we should provide it because `crictl` is using it.

Add the missing container log path in container status.

---

contrib/ansible/cri-containerd.yaml
contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/194.
Put both `cri-containerd` and `containerd` into a runtime cgroup `/runtime` in ansible playbook. I'll do the same for `kube-up.sh`.

Add runtime cgroup and put containerd and cri-containerd into it.

---

pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/events.go
pkg/store/container/fake_status.go
pkg/store/container/status.go
pkg/store/container/status_test.go

In a test, I saw that we could never remove a container any more once containerd container removal returns an error.
```
E1029 23:59:48.015653    1035 container_remove.go:56] failed to reset removing state for container "9271ad01c1ef091260fca1b432128d98d3b6e40735f8e6b3d8f6d8d10d58ac56": failed to checkpoint status to "/var/lib/cri-containerd/containers/9271ad01c1ef091260fca1b432128d98d3b6e40735f8e6b3d8f6d8d10d58ac56/status": open /var/lib/cri-containerd/containers/9271ad01c1ef091260fca1b432128d98d3b6e40735f8e6b3d8f6d8d10d58ac56/.tmp-status551243121: no such file or directory
E1029 23:59:48.015675    1035 instrumented_service.go:176] RemoveContainer for "9271ad01c1ef091260fca1b432128d98d3b6e40735f8e6b3d8f6d8d10d58ac56" failed, error: failed to delete containerd container …
```

Fix removing state recover.

---

.travis.yml
test/e2e_node/build.sh
test/e2e_node/configure.sh

We'll also need tarball with CNI for master node in cluster e2e, so rename the tarball to `cri-containerd-cni`.

Rename release tarball for node e2e to cri-containerd-cni.

---

contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml

Update cri-containerd version to 1.0.0-alpha.1 in ansible.

---

test/build.sh
test/configure.sh
test/e2e/master.yaml
test/e2e/node.yaml
test/e2e_node/image-config.yaml
test/e2e_node/init.yaml

This PR added cloud-init file and scripts for cri-containerd integration with `kube-up.sh`.
Also see https://github.com/kubernetes/kubernetes/pull/54964.

Add e2e test

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/load.go

This PR:
1) Moves load command logic into a separate file, because it grows a bit big.
2) Get rid of the leading new line in the help message.
It becomes cleaner:
```console
$ ./cri-containerd help load
Help for "load TAR" command
TAR - The path to a tar archive containing a container image.
Requirement:
Containerd and cri-containerd daemons (grpc servers) must already be up and
running before the load command is used.
Description:
Running as a client, cri-containerd implements the load command by sending the
load request to the already running cri-containerd daemon/server, which in
turn loads the image into containerd's image storage via the already running
containerd daemon.
Usage:
cri-containerd load TAR [flags]
Example:
- use docker to pull the latest busybox image and save it as a …
```

Cleanup image load code a bit.

---

pkg/server/sandbox_status.go
pkg/store/sandbox/netns.go

In test log, I see tons of:
```
I1102 16:21:55.828275    1908 sandbox_status.go:102] getIP: failed to read sandbox "f20ab1e5e0d4e8f35a2fb38b8831d1b1c15393045f4416f307418caacec85180" IP from plugin: Unexpected command output nsenter: cannot open /var/run/netns/cni-82f4ccd1-72c7-495b-602e-eee9503a1d13: No such file or directory
```
When we try to get status of a stopped sandbox, the network namespace has been removed, and we'll see this error.
This doesn't harm, but cause confusion and also very spammy.
This PR checks whether network namespace is closed before we call `netPlugin.GetPodNetworkStatus`, which tries to `nsenter` into the network namespace.

Get rid of spammy CNI log.

---

pkg/server/container_create.go

Since https://github.com/moby/moby/pull/35344 we clarified that this behaviour
was a mistake, and the read only flag should just apply to the actual rootfs,
so it corresponds to the OCI read-only option. Other mounts may be able to be
adjusted by re-specifying them or other means but this is unrelated.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Remove comment about whether other paths should be read only with root

---

contrib/ansible/cri-containerd.yaml

The `include` cmd in ansible playbook is deprecated and will remove in 2.8, replace `include` with `include_tasks` to remove warning when ansible-playbook.

replace deprecated ansible include cmd

---

pkg/server/container_status.go
pkg/server/container_status_test.go

The `kubectl` rolling upgrade test is relying on this behavior.
This is the same with dockershim https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L375.
The behavior is not clearly defined, but to avoid regression, let's keep it the same with dockershim for now.
**With this I think we could pass all cluster e2e test now.** Let me try again tomorrow.

Return image tag as image spec.

---

pkg/ioutil/read_closer.go
pkg/ioutil/read_closer_test.go
pkg/server/container_attach.go
pkg/server/container_execsync.go
pkg/server/io/io.go

I've tried cluster e2e in my own cluster, and we could pass most of the test.
There are around 5 test failure I got, this PR fixes 2 of them.
This PR:
1) Add `TERM=xterm` env when do container exec. Sometimes the original container may not have `tty`, thus no `TERM=xterm`. But if we exec with tty, we should add this.
2) Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/354. Moved resize handling after task start, so that we won't miss the first resize request. https://github.com/kubernetes/kubernetes/pull/47991 @abhi Could you verify whether you still have the exec problem after this PR is merged?
3) Fix a case that `Attach` may hang. Previously after stdout/stdin is closed, we close the reader side of stdin. However, that doesn't stop `io.Copy` if the writer side …

Various fixes for container streaming.

---

pkg/server/io/io.go

The logic for `tty` is wrong. Fix it.

Reverse the wrong logic for tty.

---

cmd/cri-containerd/options/options.go

After this change:
```console
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true
},
{
"type": "NetworkReady",
"status": true
}
]
},
"config": {
"containerd": {
"rootDir": "/var/lib/containerd",
"snapshotter": "overlayfs",
"endpoint": "/run/containerd/containerd.sock",
"runtime": "io.containerd.runtime.v1.linux"
},
"cni": {
"pluginBinDir": "/opt/cni/bin",
"pluginConfDir": "/etc/cni/net.d"
},
"socketPath": "/var/run/cri-containerd.sock",
"rootDir": "/var/lib/cri-containerd",
"streamServerPort": "10010",
"sandboxImage": "gcr.io/google_containers/pause:3.0",
"statsCollectPeriod": 10,
"oomScore": -999,
"enableProfiling": true,
"profilingPort": "10011",
"profilingAddress": "127.0.0.1"
}
}
```

Cleanup config.

---

pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go

Currently we have the pod and container labels part of
containerd metadata extensions. However for third party users
like cadvisor that depend on standard kube labels will need
to be aware of the way metadata is stored in containerd to
fetch the labels.

Adding kube pod and container labels to containerd

---

pkg/ioutil/writer_group.go
pkg/server/container_create.go
pkg/server/io/io.go
pkg/server/restart.go

Fix test `Simple pod should support inline execution and attach`.
https://k8s-testgrid.appspot.com/sig-node-containerd#e2e-gci
The test leaves stdin open after:
``` console
$ kubectl --server=https://localhost:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig --namespace=e2e-tests-kubectl-7sgm7 run run-test-3 --image=busybox --restart=OnFailure --attach=true --leave-stdin-open=true --stdin -- sh -c cat && echo 'stdin closed'
```
and then assumes that `stdin closed` SHOULD NOT be printed.
However, with current cri-containerd, we open and close the stdin pipe, which seems to trigger `cat` to return, although I don't know why...
I observed that:
1) If we open the stdin fifo writer side after containerd opens the stdin fifo reader side. When we close it, `cat` will return.
2) If we open …

Keep stdin open instead of opening when use it.

---

pkg/ioutil/read_closer.go

Our e2e test still has one last test timeout.
The reason is that the previous read closer wrapper is not designed properly.
For streaming pipe, read usually blocks. It means that the `wrapReadCloser` will hold lock and block on `Read`. When it blocks on read, all `Close` will hang forever.
However a real `ReadCloser` should be able to be closed when someone is reading it.
This PR uses `io.Pipe` instead, which fixes the issue.

Fix streaming deadlock.

---

pkg/server/container_create.go

Old:
```
I1111 08:58:01.855644   21354 container_create.go:149] Container spec: &{Version:1.0.0 Process:0xc420761ad0 Root:0xc420713d00 Hostname: Mounts:[{Destination:/proc Type:proc Source:proc Options:[]} {Destination:/dev Type:tmpfs Source:tmpfs Options:[nosuid strictatime mode=755 size=65536k]} {Destination:/dev/pts Type:devpts Source:devpts Options:[nosuid noexec newinstance ptmxmode=0666 mode=0620 gid=5]} {Destination:/dev/shm Type:tmpfs Source:shm Options:[nosuid noexec nodev mode=1777 size=65536k]} {Destination:/dev/mqueue Type:mqueue Source:mqueue Options:[nosuid noexec nodev]} {Destination:/sys Type:sysfs Source:sysfs Options:[nosuid noexec nodev ro]} {Destination:/sys/fs/cgroup Type:cgroup Source:cgroup Options:[nosuid noexec nodev relatime ro]} {Destination:/etc/resolv.conf …
```

Print full container spec for debugging.

---

pkg/server/container_create.go

Many integration test failures are caused by this. It's very easy to reproduce by running volume e2e test with parallelism 30.
Original I thought `append(command, args...)` is a read only operation, but it seems not.
When different containers using the same image are created at the same time, they'll access the command and args at the same time, `append(command, args...)` seems to corrupt the underlying memory block.
With this fix, I could not reproduce the failure any more.

Fix data race.

---

Makefile
hack/install-deps.sh

Was installing this on a minimal host and this would be superrrrr helpful!
Thanks!

Makefile: release static binaries

---

.travis.yml
test/verify.sh

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/418.
`make verify` usually OOMs after upgrading to golang 1.9. e.g. https://travis-ci.org/kubernetes-incubator/cri-containerd/jobs/303420847.
This PR configure `gometalinter` to only run 2 linters at the same time to reduce memory usage. By default it's 8, and I tried on my workstation, each linter sometimes take more than 1 GB RES memory.

Move verify to kubernetes test-infra.

---

integration/duplicate_name_test.go

Add integration test for duplicated sandbox/container creation.

Should not be able to create existing sandbox/container.

---

contrib/ansible/README.md

Replaced error on Ansible README.

contrib instead of contib

---

pkg/server/container_status_test.go
pkg/server/helpers.go
pkg/server/image_list_test.go
pkg/store/image/image.go
pkg/store/image/image_test.go

refer to #352
We get image by localResolve(). 
The localResolve receive these arguments as below:
1. imageID.   e.g.   sha256:xxxxxx
2. repotag.    e.g.   busybox:1.26
3. repodigest.   e.g.  busybox@sha256:xxxxx
Now we need it to support  the truncindex of imageID.
Because it is imageID that we store into imageStore, so at first the  localResolve() must treat the argument as the truncindex of imageID .
@mikebrow @Random-Liu

support get image by truncindex

---

pkg/containerd/opts/container.go
pkg/server/container_create.go
pkg/server/sandbox_run.go

This only performs an unpack if there is an error when creating the
container (and only if it's a "not found' error) since it should already
be unpacked.

Remove explicit unpack on all container creates

---

vendor/github.com/containerd/containerd/client.go
vendor/github.com/containerd/containerd/container_opts.go
vendor/github.com/containerd/containerd/container_opts_unix.go
vendor/github.com/containerd/containerd/image.go
vendor/github.com/containerd/containerd/remotes/docker/schema1/converter.go
vendor/github.com/containerd/containerd/remotes/handlers.go
vendor/github.com/containerd/containerd/task.go

For https://github.com/containerd/containerd/issues/1785.
This PR partially revert https://github.com/containerd/containerd/pull/1690 in vendored containerd client.
Note that:
1. Image load logic is not changed, because that never fails in test.
2. A check point related `gc.root` is not added because that is on server side which we are not vendoring. However, we don't use checkpoint anyway.
If after this, the test failure never happens again, we may want to keep this until containerd side is fixed.
If after this, the test still fails, we should revert this PR immediately.

Add gc.root back in vendored containerd client.

---

pkg/opts/task.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

This is same as https://github.com/kubernetes-incubator/cri-containerd/pull/193 which was reverted due to failures in node-e2e on the CI. Havent been able to reproduce it locally. 

Setting containerd shim cgroup same as pod cgroup

---

pkg/containerd/opts/task.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

Custom options are moved to `pkg/containerd/opts` now.
And we need boilerplate.

Move shim cgroup opts to pkg/containerd/opts.

---

pkg/server/container_status.go
pkg/server/container_status_test.go

Related to https://github.com/kubernetes-incubator/cri-containerd/issues/472.
Currently `map` doesn't preserve order. Use a big struct to enforce the field order.
@mikebrow PTAL. If this makes sense, we should apply the same behavior to the other status functions.

Use one big info struct before we change info to an array.

---

OWNERS

Propose new approvers in OWNERS file.
Actually I don't know what OWNERS file in incubator project could do. The github team/permission should make more sense. :) Anyway, let's still maintain the OWNERS file.
Propose @abhi and @yanxuean as new approvers. /cc @mikebrow 

Add new approvers to the OWNERS file.

---

pkg/server/container_status.go
pkg/server/sandbox_status.go

https://github.com/kubernetes-incubator/cri-containerd/issues/359
Commit 1: adds verbose info to pod status request
So far the additional info provided is the verbose "container" status.
There's a lot of good stuff already in the pod status response struct.
Commit 1: also adds sandboxID to the container status to allow for back tracking from the container to the pod sandbox.
Commit 2: fixes the pid reported by container status.

adding info map for verbose pod status

---

.travis.yml

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/476
This accelerates the presubmit test and also avoids race with `ci-cri-containerd-build` in kubernetes test-infra.

Remove travis deploy.

---

hack/test-utils.sh
integration/restart_test.go
integration/test_utils.go
pkg/client/client.go

For https://github.com/kubernetes-incubator/cri-containerd/issues/238.
Add integration test to test sandbox state recovery across cri-containerd restart.

Add restart test for sandbox recovery.

---

pkg/server/container_status.go
pkg/server/sandbox_status.go

This PR:
1) Add `Path` and `Args` in container info. `docker inspect` also has this information at top.
2) Add `NetNS`, `NetNSClosed`, `Image` and `SandboxConfig` in sandbox info.
3) Reuse `containerd.Task`.
4) Some small cleanups. Please review the first commit first, the second one just moved a function.
@mikebrow

Improve container sandbox status

---

pkg/server/container_create.go
pkg/server/container_stop.go
pkg/server/helpers.go
pkg/server/image_list.go
pkg/server/image_list_test.go
pkg/server/image_load.go
pkg/server/image_pull.go
pkg/server/image_status.go
pkg/server/image_status_test.go
pkg/server/restart.go
pkg/server/sandbox_run.go
pkg/store/image/image.go
pkg/store/image/image_test.go

This commit addresses #359 image status debug, adds verbose info to image status request, and also does some refactoring.

adding info map for verbose image status

---

pkg/server/sandbox_status.go
pkg/server/sandbox_status_test.go
pkg/store/image/image.go
pkg/store/image/image_test.go

Addresses:
* https://github.com/kubernetes-incubator/cri-containerd/pull/479#discussion_r155183127
* https://github.com/kubernetes-incubator/cri-containerd/pull/470#discussion_r156522507
* https://github.com/kubernetes-incubator/cri-containerd/pull/470#discussion_r156522507
/cc @mikebrow @yanxuean 

Minor cleanup.

---

Makefile
cluster/gce/configure.sh
contrib/ansible/tasks/binaries.yaml
contrib/ansible/vars/vars.yaml
docs/installation.md
hack/install-deps.sh
hack/push.sh
hack/release.sh
hack/test-utils.sh
test/configure.sh

This PR:
1) Add OS and arch in release tarball name.
2) Generate sha1sum for release tarball.
3) Update version to 1.0.0-beta.0 to prepare for the release.

Add OS and arch in release tarball.

---

README.md
docs/crictl.md

Addresses #96; adds documentation describing how to use crictl to aid in debugging CRI-Containerd.

add docs for using crictl

---

README.md
cluster/gce/configure.sh
cluster/gce/env
docs/installation.md
docs/kube-up.md
docs/testing.md
test/configure.sh

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/289.
This PR added a document for using `kube-up.sh`.

Add document for kube-up.sh

---

Makefile
hack/update-vendor.sh

Part of #385
Compare vendor with hack/versions, update hack/versions if the commit id different from vendor.conf.
If OK, I will update `CONTRIBUTING.md`.

Compare vendor with hack/versions and update hack/versions

---

docs/installation.md
hack/push.sh
hack/release.sh
hack/test-utils.sh

Use sha256 instead of sha1.

---

pkg/server/container_create.go
pkg/server/container_execsync.go
pkg/server/container_update_resources.go
pkg/server/helpers.go
pkg/server/sandbox_run.go

Fixes https://github.com/kubernetes-incubator/cri-containerd/issues/517.
We should enable the `HostSpecific` option, so that the generator will apply host specific cap list https://github.com/opencontainers/runtime-tools/blob/master/generate/generate.go#L1023.

Fix privileged caps

---

vendor.conf
vendor/github.com/json-iterator/go/README.md
vendor/github.com/json-iterator/go/feature_adapter.go
vendor/github.com/json-iterator/go/feature_any.go
vendor/github.com/json-iterator/go/feature_config.go
vendor/github.com/json-iterator/go/feature_iter.go
vendor/github.com/json-iterator/go/feature_iter_array.go
vendor/github.com/json-iterator/go/feature_iter_int.go
vendor/github.com/json-iterator/go/feature_iter_object.go
vendor/github.com/json-iterator/go/feature_iter_skip.go
vendor/github.com/json-iterator/go/feature_iter_skip_sloppy.go
vendor/github.com/json-iterator/go/feature_iter_skip_strict.go
vendor/github.com/json-iterator/go/feature_iter_string.go
vendor/github.com/json-iterator/go/feature_json_number.go
vendor/github.com/json-iterator/go/feature_pool.go
vendor/github.com/json-iterator/go/feature_reflect.go
vendor/github.com/json-iterator/go/feature_reflect_array.go
vendor/github.com/json-iterator/go/feature_reflect_extension.go
vendor/github.com/json-iterator/go/feature_reflect_native.go
vendor/github.com/json-iterator/go/feature_reflect_slice.go
vendor/github.com/json-iterator/go/feature_reflect_struct_decoder.go
vendor/github.com/json-iterator/go/feature_stream.go

We do have the dependency in `vendor/`, but don't know why we miss it in `vendor.conf`.
Since we do have the dependency in `vendor/`, it does build, but we are not using the correct version of `github.com/json-iterator/go`.

Add missing vendor into vendor.conf.

---

hack/install-deps.sh

Fix install-deps.
When run `make install-deps`, `sudo` will be enabled because we need to install to `/usr/local/bin`.
However, `sudo` doesn't inherit environment variables, we need to explicitly set the temporary `GOPATH` for `make install`.

Fix install-deps

---

hack/push.sh
hack/release.sh
hack/test-utils.sh
hack/update-vendor.sh
hack/utils.sh

Based on https://github.com/kubernetes-incubator/cri-containerd/pull/521.
This is just a cleanup.
Previously, we only have a `hack/test-utils.sh`. However, some functions in test-utils.sh are not actually used by test scripts, such as `create_ttl_bucket`, `sha256`, and I'm planning to add more.
This PR create a `hack/utils.sh` for pure util functions, `hack/test-utils.sh` should only be used by test scripts.

Refactor hack utils

---

pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/store/sandbox/sandbox.go

A Possible fix to address scenario mentioned in kubernetes-incubator/cri-containerd#524
Cache the IP allocated for pods not connected to host network and avoid fetch it on every Sandbox status request.

Caching IP allocated by CNI plugin

---

cmd/cri-containerd/options/options.go
pkg/server/service.go

Current uuid handling logic is not perfect. Some known issues have been reported such as https://github.com/kubernetes-incubator/cri-containerd/issues/509, https://github.com/kubernetes-incubator/cri-containerd/issues/399 and https://github.com/kubernetes-incubator/cri-containerd/issues/325.
When this doesn't work, kubelet won't be able to get image filesystem capacity and usage. However, we should not keep user from trying cri-containerd out because of this.
Add a flag to skip this logic, and I'll figure out how we could make this more portable across different environments.

Do not error out if uuid is not found.

---

pkg/server/helpers_selinux_test.go

- use t.Skip() instead of return
- use t.Run() instead of t.Log() for test description

Minor cleanup on selinux test

---

hack/install-deps.sh

containerd `make install` requires `go` to check OS and ARCH. However, `sudo` doesn't inherit envs usually, so `sudo make install` could not find `go` in `PATH`.
Partially unblock https://github.com/containerd/cri-containerd/pull/485.
@dnephin 

Pass PATH for containerd sudo make install.

---

contrib/ansible/README.md
docs/installation.md

This pr is one of a two or more fixes to the docs as a part of the move from kubernetes-incubator to our new github.com/containerd home.
First stage fix for the docs is just to move the links from kubernetes-incubator/cri-containerd to containerd/cri-containerd.
Next stage will be to modify the docs appropriately to address cri-containerd becoming a plugin within containerd, and possibly to move the repo from containerd/cri-containerd to containerd/cri or to containerd/cri-plugin etc.

fix kubernetes-incubator links

---

hack/boilerplate/boilerplate.Dockerfile.txt
hack/boilerplate/boilerplate.Makefile.txt
hack/boilerplate/boilerplate.go.txt
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate.sh.txt
hack/update-proto.sh

Adds the following additional features to boilerplate testing:
1) Now supports the form `Copyright YEAR AUTHORS` where the YEAR is this year and back to 2014, and AUTHORS is one of [ 'The Kubernetes Authors', 'The Containerd Authors', 'The containerd Authors', 'The Authors' ]
2) Now supports multiple copyright lines, though each copyright line has to be of the above form.

enhanced boilerplate checking

---

CONTRIBUTING.md
README.md
code-of-conduct.md

This commit modifies the readme in view of our transition `kubernetes-incubator/` to `containerd`.

update readme after move to containerd

---

.travis.yml
Makefile
cmd/cri-containerd/options/options.go
cri.go
hack/install-deps.sh
hack/test-integration.sh
hack/test-utils.sh
integration/restart_test.go
integration/test_utils.go

This PR:
1) Added `cri.go`, which implements the containerd plugin interface. Containerd can import cri plugin by simply adding:
```go
import _ "github.com/kubernetes-incubator/cri-containerd"
```
2) Added `make install.deps COOK_CONTAINERD=true` mode, which will automatically update vendored CRI plugin in containerd before building it.
3) Added integration test for the plugin mode in travis.
Please note that:
1) Build `cri-containerd` as binary plugin doesn't work at all. I tried it. One problem is that cri-containerd and containerd import many same packages, and init functions in those packages will run twice. Once when containerd starts, another one when the binary plugin is loaded, which is apparently unacceptable. Thus vendor cri-containerd into containerd become the only option.
2) …

Add initial version of plugin mode

---

pkg/annotations/annotations.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

For hypervisor-based container runtimes (like Kata Containers, Clear Containers
or runv) a pod will be created in a VM and then create containers within the VM.
When a runtime is requested for container commands like create and start, both
the instal "pause" container and next containers need to be added to the pod
namespace (same VM).
A runtime does not know if it needs to create/start a VM or if it needs to add a
container to an already running VM pod.
This patch adds a way to provide this information through container annotations.
When starting a container or a sandbox, 2 annotations are added:
- type (Container or Sandbox)
- sandbox name
This allow to a VM based runtime to decide if they need to create a pod VM or
container within the VM pod.
Signed-off-by: Jose Carlos Venegas Munoz …

Annotations: Provide container metadata for VM based runtimes

---

cmd/cri-containerd/cri_containerd.go
cri.go
hack/test-integration.sh
hack/test-utils.sh
integration/restart_test.go
integration/test_utils.go
pkg/atomic/atomic_boolean.go
pkg/atomic/atomic_boolean_test.go
pkg/server/events.go
pkg/server/instrumented_service.go
pkg/server/service.go
pkg/server/version.go

Let CRI plugin use containerd grpc server.
Previously we had a circular dependency problem:
1) cri plugin becomes one of containerd grpc service.
2) cri plugin itself replies on containerd grpc services to do initialization.
This PR split the CRI GRPC service creation and initialization.
During plugin regstration, cri plugin will:
1) Create the grpc service with `Register` method and return to containerd;
2) Start a goroutine to do initialization asynchronously.
3) All GRPC service request handlers need to return error before initialization is finished.
In this way, we can make cri one of containerd grpc services, and make sure CRI only starts serving request when initialization is done.
The only downside is that after containerd starts, CRI might not be available immediately.
However, we …

Use containerd grpc server

---

cmd/cri-containerd/cri_containerd.go
pkg/server/helpers.go
pkg/server/service.go

Based on #552. Only the last commit is new.
Move `SetOOMScore` and `loadCgroup` into `cmd/cri-containerd`.
For plugin mode, containerd will provide those configurations, so we only need to do them in standalone mode.

Move cgroup oom to cmd

---

cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
cri.go
hack/test-integration.sh
integration/restart_test.go
integration/test_utils.go
integration/volume_copy_up_test.go
pkg/server/service.go
pkg/server/service_test.go

Based on https://github.com/containerd/cri-containerd/pull/555.
Use containerd plugin config. With this PR, we can use contianerd config file to config CRI plugin:
```console
$ cat /etc/containerd/config.toml 
[plugins.linux]
shim_debug = true
[plugins.cri]
stream_server_port = "10010"
```

Use containerd config

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
cri.go
pkg/server/service.go
pkg/server/service_test.go
test/e2e_node/init.yaml

This PR:
1) Add `/runtime` cgroup for containerd and cri-containerd in e2e test. So that our resource usage test in https://k8s-testgrid.appspot.com/sig-node-containerd#node-e2e-serial can get full runtime resource usage. @yanxuean @miaoyq 
2) Fix `cri-containerd default-config` panic. I don't understand why it panics, but this PR does fix it by removing a level of embedded struct `CRIConfig`. See https://github.com/BurntSushi/toml/issues/211.

Add runtime cgroup and fix a cli panic.

---

integration/sandbox_clean_remove_test.go
pkg/server/container_list_test.go
pkg/server/container_start.go
pkg/server/container_status.go
pkg/server/container_stop.go
pkg/server/events.go
pkg/server/restart.go
pkg/server/sandbox_list.go
pkg/server/sandbox_list_test.go
pkg/server/sandbox_portforward.go
pkg/server/sandbox_remove.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/server/sandbox_status_test.go
pkg/server/sandbox_stop.go
pkg/server/sandbox_stop_test.go
pkg/store/container/status.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go
pkg/store/sandbox/status.go
pkg/store/sandbox/status_test.go

Related to https://github.com/containerd/containerd/issues/2020.
This PR:
1) Cache sandbox status in sandbox store.
2) Update sandbox status based on containerd event.
3) Recover sandbox cache during restart.
This should reduce the containerd/containerd-shim cpu/memory usage.

Avoid containerd access as much as possible.

---

pkg/server/container_status.go
pkg/server/events.go

goal:
1. improve cri-containerd performance
2. clean log.
There are many useless info in log.
```
I1208 15:49:43.785508   12909 events.go:73] Received container event timestamp - 2017-12-08 07:49:43.784790728 +0000 UTC, namespace - "k8s.io", topic - "/images/create"
I1208 15:49:43.786397   12909 image_pull.go:111] Unpack image "busybox"
I1208 15:49:43.903693   12909 events.go:73] Received container event timestamp - 2017-12-08 07:49:43.903308963 +0000 UTC, namespace - "k8s.io", topic - "/images/update"
I1208 15:49:43.905175   12909 events.go:73] Received container event timestamp - 2017-12-08 07:49:43.90488295 +0000 UTC, namespace - "k8s.io", topic - "/images/create"
I1208 15:49:43.920262   12909 events.go:73] Received container event timestamp - 2017-12-08 07:49:43.919800908 +0000 UTC, …
```

add filter for containerd event

---

cmd/cri-containerd/options/options.go
cmd/cri-containerd/options/registry.go
pkg/containerd/resolver/auth.go
pkg/containerd/resolver/fetcher.go
pkg/containerd/resolver/httpreadseeker.go
pkg/containerd/resolver/resolver.go
pkg/containerd/resolver/scope.go
pkg/containerd/resolver/scope_test.go
pkg/containerd/resolver/status.go
pkg/server/helpers.go
pkg/server/image_pull.go

This commit aims to add registy mirror support similar to docker. The UI is similar to docker where user can provide mirror urls and the image resolves against the provided mirrors before fetching from default docker regitry mirror url. This PR only addresses a small feature set to support registry mirror.
**Note** 
A proposal for full feature-set that involves namespace based configuration for registry will be following this PR shortly. The proposal will aim to provide a more flexible and cleaner approach to use registry mirror. 
Testing:
1) Tested using default mirror (docker.io)
images from docker registry and docker namespace(alpine,redis)
images from non default namespace (quay.io/coreos/etcd,gcr.io/google_containers/alpine-with-bash:1.0)
2) Tested using non default mirror (gcr.io) …

Adding Registry Mirror support

---

pkg/server/status.go

I feel like it's useful to show golang version in `crictl info`.
I feel like for `crictl info`, order is not so important, so don't put everything into one big struct for now.
```console
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true,
"reason": "",
"message": ""
},
{
"type": "NetworkReady",
"status": true,
"reason": "",
"message": ""
}
]
},
"config": {
"containerd": {
"snapshotter": "overlayfs",
"runtime": "io.containerd.runtime.v1.linux"
},
"cni": {
"binDir": "/opt/cni/bin",
"confDir": "/etc/cni/net.d"
},
"registry": {},
"streamServerPort": "10010",
"sandboxImage": "gcr.io/google_containers/pause:3.0",
"statsCollectPeriod": 10,
"containerdRootDir": "/var/lib/containerd",
"containerdEndpoint": "/run/containerd/containerd.sock",
"socketPath": …
```

Add golang version in `Status` info.

---

cluster/gce/configure.sh
cluster/gce/env
test/configure.sh

Cloud-init script will run whenever node reboot. Previously we get version from `https://storage.googleapis.com/cri-containerd-release/latest` in the cloud init script.
However, if the latest version changed before reboot, the node will download a new version of cri-containerd during reboot, which might not be compatible with the Kubernetes version in use.
We should fix the version in instance metadata.

Put version into metadata so that version won't be changed across reboot.

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
test/e2e_node/init.yaml

@abhi has a good point. We should not use docker.io as fallback in the code. We should use configuration to specify that.

Use registry-1.docker.io as backup

---

Makefile
cluster/gce/env
cmd/cri-containerd/cri_containerd.go
cmd/cri-containerd/options/options.go
cmd/ctrcri/ctrcri.go
cmd/ctrcri/load.go
docs/installation.md

Add a separate CLI for cri-containerd called `ctrcri`, basically a `ctr` for CRI plugin. I know the name is bad and confusing, but I could not come up with a better name...
We need a separate CLI. Today we use `cri-containerd load`. However, after switching to plugin mode, we don't have a `cri-containerd` binary. We have to support `load` somewhere, so we added `ctrcri`.
This works with both standalone `cri-containerd` and containerd cri plugin.
The CLI is used for image load for now, which is required for cluster bootstrapping today. We may add new subcommand in the future if we have to.
`ctrcri` isn't targeted to be a user facing tool. User should only use `kubectl` or `crictl` in most cases.
```console
$ ctrcri
__                 _ 
_____/ /________________(_)
/ ___/ __/ ___/ ___/ ___/ …
```

Add a separate CLI for cri-containerd `ctrcri`.

---

hack/install-deps.sh

This PR:
1) Remove `critest` from release tarball. `critest` requires `cri-tools` repo to work. The binary itself is not usable.
2) Add `FASTBUILD=true` for cni plugins build, which accelerate build process a lot.

Remove critest from release tarball.

---

cri.go

Remove wrong comment. CRI is a service registered on containerd grpc server now.

Remove wrong comment. CRI is actually a grpc plugin of containerd now.

---

hack/install-deps.sh
hack/test-e2e-node.sh
hack/update-vendor.sh
hack/utils.sh
hack/versions

This sets `$what_VERSION` and `$what_REPO` for runc, cni, containerd and
kubernetes based on vendor.conf, removing the need to duplicate things in
hack/versions.
With this `update_hack_versions` becomes redundant so remove it and both calls.
Since CONTAINERD_REPO is now unconditionally set we can also simplify the
fetching of vendor.conf in update-vendor.sh a bit, so do so. Further since
`*_REPO` are now unconditionally set we can support alternative clone paths for
all of these repos by adjusting checkout_repo to make the 3rd argument
non-optional and always passing it. Since `CRITOOL_VERSION` is not coming from
`vendor.conf` (since it is not used from Go code) we manually set
`CRITOOL_REPO` for consistency.
The final wrinkle is that `k8s.io/kubernetes` is has a Go specific redirect in …

hack/versions: extract most from vendor.conf

---

hack/install-deps.sh

Although not sure why. After https://github.com/containerd/cri-containerd/commit/78f3df285f209b4e5ae54787ed9ae159bb0e785a got merged, device-plugin-gpu test become very flaky. https://k8s-testgrid.appspot.com/sig-node-containerd#e2e-gci-device-plugin-gpu
I can't find any other suspicious change around that time, so revert this to see whether it fixes it.
/cc @mikebrow 

Do not fast build.

---

hack/boilerplate/boilerplate.py

The group wants to use "The containerd Authors" see https://github.com/containerd/containerd/pull/2108
IMO both containerd and Containerd seek to cover the same group from a copyright perspective.. so for the purpose of boilerplate verification I at least want to make sure we support the all lower case option. If desired I can sed through the files, remove "Containerd" and force "The containerd Authors" but for now I'd rather just support both in boilerplate verify.

adds lower case containerd to the list of authors

---

hack/versions
pkg/ioutil/writer_group.go
pkg/ioutil/writer_group_test.go
pkg/server/container_attach.go
pkg/server/container_log_reopen.go
pkg/server/container_start.go
pkg/server/io/container_io.go
pkg/server/restart.go

Support reopening container log.
The PR for kubelet is coming soon.
The PR for critest is https://github.com/kubernetes-incubator/cri-tools/pull/242. And the critest has passed:
```console
[k8s.io] Container runtime should support log 
runtime should support reopening container log [Conformance]
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:226
[BeforeEach] [k8s.io] Container
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:50
[BeforeEach] [k8s.io] Container
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:63
[BeforeEach] runtime should support log
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:194 …
```

Support reopening container log.

---

cluster/health-monitor.sh
hack/test-utils.sh
integration/test_utils.go

Add `INITIAL_WAIT_SECONDS` for health-monitor. And use `pkill -x` to do exact match. https://gsp.com/cgi-bin/man.cgi?section=1&topic=pkill

Add initial wait for health-monitor and use pkill -x.

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
pkg/server/service.go

In e2e test, I sometimes see that when cri-containerd is starting, it is killed by health-monitor, and then stuck forever:
```
Started Kubernetes containerd CRI shim.
time="2018-02-13T02:26:55Z" level=info msg="Run cri-containerd "
time="2018-02-13T02:26:55Z" level=info msg="Start profiling server"
time="2018-02-13T02:26:55Z" level=info msg="Run cri-containerd grpc server on socket "/var/run/cri-containerd.sock""
time="2018-02-13T02:26:55Z" level=info msg="Get image filesystem path "/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs""
I0213 02:26:55.155330    2490 interface.go:360] Looking for default routes with IPv4 addresses
I0213 02:26:55.155351    2490 interface.go:365] Default route transits interface "eth0"
I0213 02:26:55.155458    2490 interface.go:174] Interface eth0 is …
```

Do not block on stream server close.

---

pkg/store/container/container.go
pkg/store/sandbox/sandbox.go
pkg/store/util.go

When doing restart test for containerd/cri-containerd, I saw this panic:
```
time="2018-02-22T01:29:30Z" level=info msg="TaskExit event &TaskExit{ContainerID:5572b0aff62a960b5e2082f9cbcdceb2b40c6148c4c0277cbe47f29300eac02c,ID:5572b0aff62a960b5e2082f9cbcdceb2b40c6148c4c0277cbe47f29300eac02c,Pid:23240,ExitStatus:137,ExitedAt:2018-02-22 01:29:30.09547447 +0000 UTC,}"  
panic: close of closed channel
goroutine 675 [running]:
github.com/containerd/cri-containerd/pkg/store.store.StopCh.Stop(...)
/home/lantaol/workspace/src/github.com/containerd/cri-containerd/pkg/store/util.go:24
github.com/containerd/cri-containerd/pkg/server.handleContainerExit(0xc420340480, 0xc4202a4480, 0x40, 0xc42041a000, 0xb9, 0xc4202a44c0, 0x40, 0xc4201920d0, 0xc4203a6050, 0x47, ...) …
```

Fix a potential panic

---

hack/utils.sh

Update cri-tools to include https://github.com/kubernetes-incubator/cri-tools/pull/257 and https://github.com/kubernetes-incubator/cri-tools/pull/250.

Update critools to b184f9aefe60a4441330e615ee20634ee26474fb.

---

README.md

Update support matrix to clarify that HEAD only supports 1.10+ now.

Update support matrix.

---

.travis.yml

Moves travis tests from 1.9 and tip to 1.9 and 1.10 to sync with containerd's travis testing.

adds go 1.10 to ci test

---

.travis.yml
README.md

addressing issue #626
From here on in we can start using 1.10 only golang features and thus will only test on 1.10 and up.

moving to go1.10 only

---

cri.go

Fixes https://github.com/containerd/containerd/issues/2174.
Export CRI version for CRI plugin, so that we can see the cri version in `ctr plugins -d`:
```console
...
Type:          io.containerd.grpc.v1
ID:            cri
Requires:     
io.containerd.runtime.v1
io.containerd.snapshotter.v1
io.containerd.monitor.v1
io.containerd.differ.v1
io.containerd.metadata.v1
io.containerd.content.v1
io.containerd.gc.v1
Platforms:     linux/amd64
Exports:      
CRIVersion      v1alpha2
```

Expose cri version for CRI plugin.

---

hack/test-utils.sh

After check if containerd is intalled the command executed using sudo,
/usr/local/bin may not been in the root's PATH, save the path where
containerd was found and use it.
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

tests: Use path found to containerd.

---

.travis.yml
Makefile

If no tag is "found" we should at least fall back to the commit vs setting the version to nil. 
Maybe the root issue is the depth of the git clone, it's set to 50. Setting the clone depth to 150 and leaving the version change in for people that want a shallow clone or don't fetch tags.

adds allways to ensure there is a version even if no tag

---

cmd/cri-containerd/options/options.go

Fixes https://github.com/containerd/cri-containerd/issues.
Only overwrite `c.ContainerdRootDir` and `c.ContainerdEndpoint` when legacy options are set.
/cc @miaoyq 

Only overwrite when legacy options are specified.

---

docs/crictl.md

Address issue #638 by showing detailed steps for creating and loading images.

documents load image

---

pkg/server/events.go

We should not continue when there is an error. It may cause a panic.
Found this when reviewing https://github.com/containerd/cri-containerd/pull/628.
Ref https://github.com/containerd/cri-containerd/issues/642.

Fix a potential panic.

---

contrib/ansible/README.md

`include_tasks` is added in ansible 2.4. I tried with ansible 2.3.2, and it reports error on `include_tasks`.
http://docs.ansible.com/ansible/2.4/include_tasks_module.html
```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
The error appears to have been in '/home/lantaol/workspace/src/github.com/containerd/cri-containerd/contrib/ansible/cri-containerd.yaml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- include_vars: vars/vars.yaml # Contains tasks variables for installer
- include_tasks: tasks/bootstrap_ubuntu.yaml # Contains tasks bootstrap components for ubuntu systems
^ here
The error appears to have been in …
```

Require ansible 2.4+.

---

pkg/containerd/resolver/resolver.go

Fixes https://github.com/containerd/cri-containerd/issues/649.
Ref https://github.com/containerd/cri-containerd/issues/642.
GCR sometimes returns http 401 since this noon, which caused many test failures, e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-cri-containerd-e2e-gci-gce/2908. 
I've filed an internal issue to them. Before that is fixed let's port the fix https://github.com/containerd/containerd/pull/2171 here, which we need anyway.
@abhi 

Handles 401 in resolver.

---

cri.go
integration/test_utils.go
pkg/constants/constants.go
pkg/server/container_create.go
pkg/server/events.go
pkg/server/instrumented_service.go
pkg/server/sandbox_portforward.go
pkg/server/service.go
pkg/server/snapshots.go
pkg/server/streaming.go
vendor/github.com/containerd/containerd/client.go
vendor/github.com/containerd/containerd/grpc_services.go
vendor/github.com/containerd/containerd/lease.go
vendor/github.com/containerd/containerd/local_services.go

@crosbymichael @mikebrow Let's start from this PR. Once we are ok with this PR, we can port services one by one without interfering each other.
This PR:
1) Added a `Services` interface in `Client.go`. And added grpcServices implementation and also a directServices implementation. Suggestions for naming are welcome.
2) Added `k8s.io` namespace for all contexts in cri plugin. We can also deal with default namespace in containerd client, but without grpc it requires too many changes. It might be easier to let caller handle namespace if direct services are used.
3) Change CRI plugin to use internal content store.
Please note that **the internal content store doesn't publish events**. Should we fix it? Or we are ok with it?
/cc @containerd/containerd-maintainers

[in-process-integration] Start switching to direct function call

---

pkg/server/version.go

Given that we are going to merge cri-containerd with containerd soon, it makes sense to report containerd version instead.

Report containerd version instead of cri-containerd version.

---

cli/cli.go

For https://github.com/containerd/cri-containerd/issues/590.
Add `cli` package for `ctr` to use.
This simplifies the command description a lot to make it similar with `ctr`, e.g. [`remove`](https://github.com/containerd/containerd/blob/master/cmd/ctr/commands/images/images.go#L286).
@mikebrow Are you ok with that? Or do you have any suggestion?

Add CLI package for `ctr` to use.

---

pkg/os/os.go
pkg/server/events.go
pkg/server/events_test.go
pkg/server/helpers.go

Handle containerd event reliably

---

hack/install-deps.sh

We need promisc mode to handle the case that one pod talks to its own service.

Enable promisc mode because Kubernetes network model needs it.

---

test/build-containerd.sh
test/configure.sh
test/e2e_node/image-config-containerd.yaml

We should not use the same latest file for `containerd` and `cri-containerd` together.
Push containerd test tarball to a different bucket `cri-containerd-staging/containerd`.

Fix containerd repo test.

---

test/containerd/build.sh
test/containerd/deploy-path
test/containerd/image-config.yaml
test/containerd/pkg-prefix
test/e2e_node/image-config-containerd.yaml

Kubernetes test-infra only supports load instance metadata from files. This PR write both `pkg-prefix` and `deploy-path` into files to work around this.
The test-infra side change is https://github.com/kubernetes/test-infra/pull/7328.

Write all instance metadata to files.

---

test/containerd/build.sh

Deploy bucket is set via `DEPLOY_BUCKET`, and the default `cri-containerd-staging` is just what we want. https://github.com/containerd/cri/blob/master/hack/push.sh#L24
We should only set `DEPLOY_DIR`.

Only set deploy dir.

---

Makefile
cluster/gce/configure.sh
cluster/gce/env
docs/crictl.md
docs/kube-up.md
hack/release.sh

This PR:
1) Fix the `configure.sh` for `kube-up.sh`.
2) Write a `version` file into the release tarball, and use fixed version for `kube-up.sh`. We shouldn't let user specify arbitrary version of `cri-containerd` to use, because that may not be compatible with the cluster bootstrap scripts and cloud init files.
3) Update some documents.

Fix for kube-up.sh and update several documments.

---

hack/install/install-critools.sh
hack/install/install-deps.sh
hack/test-cri.sh
hack/utils.sh

Build `critest` into release tarball again, because we've got rid of the dependency on the source code. https://github.com/kubernetes-incubator/cri-tools/pull/261
Now `critest` binary is usable itself.

Update cri-tools and build critest into release tarball again.

---

hack/test-utils.sh
pkg/annotations/annotations.go
pkg/config/config.go
pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

This PR adds:
- Trusted runtime configuration option.
- Allow to change contaienrd configuration for testing.
Some CRI compatible runtimes may not support privileged operations.
Specifically hypervisor based runtimes (like kata-containers, cc-runtime
and runv) do not support privileged operations like:
- Provide access to the host namespaces
- Create fully privileged containers with access to host devices
Hypervisor based runtimes create container workloads within virtual machines.
When a running host privileged containers using them,
they wont provide support to requested the privileged opertations.
This commits add the new options to define two runtimes:
Trusted runtime : Used when a privileged container is requested.
Default runtime : for non-privileged workloads.
A container that …

[WIP]config: Allow to define trusted runtime

---

pkg/config/config.go

Remove `omitempty` from config json.
We should show empty config option in `crictl info`:
```console
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true,
"reason": "",
"message": ""
},
{
"type": "NetworkReady",
"status": true,
"reason": "",
"message": ""
}
]
},
"config": {
"containerd": {
"snapshotter": "overlayfs",
"defaultRuntime": {
"runtimeType": "io.containerd.runtime.v1.linux",
"runtimeEngine": "",
"runtimeRoot": ""
},
"privilegedRuntime": {
"runtimeType": "io.containerd.runtime.v1.linux",
"runtimeEngine": "",
"runtimeRoot": ""
}
},
"cni": {
"binDir": "/opt/cni/bin",
"confDir": "/etc/cni/net.d"
},
"registry": {
"mirrors": {
"docker.io": {
"endpoint": [
"https://registry-1.docker.io"
]
}
}
},
"streamServerAddress": "",
"streamServerPort": "10010",
"enableSelinux": …
```

Remove omitempty from config json.

---

hack/utils.sh
pkg/server/streaming.go

Addresses issue #665
Adds a tls config comprising a newly generated x509 certificate from a newly generated public/private key pair.

adds tls certificate to tls config

---

hack/test-utils.sh
pkg/annotations/annotations.go
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_status.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go
pkg/server/sandbox_status.go

Address some comments from https://github.com/containerd/cri/pull/657.
Changes need input:
1) I changed `privilegedSandbox` to `hostPrivilegedSandbox`. The reason is that `privileged` already has special meaning today, and `trusted` is still a bit confusing to me. I feel that `hostPrivileged` is more accurate, but a bit long.
2) I changed `containerRuntime` and `getRuntime` to `ociRuntime` and `getOCIRuntime` to make it more clear.
3) I changed sandbox to use privileged runtime if `annotations.HostPrivilegedSandbox` is "true". This behavior is not included in the original PR, I'm not sure whether it is a mistake.
@jcvenegas Thanks a lot for contributing this! :)
/cc @mikebrow @jcvenegas 

Address comments for privileged runtime code.

---

pkg/server/events.go

Fix the event monitor panic.
We should only stop ticker when it is not nil.
Since `start` and `stop` can be called at the same time, we need a lock to protect it.

Fix event monitor panic.

---

docs/installation.md

Resolves this warning:
"/run/containerd/containerd.sock" as endpoint is deprecated please
consider using full url format "unix:///run/containerd/containerd.sock".

fully specify --container-runtime-endpoint flag

---

pkg/server/sandbox_portforward.go

Fix a log output.

---

pkg/server/container_create.go
pkg/server/sandbox_run.go
vendor.conf
vendor/github.com/containerd/containerd/archive/tar_windows.go
vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
vendor/github.com/containerd/containerd/image.go
vendor/github.com/containerd/containerd/linux/shim/client/client.go
vendor/github.com/containerd/containerd/oci/spec_opts_unix.go
vendor/github.com/containerd/containerd/sys/socket_unix.go
vendor/github.com/containerd/containerd/vendor.conf

Based on https://github.com/containerd/containerd/pull/2257.
`RunAsGroup` is added in Kubernetes 1.10 https://github.com/kubernetes/kubernetes/pull/52077. We should support it.
Please hold this PR until I add CRI validation test. https://github.com/kubernetes-incubator/cri-tools/issues/280

Add RunAsGroup support.

---

.travis.yml
README.md
contrib/ansible/tasks/bootstrap_ubuntu.yaml
docs/installation.md
hack/install/install-deps.sh
test/build-utils.sh

As of opencontainers/runc@db093f6 runc no longer depends on libapparmor
thus libapparmor-dev no longer needs to be installed to build it or
anythind that depends on it (like containerd or cri-containerd). Adjust
the documentation accordingly.
containerd/containerd#2238 did the same for containerd.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Drop libapparmor dependency from build docs

---

pkg/config/config.go
pkg/server/streaming.go

Addresses issue  #712 by disabling TLS support by default. Some clients do not support insecure TLS.

adds a new flag to enable TLS support (insecure for now)

---

pkg/server/streaming.go

switches from not CA signed to self CA signed for streaming TLS

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
contrib/ansible/cri-containerd.yaml
docs/config.md
test/e2e_node/init.yaml

Enable it in all the setup. We don't enable it by default, because we don't know whether it works for other setup. But we are confident that it works for all our supported setup.
We can switch the default in the future.

Enable TLS streaming in all the setup.

---

.travis.yml
README.md
contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/bootstrap_ubuntu.yaml
pkg/server/sandbox_portforward.go
pkg/store/sandbox/netns.go

This commit removes the usage of nsenter and uses netns
to perform socat operation.
Fixes https://github.com/containerd/cri/issues/144

Getting rid of nsenter and socat

---

pkg/containerd/importer/importer.go

Fixes https://github.com/containerd/cri/issues/638.
This PR added support for symlink layers. @AkihiroSuda Does this make sense to you?
Now `ctr cri load` works for `k8s.gcr.io/pause-amd64:3.0`:
```console
$ sudo ctr cri load test/test.tar 
Loaded image: k8s.gcr.io/pause-amd64:3.0
```
/cc @hmtai @qiujian16

Support symlink layer in image import.

---

.travis.yml
README.md
contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/bootstrap_ubuntu.yaml
pkg/server/sandbox_portforward.go

`io.Copy` doesn't work for us. The main problem is that:
1) When one side (either pod side or user side) of portforward is closed, we should stop port forwarding.
2) When one side is closed, the `io.Copy` use that side as source will close, but the `io.Copy` use that side as dest won't. (`io.Copy` doesn't stop when dest is closed until there is new input from source)
3) However, we can't simply forcibly stop the hanging `io.Copy` by closing the source. Because TCP is bi-direction, even though one direction is closed (we know because one `io.Copy` stops), the other direction may not, and that `io.Copy` might be working. There is no way for us to know it now.
There should be some solution for this problem, and socat must have implemented that. We need more time to investigate it.
So let's …

Add socat back.

---

docs/release.md

Document the current release process.
It is not ideal, but it is still better to note it down than doing it differently each time.

Add release instruction to make the release process written down.

---

.travis.yml

It's time to start tracking point release updates for golang See: https://github.com/containerd/containerd/commit/37765fbde5b297b81bba2d1306f9abc84e8f775d

start tracking golang updates for 1.10.x

---

hack/utils.sh
pkg/server/sandbox_portforward.go

Fixes https://github.com/containerd/cri/issues/738.
Corresponding CRI validation test https://github.com/kubernetes-incubator/cri-tools/pull/289.
Test result:
```
[BeforeEach] [k8s.io] Streaming
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:50
[BeforeEach] [k8s.io] Streaming
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:52
[It] runtime should support portforward in host network
/home/lantaol/workspace/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/streaming.go:148
STEP: create a PodSandbox with container port port mapping in host network
STEP: create a nginx container
Apr 17 07:32:26.804: INFO: Use latest as default image tag.
STEP: Get image status for image: …
```

Fix portforward for host network.

---

pkg/server/sandbox_stop.go

`sandbox_stop.go` should only kill the sandbox container, and event monitor will handle `TaskExit` event and `Delete` the task.
Errors caused by this race condition:
```
time="2018-04-18T00:53:09Z" level=error msg="Failed to handle event &TaskExit{ContainerID:e162c2c3f61deeebc88a9f12219fc574eb2b3a47a5bd9d0e1a79f2fc643a37c4,ID:e162c2c3f61deeebc88a9f12219fc574eb2b3a47a5bd9d0e1a79f2fc643a37c4,Pid:21642,ExitStatus:137,ExitedAt:2018-04-18 00:53:09.292640191 +0000 UTC,} for container e162c2c3f61deeebc88a9f12219fc574eb2b3a47a5bd9d0e1a79f2fc643a37c4" error="failed to handle sandbox TaskExit event: failed to stop sandbox: container must be created: failed precondition"
```

Fix sandbox stop race condition.

---

README.md
cluster/gce/env
contrib/ansible/cri-containerd.yaml
docs/crictl.md
hack/install/install-critools.sh
hack/test-utils.sh
hack/utils.sh
integration/test_utils.go

Kubelet and `crictl` prefers socket address with `unix://` prefix, or else it prints out warning. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/util_unix.go#L75
For example:
```
W0420 17:20:40.130286  237131 util_unix.go:75] Using "/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/containerd/containerd.sock".
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT
```
This PR adds `unix://` prefix to all containerd socket addresses except the ones passed to containerd client, because containerd client doesn't work with the `unix://` prefix.

Add `unix://` prefix for socket addresses used by CRI remote client.

---

docs/release.md
hack/install/install-deps.sh
hack/release.sh

Fixes #737.
I've uploaded 1.1.0 release tarballs, and updated the release note https://github.com/containerd/containerd/releases/tag/v1.1.0. Containerd binaries in the release tarball are downloaded from containerd github release.

Download containerd binaries from official release.

---

hack/release.sh

@mikebrow @dmcgowan Fix the tarball permission and containerd binary path problem.
I've uploaded newest release tarballs.

Fix tarball ownership and containerd binary path for containerd.

---

hack/utils.sh

See: https://github.com/kubernetes-incubator/cri-tools/pull/293
Update cri-tools to fix `crictl logs` output issue.

Update cri-tools to fix `crictl logs` output.

---

pkg/os/os.go
pkg/os/testing/fake_os.go
pkg/server/sandbox_run.go
pkg/store/sandbox/netns.go

Currently, Unmount() call takes a burden to parse the whole nine yards of /proc/self/mountinfo to figure out whether the given mount point is mounted or not (and returns an error in case parsing fails somehow).
Instead, let's just call umount() and ignore EINVAL, which results in the same behavior, but much better performance.
Note that EINVAL is returned from umount(2) not only in the case when target is not mounted, but also for invalid flags. To avoid ignoring a valid error, the check for valid flags is added.
Note that MNT_EXPIRE is not allowed as it requires a special handling.
While at it, remove the 'containerdmount' alias from the package.

os.Unmount: do not consult mountinfo

---

pkg/server/container_stats_list.go
pkg/server/container_stats_list_test.go

Fix container workingset memory calculation.
In kubernetes and cadvisor, workingset is defined as "usage - total_inactive_file".
See https://github.com/google/cadvisor/blob/08f0c2397cbca790a4db0f1212cb592cc88f6e26/container/libcontainer/handler.go#L520.
/cc @dashpole @abhi 

Fix workingset memory calculation.

---

vendor.conf
vendor/github.com/containerd/containerd/client.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/events/events.go
vendor/github.com/containerd/containerd/cmd/ctr/commands/tasks/list.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go

Update containerd to newest commit in `release/1.0` to prepare for 1.0.1 release.

Update containerd to 01a0741488487779a95035cd85504589034d2e91.

---

README.md

Quick fix to moving tagged logo images in the readme.

use public logos for a while vs remote github logos not in this repo

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
cluster/gce/configure.sh
cluster/health-monitor.sh

Depends on https://github.com/kubernetes/kubernetes/pull/63357.
kube-up.sh will install crictl on GCE. We don't need to install it our own.

Use crictl installed in kube-up.sh

---

pkg/server/image_pull.go

Remove the useless error check during creating reference in containerd.
ping @Random-Liu

Remove useless error-check in createImageReference

---

test/containerd/build.sh

Make `DEPLOY_PATH` configurable.
This is useful for branch test. See https://github.com/kubernetes/test-infra/pull/8158

Make DEPLOY_PATH configurable.

---

pkg/containerd/resolver/fetcher.go
pkg/containerd/resolver/fetcher_test.go

Port docker resolver fix https://github.com/containerd/containerd/pull/2364.
We should really get rid of the fork. https://github.com/containerd/cri/issues/723
/cc @abhi @dmcgowan 

Port docker resolver fix #2364.

---

pkg/server/events.go
pkg/server/service.go

Fixes https://github.com/containerd/containerd/issues/2371.
This PR:
1) Let event monitor and streaming server return an error channel.
2) Let CRI plugin `Run` return error if an error is received from the error channels of event monitor or streaming server.
3) Ignore `http.ErrServerClosed` which is a normal error generated when http server is Shutdown/Closed.
@t3hmrman @crosbymichael 

Generate fatal error when cri plugin fail to start.

---

cluster/gce/configure.sh
contrib/ansible/cri-containerd.yaml

Disable TLS streaming to work with new kubelet streaming proxy added in https://github.com/kubernetes/kubernetes/pull/64006.

Disable TLS streaming to work with new kubelet streaming proxy.

---

cli/cli.go
integration/test_utils.go
pkg/client/client.go

Fix `ctr cri` timeout.
See https://github.com/containerd/cri/pull/799#issuecomment-394518385
@AkihiroSuda @mikebrow 

FIx ctr cri timeout.

---

pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Fixes https://github.com/containerd/cri/issues/783.
Select ipv4 address if there is one.
The expected behavior is not clearly defined in Kubernetes, but this is the implementation for all existing kubernetes network plugins. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/plugins.go#L251

Select ipv4 first if there is one.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

This is not a huge problem to `containerd/cri`, because our default ambient list is empty. https://github.com/containerd/containerd/blob/master/oci/spec_unix.go#L97
However, we add ambient cap if user explicitly adds it. This is not a CVE, but a behavior change to me. We decided to follow docker's behavior for backward compatibility. And we can carry on discussion about how to better handle this in https://github.com/kubernetes/kubernetes/issues/56374.

Erase ambient capabilities.

---

pkg/server/events.go

Log task exit event which is useful for debugging issues like https://github.com/containerd/containerd/issues/2392.

Log task exit event.

---

pkg/server/sandbox_portforward.go

This reverts commit dd886bc281c764c3a40f1c5e1eadca3337f847e4.

Revert "Use pod ip instead of localhost in pod netns for portforward."

---

integration/images/volume-ownership/Dockerfile
integration/images/volume-ownership/Makefile
integration/volume_copy_up_test.go
pkg/containerd/opts/container.go

Fixes https://github.com/containerd/cri/issues/809.
We should still copy file ownership even if the source volume directory is empty.
@ibuildthecloud

Fix empty volume ownership.

---

pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

I tried to use `nginx` as sandbox container image, but failed because of this.
This is not super important, so no need to cherrypick.

Support `Cmd` for sandbox container.

---

pkg/server/container_create.go
pkg/server/sandbox_run.go

We have double `/dev/shm` mount now, one from containerd default runtime spec, one from our own `/dev/shm` mount.
```
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```
This PR fixes it:
```
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
```

Fix double /dev/shm mount.

---

docs/config.md
integration/container_log_test.go
integration/container_update_resources_test.go
integration/test_utils.go
pkg/config/config.go
pkg/ioutil/write_closer.go
pkg/ioutil/write_closer_test.go
pkg/server/container_log_reopen.go
pkg/server/container_start.go
pkg/server/io/logger.go
pkg/server/io/logger_test.go
pkg/server/restart.go

Fixes https://github.com/containerd/cri/issues/283.
This PR added a configuration `max_container_log_size` for configuring max container log line size. Log line longer than the size limit will be split into multiple lines.
@yujuhong

Add log max size

---

cluster/gce/configure.sh

Fixes https://github.com/containerd/cri/issues/819.

Make max container log line size configurable through cloud init.

---

pkg/server/service.go

The specified snapshotter can be `nil`. When that happens, it is better to log a clear fatal error than panic for nil pointer access.
/cc @dmcgowan 

Fix snapshotter nil panic.

---

pkg/server/service.go
pkg/server/status.go
pkg/server/testing/fake_cni_plugin.go
pkg/server/update_runtime_config.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/cni.go
vendor/github.com/containerd/go-cni/opts.go

This commit contains change to pick the latest cni config from the configured CNIConfDir.
With this change any changes made to the cni config file will be picked up on the kubelet's runtime status check call.
Ofcourse this would lead to undefined behavior when the cni config change is made in parallel during pod creation. However its reasonable to assume that the operator is aware of the need to drain the nodes of pods before making cni configuration change. The behavior is currently not defined in kubernetes. However I see that similar approach being adopted in the upstream kubernetes with dockershim. Keeping the behavior consistent for now.
Signed-off-by: Abhinandan Prativadi abhi@docker.com

Change to keep in sync with latest cni config

---

cluster/gce/configure.sh

Fixes https://github.com/containerd/cri/issues/777.
Let stream server serve on localhost on GCE to work with newly introduced kubelet proxy streaming. https://github.com/kubernetes/kubernetes/pull/64006

Set stream server to serve on localhost on GCE.

---

cluster/gce/configure.sh

Fixes https://github.com/containerd/cri/issues/759.
On second thought, I don't think we need to build another GCE tarball. We'll just use the standard containerd release tarball.

Remove crictl on GCE for all cases.

---

docs/config.md
hack/verify-lint.sh
integration/container_log_test.go
integration/container_update_resources_test.go
integration/test_utils.go
pkg/config/config.go
pkg/ioutil/write_closer.go
pkg/ioutil/write_closer_test.go
pkg/server/container_log_reopen.go
pkg/server/container_start.go
pkg/server/io/logger.go
pkg/server/io/logger_test.go
pkg/server/restart.go

#761 is not a CRI api change. And the config change is also backward compatible.
It is very useful for production environment, so we decide to backport it to release/1.0 branch.
/cc @yujuhong

Backport #761 to release/1.0

---

docs/installation.md
hack/release.sh

Fixes https://github.com/containerd/cri/issues/842.
Without this flag, `tar` will overwrite metadata of existing directories including `/usr`, `/etc` and `/opt`.
Another problem is that in our release tarball those directories have `750` permission, but the permissions inside the tarball shouldn't be applied to existing directories during installation anyway.
We should cherrypick this to the document in old branches.

Use `--no-overwrite-dir` in installation doc.

---

docs/config.md
pkg/config/config.go
pkg/server/container_start.go
pkg/server/sandbox_run.go

For minikube #462, If not, we will fail to create sandbox.
```
FATA[0003] run pod sandbox failed: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:107: jailing process inside rootfs caused \\\"pivot_root invalid argument\\\"\"": unknown
```
refer to https://github.com/containerd/containerd/issues/1973

support no_pivot option for runc

---

pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

VM isolated runtimes can support privileged workloads. In this
scenario, access to the guest VM is provided instead of the host.
Based on this, allow untrusted runtimes to run privileged workloads.
If the workload is specifically asking for node PID/IPC/network, etc.,
then continue to require the trusted runtime.
This commit repurposes the hostPrivilegedSandbox utility function to
only check for node namespace checking.
Fixes: #855
Signed-off-by: Eric Ernst <eric.ernst@intel.com>

sandbox: separate host accessing workload and privileged

---

hack/verify-lint.sh
pkg/containerd/importer/importer.go
pkg/server/image_load.go

We should unpack image during import, so that the lease can help us hold the resource.
Similar issue with https://github.com/containerd/containerd/pull/2331.

Unpack image during import.

---

cluster/gce/configure.sh

We should cherrypick this to 1.11, because netd support is added in Kubernetes 1.11. https://github.com/kubernetes/kubernetes/pull/64591

Support netd in GCE bootstrap.

---

docs/config.md
pkg/config/config.go
pkg/server/streaming.go
pkg/server/streaming_test.go

This PR allows to configure containerd certificates used to stream.
This is needed if we want to use a safe `https` setup for `kubectl exec`.
```text
time="2018-08-27T18:30:06.366428577+02:00" level=info msg="Exec for "23db729b6d704da42d366ead46278dae498594ea4043ded7bb9af401bc589c50" with command [/bin/sh], tty true and stdin true"
time="2018-08-27T18:30:06.366497645+02:00" level=info msg="Exec for "23db729b6d704da42d366ead46278dae498594ea4043ded7bb9af401bc589c50" returns URL "https://192.168.128.173:10010/exec/_dPWQE1j""
```

stream: can use user certificates

---

pkg/server/container_create.go

To match expectations of users coming from Docker engine runtime, add
the HOSTNAME to the environment of new containers in a pod.
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Add HOSTNAME to env by default for pod containers

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go

Fixes https://github.com/containerd/containerd/issues/2596.
We should cherry-pick this fix into all supported branches.
This PR:
1) Makes sure volume mounts are sorted based by depth, so that parent directory mount won't override the sub directory mount. (Corresponding docker code: https://github.com/moby/moby/blob/a9bd60d674f85c2161bb702404b23501d6b746c3/daemon/volumes_unix.go#L97)
2) Skip default mount or cri plugin controlled mount if the destination is mounted by CRI already.
3) Skip all default `/dev` mounts if `/dev` is mounted in CRI. (Corresponding docker code: https://github.com/moby/moby/blob/a9bd60d674f85c2161bb702404b23501d6b746c3/daemon/oci_linux.go#L555)

Sort volume mount.

---

pkg/server/container_status.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/store/sandbox/metadata.go

Fixes https://github.com/containerd/cri/issues/915.
Added `runtimeHandler` in sandbox debug info. Not sure whether we should add it to container debug info, given that runtime handler is a sandbox level configuration. Only add to sandbox debug info for now.

Show runtime handler in sandbox debug info.

---

hack/test-e2e-node.sh

Many dev environments run with swap on, so we don't fail by default.

Turn off `--fail-swap-on` in node e2e test.

---

hack/test-utils.sh

`sudo` usually has a different `PATH`, explicitly use `which` to find those binaries.
This makes test start up much faster on my desktop, because my `sudo` `PATH` doesn't include `ctr` and `crictl`.

Fix readiness check in test utils.

---

integration/containerd_image_test.go
integration/restart_test.go
integration/test_utils.go
pkg/server/events.go
pkg/server/helpers.go
pkg/server/image_load.go
pkg/server/image_pull.go
pkg/server/restart.go
pkg/server/service.go

For https://github.com/containerd/cri/issues/909.
For https://github.com/containerd/containerd/issues/2678.
This PR:
1) Add `io.cri-containerd.image` label for `cri` plugin managed images.
2) For images pulled/imported by other clients, e.g. `ctr`, the `cri` plugin will generate the image id as the unique reference, and apply the `io.cri-containerd.image` label. This prevents the image from losing all references unexpectedly.
3) Add 2 integration tests: "image can be recovered during restart" and "image pulled with containerd client can be seen by CRI plugin".
/cc @dmcgowan

Better external image handling

---

Makefile

fixes syntax issue with "make help" command 
before:  
```
* 'install.tools'    	- Install tools used by verify
/bin/sh: 1: Syntax error: ")" unexpected
Makefile:41: recipe for target 'help' failed
make: *** [help] Error 2
```
after:
```
* 'install.tools'    	- Install tools used by verify
* 'install.deps'     	- Install dependencies of cri (Note: BUILDTAGS defaults to 'seccomp apparmor' for runc build)
* 'uninstall'        	- Remove installed binaries from system locations
* 'version'          	- Print current cri plugin release version
* 'update-vendor'    	- Syncs containerd/vendor.conf -> vendor.conf and sorts vendor.conf
```

corrects syntax error in Makefile

---

integration/image_load_test.go

Replace Skip with Skipf in the intergration test.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

test: Fix compile error with go1.10.2

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_start.go
pkg/server/container_status.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_status.go

Fixes https://github.com/containerd/containerd/issues/2701.
Support per-runtime configuration in the `cri` config file. The newly introduced `Options` field can be any type. Currently, only supported types are [`options.Options`](https://github.com/containerd/containerd/blob/master/runtime/v2/runc/options/oci.pb.go#L39) for shim v2, and [`runctypes.RuncOptions`](https://github.com/containerd/containerd/blob/master/runtime/linux/runctypes/runc.pb.go#L40). `runctypes.RuncOptions` is the fallback for unknown runtime types.
Change [`getRuntimeType`](https://github.com/containerd/cri/pull/943/files#diff-f41a864ccb9e17c8853f725df14b8e3eR479) to support new option types.
Here is an example config which uses runc with shim v1 as the default runtime, runc with shim v2 as the `runc` runtime, and …

Support runtime specific configurations.

---

integration/restart_test.go
integration/sandbox_clean_remove_test.go
integration/test_utils.go
pkg/server/container_status.go
pkg/server/sandbox_status.go
pkg/server/sandbox_stop.go
pkg/store/sandbox/netns.go
vendor.conf
vendor/github.com/containerd/go-cni/cni.go

Fixes #948.
Based on https://github.com/containerd/go-cni/pull/31.
We should cherrypick this PR into all supported branches.

Fix ip leakage

---

pkg/server/sandbox_run.go

Signed-off-by: Starnop <starnop@163.com>
Now, we setup network before get sandbox runtime, it will happen if the untrusted workload is requesting access to the host/node, request will fail, and we have to rollback after the defer clean  up. It' not make sence, so I adjusted the order of them.

refactor: setup network after get Sandbox runtime

---

integration/restart_test.go
integration/sandbox_clean_remove_test.go
integration/test_utils.go
pkg/server/container_status.go
pkg/server/sandbox_status.go
pkg/server/sandbox_stop.go
pkg/server/service.go
pkg/server/status.go
pkg/server/testing/fake_cni_plugin.go
pkg/server/update_runtime_config.go
pkg/store/sandbox/netns.go
vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/cni.go
vendor/github.com/containerd/go-cni/opts.go

I need to double check the `go-cni` update to make sure it doesn't introduce unexpected behavior into release/1.0.

Cherrypick #949 release 1.0

---

Makefile

Do this because:
1) The containerd binary built from this repo is only used for testing.
2) Since 1.2, we are not going to create new tags in this repo. If we don't do this, all future versions will be `v1.11.0-xxxx`.

Use commit as version.

---

pkg/server/instrumented_service.go

removes authconfig from info log

---

pkg/server/instrumented_service.go

cherry-pick #961 for 1.0 removes authconfig from info log

---

Makefile

Cherrypick this, so that the test binary version is correctly set in 1.2 branch.

Cherrypick #959 release 1.2

---

README.md

Include containerd 1.2 in the support metrics.

Update support metrics to include containerd 1.2.

---

pkg/server/events.go

Remove the TODO, because this has already been handled by containerd.
See https://github.com/containerd/containerd/blob/c95bb88fa3b6e6a37cdad6aad630203c80e4063f/runtime/v1/linux/runtime.go#L190 and https://github.com/containerd/containerd/blob/c95bb88fa3b6e6a37cdad6aad630203c80e4063f/runtime/v1/linux/runtime.go#L324.

Remove invalid TODO comment.

---

.travis.yml
integration/container_update_resources_test.go

Never really liked the stages feature, switching back to clean and simple one run per go version implementation.
Setting 1.11.x to an allowed failure, temporarily, due to 
```
=== RUN   TestUpdateContainerResources
E1023 22:34:56.902537   21909 remote_runtime.go:213] StartContainer "70638def43d25a54024ccbb85b262beee83af18de47bb39fa6ddce1988749020" from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:336: starting container process caused "process_linux.go:402: container init caused \"process_linux.go:367: setting cgroup config for procHooks process caused \\\"failed to write 4194304 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/k8s.io/70638def43d25a54024ccbb85b262beee83af18de47bb39fa6ddce198874 …
```

adds golang 1.11.x to build

---

pkg/server/sandbox_run.go
pkg/server/sandbox_status.go
pkg/store/sandbox/metadata.go

Address issue #979 while we can ask them to re-run with debug logging turned on, it should be very useful to have the ability to inspect each pod's cni load results from users (clients) of containerd/cri. 

adds cni results to verbose pod info

---

pkg/server/events.go

Resolve issue https://github.com/firecracker-microvm/firecracker-containerd/issues/35

filter events for non k8s.io namespaces

---

pkg/server/events.go

This PR:
- Cherrypick #984 into release/1.0 branch;
- Resolves issue firecracker-microvm/firecracker-containerd#35

Cherrypick #984 release 1.0

---

pkg/server/container_create_test.go

fix spelling error: contaner -> container in [container_create_test.go](https://github.com/containerd/cri/compare/master...JoeWrightss:patch-1?expand=1#diff-a1753cc8f8d4a50ed78a098ba4efd957) at line 596.

fix spelling error: contaner -> container

---

integration/container_without_image_ref_test.go
pkg/server/container_create.go
pkg/server/container_status.go
pkg/server/container_stop.go
pkg/store/container/container_test.go
pkg/store/container/metadata.go

Fixes https://github.com/containerd/cri/issues/990.
Test result without the fix:
```
--- FAIL: TestContainerLifecycleWithoutImageRef (1.66s)
container_without_image_ref_test.go:29: Create a sandbox
container_without_image_ref_test.go:42: Pull test image
container_without_image_ref_test.go:49: Create test container
container_without_image_ref_test.go:59: Remove test image
container_without_image_ref_test.go:62: Container status should be running
Error Trace:    container_without_image_ref_test.go:64
Error:		Received unexpected error rpc error: code = Unknown desc = failed to get image "sha256:59788edf1f3e78cd0ebe6ce1446e9d10788225db3dedcfd1a59f764bad2b2690": does not exist
```
Test result with the fix:
```
=== RUN   TestContainerLifecycleWithoutImageRef
--- PASS: …
```

Remove container lifecycle image dependency

---

pkg/server/image_pull.go

Fix some typos:
1. "cann't" to "can't" at line 64.
2. "occurrs" to "occurs" at line 68.

Fix some typo errors

---

hack/test-cri.sh

To temporarily work around a golang regression. See https://github.com/golang/go/issues/29241.

Temporary fix for golang regression #29241.

---

test/build-utils.sh

In Kubernetes test infra, we have both debian:jessie and debian:stretch test images.
We need to support both until the switch is completed.
/cc @bentheelder

Install libseccomp2 based on debian version

---

pkg/server/restart.go
pkg/server/sandbox_stop.go

Fix some spelling errors:
1. "Event montior" to "Event monitor" in line 149.
2. "intialized" to "initialized" in line 131.

Fix return error message

---

pkg/server/sandbox_stop.go

Fixes https://github.com/containerd/containerd/issues/2546.
I thought about this a bit.
I don't think reversing the order will cause any problem. Previously, I was worried that we remove the sandbox when the sandbox container is not running but network is not tore-down yet. So we teardown the network first then stop the sandbox container.
However, now we also checks network namespace before sandbox removal, it should be fine to reverse the order https://github.com/containerd/cri/blob/master/pkg/server/sandbox_remove.go#L57

Teardown sandbox network after stop.

---

pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1015.
Till now, the issue only happens to `docker.io/library/golang`. It seems that some platform of `docker.io/library/golang` is not pullable.
However, we shouldn't be pulling image for all platforms in the cri plugin anyway.
This is handled in containerd client in release/1.2.
However, we missed it in release/1.0.
Before the fix:
```
(stuck...)
```
After the fix:
```
Image is up to date for sha256:ef89ef5c42a90ec98bda7bbef0495c1ca6f43a31d059148c368b71858de463d2
```

[release/1.0] Specify platform for image pull.

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/service.go

Add following config for supporting "rootless" mode
* DisableCgroup: disable cgroup
* DisableApparmor: disable Apparmor
* RestrictOOMScoreAdj: restrict the lower bound of OOMScoreAdj
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
---
A quick way to test this PR is to use Usernetes v20181109.0 ( https://github.com/rootless-containers/usernetes )
```console
$ ./run.sh default-containerd
$ ./kubectl.sh run -it --rm --image alpine foo
```
cc @giuseppe for consistency with CRI-O implementation (https://github.com/kubernetes-sigs/cri-o/blob/2accad9fab352c445bb4c414d9d3c8cdf351c524/server/rootless.go could be simplified as in this PR with the latest runc IIUC)

support DisableCgroup, DisableApparmor, RestrictOOMScoreAdj

---

pkg/server/container_create_test.go
pkg/server/helpers_test.go
pkg/server/sandbox_run_test.go

OCI spec generation is the core logic, would like as much coverage as possible.

Add unit test for DisableCgroup, RestrictOOMScoreAdj.

---

integration/container_stop_test.go
integration/test_utils.go

Ref https://github.com/containerd/cri/issues/1018.
Without the fix https://github.com/containerd/containerd/pull/2854 the test timeout, because stop hangs.
With the fix, the test passes.

Add test for shared pid multi-process container stop.

---

integration/container_log_test.go
pkg/server/events.go
pkg/server/io/logger.go
pkg/server/io/logger_test.go
pkg/util/strings.go

Fixes https://github.com/containerd/cri/issues/1026.
Basically we need our own `ReadLine` to return errors instead of hiding it.
We should cherry-pick this change to release/1.0 and release/1.2.

Fix the log ending newline handling.

---

pkg/server/streaming.go
pkg/store/snapshot/snapshot.go

1. "cetificate" to "certificate" in line 179.
2. "commited" to "committed" in line 31.

Fix some typos in comment

---

hack/test-cri.sh
hack/test-integration.sh

Add `RUNTIME` env in the integration and cri test.
This can be used to test different runtimes.

Add RUNTIME env in integration and cri test.

---

vendor.conf
vendor/github.com/containerd/containerd/cmd/ctr/commands/run/run_windows.go
vendor/github.com/containerd/containerd/images/archive/reference.go
vendor/github.com/containerd/containerd/metadata/buckets.go
vendor/github.com/containerd/containerd/oci/spec.go
vendor/github.com/containerd/containerd/oci/spec_opts_windows.go
vendor/github.com/containerd/containerd/vendor.conf

This removes the last use of `util.NormalizeImageRef`
Let me know if you want to have this utility removed, or to keep it for backward compatibility (not sure if this repository is vendored elsewhere, and the utility used by other projects)

Update containerd to 4543e32a8b29e691e523ddc142f0c9068917df54

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/instrumented_service.go
pkg/server/sandbox_run.go

Fixes https://github.com/containerd/cri/issues/1044.
This PR:
1) Remove config info log. It will be too spammy when the config is large, e.g. a lot of envs.
2) Add a map to cache envs in the spec generator.
We may eventually upstream the cache change, but I think we should make local change to avoid delaying release.
With the fix:
```console
$ time crictl create 9 container.json sandbox.json 
5c5bbe3d624bbdfb7030a9909e6f139c38c253ea436da2e8432d9ab02a2da213
real	0m0.298s
user	0m0.083s
sys	0m0.030s
```
Without the fix:
```console
$ time crictl create 9 container.json sandbox.json 
65ade40d8c4b77d6227c0fe36e11c5f3ec4b6cab4a8d76d4135bf4e273ca8544
real	0m41.998s
user	0m0.095s
sys	0m0.009s
```
Test env number:
```console
$ crictl exec 6 sh -c "env | wc -l"
26017
```

Fix env performance issue

---

integration/runtime_handler_test.go
pkg/server/sandbox_list.go
pkg/server/sandbox_list_test.go
pkg/server/sandbox_status.go
pkg/server/sandbox_status_test.go

Add RuntimeHandler into PodSandbox and PodSandboxStatus
The upstream CRI change: https://github.com/kubernetes/kubernetes/pull/73833
Signed-off-by: Haiyan Meng <haiyanmeng@google.com>

Add RuntimeHandler into PodSandbox and PodSandboxStatus

---

pkg/server/container_create.go

This is to work with https://github.com/kubernetes/kubernetes/pull/74441.
Usually the sandbox config passed in by `RunPodSandbox` and `CreateContainer` should be the same. However, it may not be the case when there is a version skew (sandbox is created before upgrade, container is created after upgrade).
Use the `sandboxConfig` passed in `CreateContainer` to keep the same behavior with dockershim.

Use the correct sandbox config.

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go

Fixes https://github.com/containerd/cri/issues/1059.
Use `filepath.Clean` for map deduplication and path comparison.
I've searched with `git grep -i`: `==.*path`, `path.*==`, `\[.*path.*\]`, `==.*source`, `source.*==`, `\[.*source.*\]`, `==.*src`, `src.*==`, `\[.*src.*\]`, `==.*dst`, `dst.*==`,  `\[.*dst.*\]`,`==.*dest`, `dest.*==`, `\[.*dest.*\]`. And added `filepath.Clean` for all appearance.
We should cherry-pick this fix into all supported branches.

Use clean path for map and comparison.

---

pkg/annotations/annotations.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Add an OCI annotation to pass down the pod log directory.
This is useful for sandbox runtime which has pod level logs, e.g. gvisor. Actually I chatted with @resouer about this, and he told me that kata used to have pod level logs as well.
Especially after https://github.com/kubernetes/kubernetes/pull/74441 lands, Kubelet will be responsible for monitoring the disk usage and cleanup these logs.
@mikebrow Are you ok with cherrypicking this to release/1.2? It doesn't break anyone. :)

Add an OCI annotation for sandbox log directory.

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
test/e2e_node/init.yaml

Docker 18.09 depends on a containerd service. For testing our own containerd we need to replace that containerd service.
Kubernetes has been updated to test on COS m73, which has Docker 18.09 built-in https://github.com/kubernetes/kubernetes/pull/75149. That is why all tests are failing: https://k8s-testgrid.appspot.com/sig-node-containerd

Support docker 18.09 in the test script.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Fixes https://github.com/containerd/cri/issues/1082.
If people do in-place upgrade, old sandboxes may not have the `hostname` file. In that case, we shouldn't try to mount it into containers.
Another option is to create the hostname file for the old sandbox if it doesn't have it. However, that also causes inconsistency, e.g. inside the same pod, old running containers don't have the hostname file, new restarted containers have it.
Neither of them is a perfect solution, skipping mounting is cleaner and keeps consistency inside the same pod, so I implemented that one.

Fix /etc/hostname backward compatibility issue for in-place upgrade.

---

cluster/gce/configure.sh

This is a prerequisite to testing a non-default runtime handler in the Kubernetes containerd E2E tests.

Expose environment variables for configuring an additional runtime handler

---

cluster/gce/configure.sh

I get the following error now:
```
/home/containerd/configure.sh: line 184: CONTAINERD_EXTRA_RUNTIME_HANDLER: unbound variable
```
/cc @tallclair 

Set default "" to extra runtime handler.

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Changed PR from add filtering to testing the filtering...
Add test case to confirm we are processing masks correctly when privileged. see https://github.com/kubernetes/kubernetes/issues/75238
Based on the code in dockershim... we should not be masking/adding read only paths for privileged containers (even if requested). Shrug. 
Added note: Since we already do mask, simply adding a test case and comments to verify and explain to future readers.

Add test for filtering container create masks when privileged

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

OCI annotations can be used to set the sandbox related parameters. In the case of VM based runtimes, such as kata, this can be used to dynamically select the `vmdisk` or `initrd` that can be custom built for that container image.
e.g. With ppc64le ultravisors' upcoming capability to run secure VM which need to be encrypted with the public key of target system, user can specifically intruct the runtime, like kata, to use a specific initrd on the system for the given container image. 
Kata already supports setting those values via OCI annotations, it's just that until now CRI wasn't setting it. The corresponding k8s pod.yaml looks something like this,
```yaml
apiVersion: v1
kind: Pod
metadata:
name: foobar-kat3
"annotations": {
"com.github.containers.virtcontainers.InitrdPath" : …
```

Add support for passing sandbox annotations to runtime

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run_test.go

This is a follow up of #1084.
This PR:
1) Cleanup passthrough pod annotation test;
2) Change back to only support wildcard, reason https://github.com/containerd/cri/pull/1084#discussion_r268091851.
/cc @harche I think your original solution is better, because:
1) Regular expression is not convenient for domain name matching, especially for matching `.`.
2) A generic wildcard support requires dynamic planning, which makes the code complicated.
Let's just do tailing wildcard support.

Cleanup pod annotation test and only support wildcard

---

vendor.conf

For https://github.com/containerd/cri/issues/1107.

Update CNI to v0.7.5.

---

integration/pod_hostname_test.go
pkg/containerd/opts/spec.go
pkg/containerd/opts/spec_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

This PR:
1) Remove UTS namespace for hostnetwork. This is to keep the behavior consistent with dockershim https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/security_context.go#L204.
2) Stop assuming arrays don't contain duplicated elements.
1 is important, and we should cherry-pick to supported branches.
2 is not that critical.

Uts namespace and fix array

---

cluster/gce/configure.sh

@tallclair 
The runtime class test is failing right now, because:
```
configure.sh[975]: + source /home/containerd/containerd-env
configure.sh[975]: ++ readonly CONTAINERD_EXTRA_RUNTIME_HANDLER=test-handler
configure.sh[975]: ++ CONTAINERD_EXTRA_RUNTIME_HANDLER=test-handler
...
configure.sh[975]: + CONTAINERD_EXTRA_RUNTIME_HANDLER=test-handler
configure.sh[975]: /home/containerd/configure.sh: line 185: CONTAINERD_EXTRA_RUNTIME_HANDLER: readonly variable
```

Use local env to avoid writing to passed-in readonly env.

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go

full diff: https://github.com/opencontainers/selinux/compare/v1.2...v1.2.1
brings in opencontainers/selinux#49 Ignore attempts to setLabels "" on SELinux disabled systems
relates to https://github.com/opencontainers/runc/issues/2030

bump opencontainers/selinux v1.2.1

---

cluster/gce/configure.sh
pkg/server/helpers.go
pkg/server/helpers_test.go

For https://github.com/containerd/cri/issues/1075.
/cc @crosbymichael @yujuhong 
Use per-pod shim in the node e2e and cluster e2e test.
We should consider switching the default runtime in `pkg/config/config.go`, once the test result looks good.

Enable runc.v2 as the default runtime in test.

---

pkg/server/helpers.go
vendor.conf
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

backports of https://github.com/containerd/cri/pull/1101 and https://github.com/containerd/cri/pull/1113 for the 1.2 branch

[release/1.2 backport] bump selinux v1.2.1

---

pkg/server/helpers.go
vendor.conf
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

backports of https://github.com/containerd/cri/pull/1101 and https://github.com/containerd/cri/pull/1113 for the 1.0 branch

[release/1.0 backport] bump selinux v1.2.1

---

hack/utils.sh

The containerd build is broken, because we added a vendor comment for runc in https://github.com/containerd/containerd/pull/3184 and https://github.com/containerd/containerd/pull/3183.
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-build-1.1
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-build-1.2
This should not happen.

Support comment in vendor.

---

.travis.yml

1.11.7 doesn't work on travis right now:
```
/home/travis/.gimme/versions/go1.11.7.linux.amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-869411160/000016.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
```
See:
* https://travis-ci.org/containerd/cri/jobs/517237868
* https://travis-ci.org/containerd/cri/builds/516837021
* https://travis-ci.org/containerd/cri/builds/516560894

Use golang 1.11.6 for now.

---

cluster/gce/configure.sh

Use runc.v1 to see whether https://github.com/containerd/containerd/issues/3177 is still reproducible.
This can help us figure out whether the issue is caused by the 5 seconds timeout introduced in the v2 shim, or architecture change from per-container shim to per-pod shim.

Use runc.v1 for now for debugging.

---

pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/container_stop.go
pkg/server/events.go
pkg/server/events_test.go
pkg/server/helpers.go
pkg/server/restart.go
pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
pkg/store/container/container_test.go
pkg/store/container/status.go
pkg/store/container/status_test.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go
pkg/store/sandbox/status.go
pkg/store/sandbox/status_test.go

Fixes https://github.com/containerd/cri/issues/1132.
This PR:
1) Uses `Wait` instead of `TaskExit` event. This should fix issues like https://github.com/containerd/containerd/issues/3177 and https://github.com/containerd/containerd/issues/3125;
2) Removes big sandbox and container start lock, because with `Wait` we can control the timing of exit event generation to avoid race condition. This is very important, because sandbox/container start lock is the last potential long running lock we have today. And in GKE, we do see slow container start holds container lock and blocks `docker ps` for Docker.
**Please note that for containers/sandboxes in unknown state, we still need to rely on containerd `TaskExit` event, because they were not successfully loaded, there are no corresponding exit …

Use wait instead of `TaskExit`.

---

cluster/gce/configure.sh
cri.go
docs/config.md
pkg/config/config.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Fixes https://github.com/containerd/cri/issues/1076.
This PR:
1) Add support for `DefaultRuntimeName`. And map `DefaultRuntime` to `DefaultRuntimeName=default` for legacy config support.
2) Change `DefaultRuntimeName` to `runc`, and start using `io.containerd.runc.v1` as the default runtime. (We may consider switching to v2 once https://github.com/containerd/cri/issues/1075 is fixed).
3) Add warning log for deprecated fields `DefaultRuntime` and `UntrustedWorkloadRuntime`.
4) Add deprecation policy for CRI config options.
/cc @tallclair Please take a look at the runtime config related change.

Add default runtime name

---

pkg/server/container_remove.go
pkg/server/container_start.go
pkg/server/container_start_test.go
pkg/server/container_stop.go
pkg/server/events.go
pkg/server/events_test.go
pkg/server/helpers.go
pkg/server/restart.go
pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
pkg/store/container/container_test.go
pkg/store/container/status.go
pkg/store/container/status_test.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go
pkg/store/sandbox/status.go
pkg/store/sandbox/status_test.go

Cherrypick #1133 release 1.2
This is not a small change, but it is an important bug fix. Since we are going to support containerd 1.2 for a long time, we should at least fix this in 1.2.
For #1132, https://github.com/containerd/containerd/issues/3125, https://github.com/containerd/containerd/issues/3177

Cherrypick #1133 release 1.2

---

cluster/gce/configure.sh
vendor/github.com/gogo/googleapis/go.mod
vendor/github.com/gogo/protobuf/go.mod
vendor/github.com/sirupsen/logrus/go.mod
vendor/golang.org/x/sys/go.mod
vendor/gopkg.in/yaml.v2/go.mod

For https://github.com/containerd/cri/issues/1075
https://github.com/containerd/containerd/issues/3177 has been fixed. Test looks good till now.
Time to switch back to per-pod shim.

Use per-pod shim.

---

integration/sandbox_clean_remove_test.go

task.Delete() will try to kill the task before delete it,
but once the task is killed, the TaskExit event will also
tigger another task.Delete() which would conflict with this
test task.Delete(). To avoid this conflict, kill the task instead
of Delete it, and let TaskExit trigger task.Delete().
Signed-off-by: lifupan <lifupan@gmail.com>

Integration test task.Delete fix

---

pkg/server/container_execsync.go
pkg/server/container_stop.go
pkg/server/sandbox_stop.go

To support cross compilation for SIG* signals perfer the syscall package over
the unix package.

Move from unix to syscall package for SIG* signals

---

pkg/server/container_create.go

Override container log path to empty if either of sandbox log directory or container log path is empty.
If either of the log paths is empty, container won't start properly since the log path is not properly specified.
Signed-off-by: Cong Liu <conliu@google.com>

Override container log path to empty if either of sandbox log directory or container log path is empty.

---

pkg/server/sandbox_run.go

Minor correctness. We should use the value of the const in the error message
instead of hard coding it in the string so if maxDNSSearches ever changes so
does the error.

Update parseDNSOptions maxDNSSearches in error message

---

pkg/server/container_execsync.go

When context is cancelled, the `process.Kill` won't work. We need to kill the process in the cleanup defer.

Make sure exec process is killed when context is canceled.

---

pkg/server/sandbox_run.go
vendor.conf
vendor/github.com/containerd/go-cni/namespace_opts.go
vendor/github.com/containerd/go-cni/opts.go
vendor/github.com/containerd/go-cni/types.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/doc.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/fake_shaper.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/interfaces.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/linux.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/unsupported.go
vendor/k8s.io/kubernetes/pkg/util/bandwidth/utils.go

This PR add support for traffic shaping which was implemented by Kubernetes. This allows to limit the network ingress/egress off a pod. More details are in the linked PR.
Fixes: https://github.com/containerd/cri/issues/1150
This PR depends on: https://github.com/containerd/go-cni/pull/40

Initial support for traffic shaping

---

pkg/server/status.go
pkg/store/sandbox/metadata.go

Addressing  #979 and comments from first attempt #982
Adds the CNI plugin path and config source information used to create the cni plugin results.
see cniconfig below:
```
sudo crictl info
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true,
"reason": "",
"message": ""
},
{
"type": "NetworkReady",
"status": true,
"reason": "",
"message": ""
}
]
},
"cniconfig": {
"PluginDirs": [
"/opt/cni/bin"
],
"PluginConfDir": "/etc/cni/net.d",
"Prefix": "eth",
"Networks": [
{
"Config": {
"Name": "cni-loopback",
"CNIVersion": "0.3.1",
"Plugins": [
{
"Network": {
"type": "loopback",
"ipam": {},
"dns": {}
},
"Source": "{\"type\":\"loopback\"}"
}
],
"Source": "{\n\"cniVersion\": \"0.3.1\",\n\"name\": \"cni-loopback\",\n\"plugins\": [{\n  \"type\": \"loopback\"\n}]\n}"
},
"IFName": "lo" …
```

adds cni config data to the cri status/info

---

pkg/server/image_pull.go

Fixes https://github.com/containerd/cri/issues/1161.
Add the cri managed image label when pulling the image.
Previously, we didn't add the image label when pulling the image, so the generated image create event also doesn't have the label:
```
time="2019-06-10T19:46:17.251529854Z" level=info msg="ImageCreate event &ImageCreate{Name:gcr.io/cri-tools/test-image-digest@sha256:9179135b4b4cc5a8721e09379244807553c318d92fa3111a65133241551ca343,Labels:map[string]string{},}" 
```
The cri plugin will [create/update the image reference to add the label](https://github.com/containerd/cri/blob/master/pkg/server/image_pull.go#L206), and this may happen after `PullImage` returns.
If `RemoveImage` is called right after `PullImage`, there will be a race condition before `RemoveImage` and the event …

Add cri managed image label when pulling the image.

---

README.md

use dynamic slack link

---

hack/install/install-critools.sh
hack/install/install-runc.sh

Runc and critools are both versioned with containerd version, e.g. 1.2.6, without the fix.

Fix runc and critools version in release.

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - Multiple syscall arguments were incorrectly combined with logical-OR, instead of …

bump libseccomp-golang v0.9.1

---

docs/registry.md

Correcting typo

---

hack/install/install-critools.sh
hack/install/install-runc.sh

Noticed that this one was labeled for backporting but no backport yet;
cherry-pick of https://github.com/containerd/cri/pull/1180 for the 1.2 branch
(cherry picked from commit 6afd137c026ee2133dddb22bc9a8d405852df674)

[release/1.2 backport] Fix runc and critools version in release.

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of https://github.com/containerd/cri/pull/1189 for the 1.0 branch
full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - …

[release/1.0 backport] bump libseccomp-golang v0.9.1

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of https://github.com/containerd/cri/pull/1189 for the 1.2 branch
full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - …

[release/1.2 backport] bump libseccomp-golang v0.9.1

---

.travis.yml

address #1175 move up to golang 1.12.x in build 1.11 not necessary now

move up to golang 1.12.x

---

vendor.conf
vendor/github.com/containerd/containerd/cmd/containerd/command/config.go
vendor/github.com/containerd/containerd/cmd/containerd/command/config_linux.go
vendor/github.com/containerd/containerd/cmd/containerd/command/config_unsupported.go
vendor/github.com/containerd/containerd/cmd/containerd/command/config_windows.go
vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
vendor/github.com/containerd/containerd/remotes/docker/resolver.go

Update containerd to include the backward compatibility fix. https://github.com/containerd/containerd/pull/3337
Or else this may break people's current local developing environment. :)

Update containerd for config backward compatibility.

---

cluster/gce/cni.template

Fixes https://github.com/containerd/cri/issues/1139.
Remove unused config `noSnat`.
See https://github.com/GoogleCloudPlatform/netd/pull/63.

Remove `noSnat`

---

hack/test-utils.sh

The ctr readiness check should also use the test containerd socket path.

Fix ctr readiness check in test.

---

docs/config.md
pkg/config/config.go
pkg/server/service.go

If enabled, register CRI on containerd's TCP endpoint
#1181

Add option to register on TCP server

---

pkg/server/container_execsync.go
pkg/server/container_stop.go
pkg/server/container_stop_test.go
pkg/server/sandbox_stop.go
pkg/server/sandbox_stop_test.go

In order for a calling client to properly detect when a call failed due to a
timeout CRI should be returning codes.DeadlineExceeded from gRPC by contract.

Return gRPC codes.DeadlineExceeded for all timeout operations

---

pkg/server/container_stop.go

Just a small cleanup. :) Move `sigTermCtxCancel` into defer.
If `waitContainerStop` returns error, sigTermCtx should have already `Done`;
If `waitContainerStop` returns nil, sigTermCtxCancel will be called in defer immediately.

Move context cancel into defer.

---

docs/config.md
pkg/config/config.go
pkg/server/image_pull.go

Add `max_concurrent_downloads`, and set default to `3` (the same with Docker, see https://docs.docker.com/engine/reference/commandline/dockerd/).

Add max concurrent downloads support.

---

pkg/server/container_create.go
pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/store/image/image.go

Cherrypick #1202 to release/1.2
For https://github.com/containerd/containerd/issues/3401.

Cherrypick #1202 release/1.2

---

pkg/server/sandbox_run.go

Return actual error when fetching the bandwidth info from annotation fails.

Return actual error when fetching the bandwidth info from annotation fails

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go

For https://github.com/containerd/cri/issues/1208.
Note that a `disable_proc_mount` option has to be introduced to support Kubernetes 1.11.
Given that 1) containerd 1.1 will go into security patch only mode soon; 2) 1.3 is still WIP; 3) many production Kubernetes clusters are still on 1.11; I think not supporting 1.11 is not an option.
@choury 

Fix proc mount support.

---

hack/test-integration.sh
hack/test-utils.sh
integration/test_utils.go

Rename test containerd binary to containerd-test, so that we can easily restart it in the integration test.
With this change, now we can run containerd integration and CRI test without breaking Docker 18.09+ on the node.

Rename the test binary to containerd-test.

---

cri.go
docs/config.md
pkg/config/config.go

Do not deprecate `no_pivot` yet.
There is no alternative option for `io.containerd.runtime.v1.linux` runtime right now.

Do not deprecate no_pivot yet.

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/helpers.go
pkg/server/helpers_test.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

This is from https://github.com/containerd/cri/pull/1070.
Daemon level `SystemdCgroup` option is deprecated. We don't need it actually, because we can infer that from the path format.

Infer systemd cgroup

---

pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/sandbox_run.go

By default the SecurityContext for Container activation can contain a Username
UID, GID. The order of precedences is username, UID, GID. If none of these
options are specified as a last resort attempt to set the ImageSpec username.

Assign ImageSpec User if SecurityContext is not set

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_create_test.go

This commit adds a flag to the runtime config that allows overloading of the default
privileged behaviour. When the flag is enabled on a runtime, host devices won't
be appended to the runtime spec if the container is run as privileged.
By default the flag is false to maintain the current behaviour of privileged.
Fixes #1213
Signed-off-by: Alex Price <aprice@atlassian.com>

Add flag to overload default privileged host device behaviour

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

We support `path` in mirror endpoint now. We should also consider that when checking default host.

Consider endpoint path when checking default host.

---

docs/registry.md
pkg/server/image_pull.go

Previously, client keypair had needed to be specified even when unused.
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

allow non-mutual TLS

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Fixes https://github.com/containerd/cri/issues/1239.
@mikebrow Do you remember why we didn't clear apparmor when privileged = true before?
I don't remember we intentionally did that.

Fix apparmor for privileged.

---

cmd/containerd/containerd.go

I'm surprised that we didn't explicitly import runtime v2 before.
Luckily it happened to be indirectly imported:
```console
$ git grep "\"github.com/containerd/containerd/runtime/v2\""
vendor/github.com/containerd/containerd/services/tasks/local.go:        v2 "github.com/containerd/containerd/runtime/v2"
```
Let's explicitly import it.

Explicitly import runtime v2 in the test containerd binary.

---

pkg/server/helpers.go
pkg/server/sandbox_run.go
pkg/server/sandbox_stop.go
vendor.conf
vendor/github.com/containerd/go-cni/namespace_opts.go
vendor/github.com/containerd/go-cni/types.go

Fixes https://github.com/containerd/cri/issues/1243.
Depends on https://github.com/containerd/go-cni/pull/48.
This is required for Windows container support as well. (See https://github.com/kubernetes/kubernetes/pull/67435)
/cc @yujuhong 

Support CNI DNS capabilities.

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

- empty username means caller wants to use no credentials, typically for anonymous registry
- Fixes https://github.com/containerd/cri/issues/1249

fix: support empty auth config for anonymous registry

---

cluster/gce/cloud-init/master.yaml
cluster/gce/cloud-init/node.yaml
contrib/systemd-units/containerd.service
test/e2e_node/init.yaml

This PR:
1) added `TaskMax=infinity`, which we should have done long time ago;
2) ~~Removed `contrib/systemd-units`, because we already have https://github.com/containerd/containerd/blob/master/containerd.service~~ I found that `make release` still uses it, so keep it for now.

Add TaskMax=infinity in the systemd unit.

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

cherry-pick f41675d234bb8212457ea04eae5d47dc3606bf6b from master
PR: https://github.com/containerd/cri/pull/1250

[release/1.3] fix: support empty auth config for anonymous registry

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

cherry-pick f41675d234bb8212457ea04eae5d47dc3606bf6b from master
PR: https://github.com/containerd/cri/pull/1250

[release/1.2] fix: support empty auth config for anonymous registry

---

docs/registry.md
pkg/config/config.go

`FDQN` is a typo.
And actually we are not supporting `FQDN` which requires a trailing dot.

FDQN is a typo, and we don't support trailing dot in FQDN.

---

hack/utils.sh

Update cri-tools to include the image reference test fix. https://github.com/kubernetes-sigs/cri-tools/pull/503
I've hit the test failure in travis for several times.

Update cri-tools to fix all image reference test failure.

---

Makefile
README.md

Instructions point to golang 1.10.. which is a bit long in the tooth now. Time to ask them to use 1.12.9 see #1268

need to move instr to more recent golang; remove integration/*.go from lint verify test

---

.golangci.yml
Makefile
pkg/containerd/opts/spec_unix.go
pkg/containerd/opts/spec_windows.go
pkg/netns/netns_windows.go

Add 2m deadline; similar to containerd, recent issues with golangci-lint
taking more than 1 minute. This has been seen in recent containerd/cri PRs as well (recent [example](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/containerd_cri/1280/pull-cri-containerd-verify/1174669796445261825/)).
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Move golangci-lint configuration out of Makefile

---

pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go

Fixes: #1279 
Due to [changes to the defaults in containerd](https://github.com/containerd/containerd/pull/3551), the CRI path to creating a
container OCI config needs to add back in the default UNIX $PATH (and
any other defaults) as that is the expected behavior from other
runtimes.
This is a miss from our fix released in 1.2.9 after breaking in 1.2.8 with the standard path in containerd via the API and `ctr` client (reported in [containerd issue #3597](https://github.com/containerd/containerd/issues/3597) and fixed in [containerd PR #3599](https://github.com/containerd/containerd/pull/3599))
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Add back default UNIX env to container config

---

pkg/server/container_create.go
pkg/server/container_create_test.go

Backport test from #1280; harcoded `defaultUnixEnv` from containerd/containerd brought into the spec generator sequence, as there is no clear way to fix the bug using the `oci.With..` helper in this design.
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

[release/1.2] Backport fix for default UNIX environment in OCI container config

---

pkg/server/container_create_windows.go

For https://github.com/containerd/cri/issues/1257
1. For Windows the Hostname property is not inherited from the sandbox and must
be passed for the Workload container activations as well.

Forward SandboxConfig.Hostname to Workload container activation

---

docs/kube-up.md

Now we just need a simple `KUBE_CONTAINER_RUNTIME=containerd` environment variable before kube-up.sh.

Document simpler kube-up.sh

---

pkg/containerd/opts/spec.go
pkg/containerd/opts/spec_unix.go
pkg/containerd/opts/spec_windows.go
pkg/server/sandbox_run_windows.go
pkg/server/sandbox_run_windows_test.go

For https://github.com/containerd/cri/issues/1257
This PR sets the same default sandbox container cpu shares on windows.
For more details about this, see https://github.com/containerd/cri/issues/1297
@yujuhong @jterry75 

Set default sandbox container cpu shares on windows.

---

hack/utils.sh
pkg/server/container_create_windows_test.go

Update critools to include the hostname test https://github.com/kubernetes-sigs/cri-tools/pull/542
And add hostname unit test for windows.
Ref https://github.com/containerd/cri/pull/1294

Add hostname CRI validation and unit test.

---

pkg/server/container_execsync.go

Cherrypick https://github.com/containerd/cri/pull/1156 into release/1.0
I think this is the only pre-August thing we need to backport from the commits https://github.com/containerd/cri/commits/release/1.2

[release/1.0] Make sure exec process is killed when context is canceled.

---

hack/test-cri.sh
hack/utils.sh

Let's update cri-tools to the newest release, which includes many useful bug fixes and features.

[release/1.3] Update cri-tools to v1.16.1.

---

test/windows/runner.sh

Sometimes it recovers in a second retry: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1177420340528156672.
However, sometimes it doesn't even recover after 1 min: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-cri-validation-windows/1177404990424092672
Let's extend the timeout to be the same with ssh ready. If it still doesn't work, we need to look into this further.
/cc @yujuhong 

[WCOW] Extend permission denied retry to 3min.

---

.appveyor.yml
.golangci.yml
.travis.yml
Makefile
integration/main_test.go

Fixes https://github.com/containerd/cri/issues/1311.
This PR:
1) Fixes appveyor test. Command without `.exe` stopped working somehow.
2) Fixes golangci-lint version (same with containerd/containerd). We hit a lot of unexpected verification timeout failures.
3) Updates `.travis.yml` based on new default ubuntu distro `xenial`. https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
4) Updates integration test to work with golang 1.13 https://github.com/golang/go/issues/31859#issuecomment-532415187
2 and 3 should be cherry-picked.

Explicitly specify trusty in travis.

---

.travis.yml
Makefile

Cherrypick #1312 to release/1.3

[release/1.3] configure golangci-lint and update based on default xenial distro.

---

test/build-utils.sh

The test image was updated recently, and the `btrfs-tools` version was updated to `4.20.1-2` which doesn't contain `btrfs/ioctl.h` any more.
Here is the error message without this fix:
```
W1017 18:52:29.516] vendor/github.com/containerd/btrfs/btrfs.go:38:10: fatal error: btrfs/ioctl.h: No such file or directory
W1017 18:52:29.516]  #include <btrfs/ioctl.h>
W1017 18:52:29.516]           ^~~~~~~~~~~~~~~
W1017 18:52:29.517] compilation terminated.
```

Fix containerd build, use `libbtrfs-dev` when available.

---

test/build-utils.sh

Cherrypick #1319 to release/1.2

[release/1.2] Fix containerd build, use `libbtrfs-dev` when available.

---

test/build-utils.sh

Cherrypick #1319 to release/1.3

[release/1.3] Fix containerd build, use `libbtrfs-dev` when available.

---

.travis.yml
test/build-utils.sh

Cherrypick #1319 to release/1.0.
Cherrypick #1312 to release/1.0.
We won't add new bug fix or feature into release/1.0, but this change is needed to fix the build. https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-build-1.1

[release/1.0] Fix containerd build, use `libbtrfs-dev` when available.

---

contrib/ansible/vars/vars.yaml

Closes #1317 
Old version of containerd causes kubectl exec error like described in #856

Containerd version updated for kubernetes ansible example.

---

test/windows/runner.sh

This is a trial to fix the windows test.
See https://github.com/kubernetes/test-infra/issues/14938 for more details.
/cc @BenTheElder

Avoid O_NONBLOCK on stdout in the windows test.

---

README.md

Update support metrics to reflect that:
1) containerd 1.1 is end of life;
2) Kubernetes 1.13 is end of life.

Update support metrics.

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

Fixes https://github.com/containerd/cri/issues/1327.
This changes the behavior to be consistent with Docker. We should make sure we mention this in the release note.
/cc @liyimeng 

Use `http` for localhost and 127.0.0.1 by default.

---

pkg/server/image_pull.go

It appears that PR #1328 for issue #1327 needs to be re-arranged a little to work, since c.registryEndpoints is pre-pending https the default scheme should be inserted there.

Fix using `http` for localhost, 127.0.0.1 and ::1 by default

---

pkg/containerd/opts/spec_windows.go
pkg/server/container_create_windows_test.go

For https://github.com/containerd/cri/issues/1257.
This is the correct fix for https://github.com/containerd/cri/pull/1335.
Fixes https://github.com/kubernetes/kubernetes/issues/85142

[WCOW] Clean mount path for windows

---

Makefile
hack/install/utils.sh
hack/install/windows/install-cni-config.sh
hack/install/windows/install-cni.sh
hack/install/windows/install-hcsshim.sh
hack/release-windows.sh
hack/release.sh
test/windows/build.sh
vendor.conf
vendor/google.golang.org/grpc/internal/transport/http2_server.go
vendor/google.golang.org/grpc/internal/transport/http_util.go
vendor/google.golang.org/grpc/version.go

For https://github.com/containerd/cri/issues/1257
This PR:
1) Updated containerd to a176179a0894ca6768a0f993e678f08a7f8553d5 which included the change https://github.com/containerd/containerd/pull/3785 and https://github.com/containerd/containerd/pull/3823
2) Added `GOOS=windows make release` support mainly for testing. Here is the tarball:
```console
$ tar tvf _output/cri-containerd-9f79be1b.windows-amd64.tar.gz 
drwxr-xr-x root/root         0 2019-11-15 00:31 ./
-rwxr-xr-x root/root  17256960 2019-11-15 00:31 ./ctr.exe
-rwxr-xr-x root/root  18249728 2019-11-15 00:31 ./containerd-shim-runhcs-v1.exe
drwxr-xr-x root/root         0 2019-11-15 00:31 ./cni/
-rwxr-xr-x root/root   6020608 2019-11-15 00:31 ./cni/sdnbridge.exe
-rwxr-xr-x root/root   6020608 2019-11-15 00:31 ./cni/sdnoverlay.exe …
```

[WCOW] Add windows release tar for test

---

pkg/server/sandbox_run_unix.go

As https://github.com/kata-containers/runtime/issues/1603 discussed, kata relies on such mount spec to setup resolv.conf for pod VM properly.
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>

Provide resolvConf to sandbox container's mounts

---

pkg/server/events.go
pkg/server/helpers.go
pkg/server/restart.go
pkg/store/container/status.go
pkg/store/container/status_test.go

Fixes https://github.com/containerd/cri/issues/1039.
For https://github.com/containerd/containerd/issues/3873.
Use a new in-memory only field to represent `unknown` state. With this, we'll preserve the status checkpoint, instead of overwriting it with unknown status.
We may want to cherry-pick the fix.
/cc @sofat1989  

Better handle unknown state.

---

.appveyor.yml

Should remove the old go before attempting to install new one.
fixes app veyor build break seen on latest PRs... #1356

add removal of old go

---

integration/container_restart_test.go

Add an integration test case to test whether a runtime can restart a container properly.
Related to https://github.com/kata-containers/tests/pull/2140
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>

integration: Add container restart test

---

docs/config.md
pkg/config/config_unix.go
pkg/server/sandbox_run_unix.go

The former default runtime "io.containerd.runc.v1" won't support new features
like support for cgroup v2: containerd/containerd#3726
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

bump up the default runtime to "io.containerd.runc.v2"

---

cri.go

`ValidatePluginConfig` may update the config for defaulting. It should be done before creating the service.
/cc @bentheelder

Validate and update the right config

---

pkg/server/container_create_unix.go

In cgroup v1 container implementations, cgroupns is not used by default because
it was not available in the kernel until kernel 4.6 (May 2016), and the default
behavior will not change on cgroup v1 environments, because changing the
default will break compatibility and surprise users.
For cgroup v2, implementations are going to unshare cgroupns by default
so as to hide /sys/fs/cgroup from containers.
* Discussion: https://github.com/containers/libpod/issues/4363
* Podman PR (merged): https://github.com/containers/libpod/pull/4374
* Moby PR: https://github.com/moby/moby/pull/40174
This PR enables cgroupns for containers, but pod sandboxes are untouched
because probably there is no need to do.

cgroup2: unshare cgroup namespace for containers

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

We have a new release of runc ( opencontainers/runc#2217 ). This release
has a fix for a race condition we are struggling with in kubernetes
(especially CI jobs) which was fixed in opencontainers/runc#2185
The v1.0.0-rc10 includes the fix for CVE-2019-19921 as well. The full
diff upstream is here:
https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10
`Signed-off-by: Davanum Srinivas <davanum@gmail.com>`

Bump to opencontainers/runc new version - v1.0.0-rc10

---

vendor.conf
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go

full diff: https://github.com/go-yaml/yaml/compare/v2.2.4...v2.2.8
includes:
- go-yaml/yaml@f90ceb4f409096b60e2e9076b38b304b8246e5fa Fix check for non-map alias merging in v2
- fix for "yaml.Unmarshal crashes on "assignment to entry in nil map""
- go-yaml/yaml 543 Port stale simple_keys fix to v2
- go-yaml/yaml@1f64d6156d11335c3f22d9330b0ad14fc1e789ce Fix issue in simple_keys improvements
- fixes "Invalid simple_keys now cause panics later in decode"
- go-yaml/yaml 555 Optimize cases with long potential simple_keys

vendor: bump gopkg.in/yaml.v2 v2.2.8

---

vendor.conf
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/k8s.io/api/go.mod
vendor/k8s.io/apimachinery/go.mod
vendor/k8s.io/apiserver/go.mod
vendor/k8s.io/client-go/go.mod
vendor/k8s.io/cri-api/go.mod
vendor/k8s.io/kubernetes/go.mod

Following up from discussion in https://github.com/containerd/cri/pull/1386#issuecomment-579677073
- Updating k8s to 1.16.6 
- Updating gopkg.in/yaml.v2 to v2.2.4 (Difference is [here](https://github.com/go-yaml/yaml/compare/v2.2.3...v2.2.4) `v2.2.4` has this additional [commit](https://github.com/go-yaml/yaml/commit/f221b8435cfb71e54062f6c6e99e9ade30b124d5) that is relevant for CVE-2019-11253.

[release/1.3] update kubernetes and its dependencies to v1.16.6

---

vendor.conf
vendor/gopkg.in/yaml.v2/decode.go
vendor/gopkg.in/yaml.v2/scannerc.go
vendor/gopkg.in/yaml.v2/yaml.go
vendor/gopkg.in/yaml.v2/yamlh.go

back port of https://github.com/containerd/cri/pull/1387 for the 1.3 branch
full diff: https://github.com/go-yaml/yaml/compare/v2.2.4...v2.2.8
includes:
- go-yaml/yaml@f90ceb4f409096b60e2e9076b38b304b8246e5fa Fix check for non-map alias merging in v2
- fix for "yaml.Unmarshal crashes on "assignment to entry in nil map""
- go-yaml/yaml 543 Port stale simple_keys fix to v2
- go-yaml/yaml@1f64d6156d11335c3f22d9330b0ad14fc1e789ce Fix issue in simple_keys improvements
- fixes "Invalid simple_keys now cause panics later in decode"
- go-yaml/yaml 555 Optimize cases with long potential simple_keys
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 3d0818d99e3fd012ebc2a3b299f0c5d9f3cef2f2)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

[release/1.3 backport] vendor: bump gopkg.in/yaml.v2 v2.2.8

---

pkg/store/errors.go
pkg/store/errors_test.go

The pkg/store errors are duplicated errors of NotFound and AlreadyExist from
containerd's errdefs package and thus do not properly serialize when running
errdefs.ToGRPC on them. CRI runs this function on every return from a CRI
method so the conversion fails if there is a cache miss from the store caches
for containers or sandboxes. This change verifies that the errors are properly
converted to their gRPC values.

Fix store error serialization to gRPC status codes

---

contrib/ansible/cri-containerd.yaml
docs/config.md
docs/crictl.md
integration/main_test.go
pkg/config/config_unix.go

resolve issue #1398 
see https://github.com/kubernetes/kubernetes/pull/88129 and other related prs..
Waiting for kubernetes team to push the new v3.2 pause manifest and images to k8s.gcr.io.

move to v3.2 for the pause image

---

vendor.conf

similar to https://github.com/containerd/containerd/pull/3858
Since it doesn't look like this repo will switch to using go mod yet, let's reformat this file to make comparing with other repositories slightly easier and to encourage pinning
Best to review individual commits (no dependencies were updated, so vendored files should stay unmodified)

Reformat vendor.conf: use columns, pin by git-sha, and sort alphabetically

---

pkg/server/container_create_unix.go

Conforms to the latest KEP:
https://github.com/kubernetes/enhancements/blob/0e409b47497e398b369c281074485c8de129694f/keps/sig-node/20191118-cgroups-v2.md#cgroup-namespace

cgroup2: do not unshare cgroup namespace for privileged

---

.travis.yml

To move to go mod will require one of 1.13.8 or 1.14, can't use go mod vendoring for both at the same time.  Need to start testing 1.14 now in travis to get a feel for issues we'll have when moving up. Adding 1.14 to the optional list. Check that... it worked so well.. and tip (dev) has been so bad for so long let's scratch tip and add 1.14 as mandatory to pass. 

add golang 1.14 to prepare for move

---

integration/main_test.go

Hi, 
while trying to run containerd/cri tests on branch 1.3, I got error: `flag provided but not defined: -test.run`. This is already fixed in master, but wanted to backport it to `release/1.3` as it is the branch used for `containerd/containerd` 1.3.x releases, which is the one we currently [use ](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L197-L202)for kata containers testing.

backport release/1.3: Fix integration test for golang 1.13

---

vendor.conf

The following repos have been tagged as v1.0.0:
- https://github.com/containerd/console/commit/8375c3424e4d7b114e8a90a4a40c8e1b40d1d4e6
- https://github.com/containerd/ttrpc/commit/92c8520ef9f86600c650dd540266a007bf03670f
- https://github.com/containerd/typeurl/commit/a93fcdb778cd272c6e9b3028b2f42d813e785d40

Add version numbers for newly tagged repos

---

pkg/server/container_attach.go
pkg/server/container_execsync.go
pkg/server/streaming.go

The resize chan is never closed when doing exec/attach now. What's more, `resize` is a recieved only chan so it can not be closed. Use ctx to exit the goroutine in `handleResizing` properly.
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>

Fix goroutine leak when exec/attach

---

test/e2e_node/init.yaml

`systemctl is-enabled` is not a reliable indicator that the docker service should be started. Docker service may be running even if marked as disabled.

Start docker unconditionally

---

.github/workflows/ci.yml
hack/install/install-containerd.sh
test/windows/test.sh

`pull-cri-containerd-windows-cri` is busted for a while now. We need to find another alternative.

Running critest under windows using github action

---

pkg/server/helpers_selinux_test.go

Looks like we had a bad unit test when selinux is enabled.
Found on #1437 

fixes bad unit test when selinux is enabled

---

pkg/server/cni_conf_syncer.go
pkg/server/service.go
pkg/server/service_unix.go
pkg/server/service_windows.go
pkg/server/status.go
vendor.conf
vendor/github.com/fsnotify/fsnotify/LICENSE
vendor/github.com/fsnotify/fsnotify/README.md
vendor/github.com/fsnotify/fsnotify/fen.go
vendor/github.com/fsnotify/fsnotify/fsnotify.go
vendor/github.com/fsnotify/fsnotify/go.mod
vendor/github.com/fsnotify/fsnotify/inotify.go
vendor/github.com/fsnotify/fsnotify/inotify_poller.go
vendor/github.com/fsnotify/fsnotify/kqueue.go
vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
vendor/github.com/fsnotify/fsnotify/windows.go

With go RWMutex design, no goroutine should expect to be able to
acquire a read lock until the read lock has been released, if one
goroutine call lock.
The original design is to reload cni network config on every single
Status CRI gRPC call. If one RunPodSandbox request holds read lock
to allocate IP for too long, all other RunPodSandbox/StopPodSandbox
requests will wait for the RunPodSandbox request to release read lock.
And the Status CRI call will fail and kubelet becomes NOTReady.
Reload cni network config at every single Status CRI call is not
necessary and also brings NOTReady situation. To lower the possibility
of NOTReady, CRI will reload cni network config if there is any valid fs
change events from the cni network config dir.
Signed-off-by: Wei Fu <fuweid89@gmail.com>

reload cni network config if has fs change events

---

pkg/config/config.go
pkg/server/image_pull.go

Recently, we started a non-core subproject [stargz-snapshotter](https://github.com/containerd/stargz-snapshotter) aiming to speed up pull operation and we are seeing performance improvement on `containerd.Client`'s `Pull` operation as the following (measured on [Github Actions with Docker Hub](https://github.com/containerd/stargz-snapshotter/actions?query=workflow%3ABenchmark+branch%3Amaster). please also see [README](https://github.com/containerd/stargz-snapshotter/blob/master/README.md#stargz-snapshotter) for more details).
We've implemented the fundamental features and stargz snapshotter [passes](https://github.com/containerd/stargz-snapshotter/pull/69) [`critest`](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/validation.md) with a patched version of CRI plugin. Now …

Enable to pass additional handler on pull for stargz-based remote snapshots

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

add default scheme on endpoints in mirrors. 
It is helpful in https://github.com/containerd/containerd/issues/4108 
Signed-off-by: yang yang yang8518296@163.com

add default scheme when mirrors no scheme

---

pkg/annotations/annotations.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go
pkg/server/container_create_windows.go
pkg/server/container_create_windows_test.go

Whenever a container is launched in K8s sandbox, currently there are two OCI annotations added
- type (Container or Sandbox)
- sandbox name
It's sometimes required to perform per container operations based on pass through annotations mentioned in pod metadata. (eg setting up per container hooks: [oci-ftrace-syscall-analyzer](https://github.com/KentaTada/oci-ftrace-syscall-analyzer))
Therefore, along with type(Sandbox or Container) and Sandbox name annotations provide support for additional annotation:
- Container name
**Consider the following example** 
* Example pod config:
```bash
apiVersion: v1
kind: Pod
metadata:
name: pod-test
"annotations": {
"com.something.con1": "true",
"com.something.con2": "false",
}
spec:
containers:
- name: con1
image: busybox
command: ['sh', '-c', 'echo Hello …
```

Support for additional OCI annotations: 'container-name'

---

docs/registry.md

I tried using the config `plugins.cri.registry.configs."quay.io".auth` in microk8s, but that didn't work for private registries. However, using `plugins.cri.registry.configs.auth."https://quay.io"` worked for me.
Found this here: https://stackoverflow.com/questions/56642311/microk8s-cannot-pull-from-private-registry
Signed-off-by: Joris De Winne <joris.dewinne@gmail.com>

Update registry.md for auth config 

---

pkg/server/container_create_unix.go

For a privilege pods with PrivilegedWithoutHostDevices set to true
host device specified in the config are not provided (whereas it is done for
non privilege pods or privilege pods with PrivilegedWithoutHostDevices set
to false as all devices are included).
Add them in this case.
Fixes: 3353ab76d922 ("Add flag to overload default privileged host device behaviour")
Signed-off-by: Thibaut Collet <thibaut.collet@6wind.com>

fix incomplete host device for PrivilegedWithoutHostDevices

---

pkg/server/image_pull.go

Currently, CRI plugin passes each layer digest to remote snapshotters sequentially and snapshotters prepares snapshots sequentially. But it costs extra time especially for remote snapshotters which need to connect to the remote backend store (e.g. registries) for checking the snapshot existence on each preparation.
This commit solves this problem by introducing new label `containerd.io/snapshot/cri.chain` for passing all layer digests in an image to snapshotters and by allowing them to prepare these snapshots in parallel, which leads to speed up the preparation.
This label is supported by stargz snapshotter: https://github.com/containerd/stargz-snapshotter/pull/83

Pass chained layer digests to snapshotter for parallel snapshot preparation

---

docs/config.md
docs/registry.md

Otherwise it's confusing for readers who just need quick reference
for plugin configurations.
Fixes #1460

Clarify that plugin names are long in version = 2

---

.github/workflows/ci.yml
README.md
contrib/ansible/tasks/bootstrap_centos.yaml
contrib/ansible/tasks/bootstrap_ubuntu.yaml
pkg/server/sandbox_portforward_unix.go

use goroutines to copy the data from the stream to the TCP
connection, and viceversa, removing the socat dependency.
Quoting Lantao Liu, the logic is as follow:
When one side (either pod side or user side) of portforward
is closed, we should stop port forwarding.
When one side is closed, the io.Copy use that side as source will close,
but the io.Copy use that side as dest won't.
Fixes: https://github.com/containerd/cri/issues/730

Get rid of socat for port forwarding

---

pkg/server/image_pull.go

The `DualStack` option was deprecated in Go 1.12, and is now enabled by default
(through commit github.com/golang/go@efc185029bf770894defe63cec2c72a4c84b2ee9).
> The Dialer.DualStack field is now meaningless and documented as deprecated.
>
> To disable fallback, set FallbackDelay to a negative value.
The default `FallbackDelay` is 300ms; to make this more explicit, this patch
sets `FallbackDelay` to the default value.
Note that Docker Hub currently does not support IPv6 (DNS for registry-1.docker.io
has no AAAA records, so we should not hit the 300ms delay).

newTransport(): remove deprecated DualStack option

---

cluster/gce/cloud-init/master.yaml

Copied the change from https://github.com/kubernetes/kubernetes/pull/88856.
All Kubernetes containerd e2e tests are failing because of this.
See more details at https://github.com/kubernetes/kubernetes/issues/89847
@cheftako

Create etcd user in cloud init.

---

docs/config.md
pkg/config/config.go
pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go
pkg/server/sandbox_run_unix.go

This change adds `default_seccomp_profile` config switch to apply default seccomp profile when not provided by k8s.
Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>

Add config flag to default empty seccomp profile

---

pkg/server/sandbox_portforward_unix.go

We encountered two failing end-to-end tests after the adoption of https://github.com/containerd/cri/pull/1470 in https://github.com/cri-o/cri-o/pull/3749:
```
Summarizing 2 Failures:
[Fail] [sig-cli] Kubectl Port forwarding With a server listening on 0.0.0.0 that expects a client request [It] should support a client that connects,
sends DATA, and disconnects
test/e2e/kubectl/portforward.go:343
[Fail] [sig-cli] Kubectl Port forwarding With a server listening on localhost that expects a client request [It] should support a client that connects
, sends DATA, and disconnects
test/e2e/kubectl/portforward.go:343
```
Increasing the timeout to 1s fixes the issue.
cc @aojea

Increase port-forward timeout to 1s to fix e2e test

---

vendor.conf
vendor/github.com/containerd/go-cni/README.md
vendor/github.com/containerd/go-cni/errors.go
vendor/github.com/containerd/go-cni/go.mod
vendor/github.com/containerd/go-cni/opts.go
vendor/github.com/containerd/go-cni/vendor.conf

full diff: https://github.com/containerd/go-cni/compare/0d360c50b10b350b6bb23863fd4dfb1c232b01c9...0553354f0046ccd41a02e724826040491a3d8998
- Add WithConfList opt for adding conf list from bytes
- Use Go modules instead of vndr
- Test on go1.13, 1.14, remove go1.12
- Update pkg/errors v0.9.1, switch to using errors.Is() instead of errors.Cause()

vendor: containerd/go-cni 0553354f0046ccd41a02e724826040491a3d8998

---

vendor.conf

When I changed the vendor.conf format to use tags, many of the
dependencies didn't use tagged versions, and the column format
made the file slightly more consistent / easier to read.
With many dependencies moving to go modules, we see more deps
tagging releases, and we're now more actively trying to use
tagged releases for our dependencies.
With containerd/containerd changing the format to use tags as
default, it makes sense to do the same here as well (to allow
for easier comparing the vendor.conf files between repositories)

vendor.conf: back to using tags

---

.appveyor.yml
.github/workflows/ci.yml
README.md

full diff: https://github.com/golang/go/compare/go1.13.10...go1.13.11
go1.13.11 (released 2020/05/14) includes fixes to the compiler. See the Go 1.13.11
milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.11+label%3ACherryPickApproved

Bump Golang 1.13.11

---

.github/workflows/ci.yml

Fix applied to ltag:
https://github.com/kunalkushwaha/ltag/pull/11/commits/5a99b302ff7cdc8a3fd78f238a1347b2442539e8
So we don't need to skip the /test directory due to the symlink error..
Also.. we don't need to explicitly skip /vendor because when reviewing the code I noted that ltag already skips vendor.

no longer need to skip /test header scan due to symlink

---

vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go

full diff: https://github.com/opencontainers/selinux/compare/v1.5.1...v1.5.2
- Implement FormatMountLabel unconditionally
Implementing FormatMountLabel on situations built without selinux
should be possible; the context will be ignored if no SELinux is available.
- Remote potential race condition, where mcs label is freed
Theorectially if you do not change the MCS Label then we free it and two
commands later reserve it. If some other process was grabbing MCS Labels
at the same time, the other process could get the same label.

vendor: opencontainers/selinux v1.5.2

---

Makefile
hack/install/install-runc.sh
hack/test-utils.sh
hack/utils.sh
pkg/containerd/opts/spec_unix.go
pkg/server/container_create.go
pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go
pkg/server/helpers_selinux_test.go
pkg/server/helpers_unix.go
pkg/server/sandbox_run.go
pkg/server/sandbox_run_unix.go
pkg/server/sandbox_run_unix_test.go
pkg/server/service.go
pkg/server/service_test.go
pkg/store/container/container.go
pkg/store/container/container_test.go
pkg/store/container/metadata.go
pkg/store/label/label.go
pkg/store/label/label_test.go
pkg/store/sandbox/metadata.go
pkg/store/sandbox/sandbox.go
pkg/store/sandbox/sandbox_test.go

This is a carry of #1246.  
We are splitting up the work and I will be carrying this PR to merge.

Add SELinux Support for CRI

---

hack/utils.sh

the cri-tools guys need the ability to test containerd against various cri-tools branches
Yes, I know the variable is named critool :)

add support for setting CRITOOL_VERSION

---

docs/config.md
pkg/config/config.go
pkg/server/container_create.go
pkg/server/container_create_test.go
pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go
pkg/server/container_create_windows.go
pkg/server/sandbox_run_unix.go
pkg/server/sandbox_run_windows.go
pkg/server/service.go
pkg/server/service_test.go

This PR adds `base_runtime_spec` to runtime config to use a file with base OCI spec.
Details: https://github.com/containerd/cri/issues/1488
Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>

Specify base OCI runtime spec

---

pkg/config/config.go
pkg/config/config_unix.go
pkg/containerd/opts/spec_unix.go
pkg/server/container_create_unix.go
pkg/server/container_update_resources_unix.go
pkg/server/container_update_resources_unix_test.go

Kubernetes has been sending hugepage limits for a few releases now. Things used to work because containerd-cri failed to honor them. 
However starting in the following [diff](https://github.com/containerd/containerd/compare/97ca1be0..7a5fcf61#diff-85b069277b32de3389720de87247f54eR451-R456) we noticed that k8s failed hard with the following error:
```
ay 31 02:47:12 kind-control-plane containerd[133]: time="2020-05-31T02:47:12.295625667Z" level=error msg="StartContainer for \"6426531767995db591ea89b05e52ebfa8887d2cd23c095ddf8e1727d1d6ec8cb\" failed" error="failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused \"process_linux.go:449: container init caused \\\"process_linux.go:415: setting cgroup config for procHooks process …
```

Tolerate missing HugeTLB cgroups controller

---

docs/config.md
pkg/config/config.go
pkg/server/image_pull.go

This adds a configuration knob for adding request headers to all
registry requests. It is not namespaced to a registry.
Relates to #1400
Usage:
```toml
version = 2
[plugins."io.containerd.grpc.v1.cri".registry.headers]
Foo = ["bar"]
```

Add config for registry http headers

---

pkg/containerd/opts/spec_windows.go
pkg/server/container_create_windows.go
pkg/server/container_create_windows_test.go

Signed-off-by: Daniel Canter <dcanter@microsoft.com>

Add GMSA credential spec passing

---

docs/config.md
pkg/config/config.go
pkg/config/config_unix.go
pkg/config/config_windows.go
pkg/server/container_create.go

This adds a new config option for ignoring volumes defined in image metadata.
In Kubernetes volumes (even temporary ones) are generally specified in the pod configuration. Mapping the ones in the image metadata can lead to resource accounting/exhaustion issues (think writing an unlimited amount of inodes or data into the volume) and policy enforcement issues (a PSP cannot disable these).
Specifically for containers started with `ReadOnlyRootFilesystem` it can also lead to unexpected behavior, for example if there's a typo in the volume mount path the container will still start since the process can write to the data location, but the data ends up in the volume defined by the image which is ephemeral and subsequently gets lost when the pod gets descheduled. The user expected the process in …

Add option for ignoring volumes defined in images

---

pkg/server/sandbox_run.go
pkg/server/sandbox_run_test.go

Reason: originally it was introduced to prevent the loading of the SCTP kernel module on the nodes. But iptables chain creation alone does not load the kernel module. The module would be loaded if an SCTP socket was created, but neither cri nor the portmap CNI plugin starts managing SCTP sockets if hostPort / portmappings are defined.
Trigger:
Failing SCTP HostPort e2e test in K8s: https://github.com/kubernetes/kubernetes/issues/92041
Containerd issue (if this one is merged containerd/vendor shall be updated):
https://github.com/containerd/containerd/issues/4321

Remove the protocol filter from the HostPort management

---

hack/test-e2e-node.sh
hack/utils.sh
pkg/server/image_pull.go

1st commit fixes pull-cri-containerd-node-e2e bucket:  kubernetes version removed from vendor.conf in #1463 
2nd commit fixes pull-cri-containerd-verify to  ignore image_pull.go SA1019 tlsConfig.BuildNameToCertificate is deprecated from #1516 

hard set kubernetes version not in vendor.conf anymore

---

pkg/containerd/opts/spec_windows.go
pkg/server/container_create_windows_test.go

Adds support to mount named pipes into Windows containers. This support
already exists in hcsshim, so this change just passes them through
correctly in cri. Named pipe mounts must start with "\\.\pipe\".
Signed-off-by: Kevin Parsons <kevpar@microsoft.com>
Fixes https://github.com/containerd/containerd/issues/4320

Support named pipe mounts for Windows containers

---

pkg/store/sandbox/status.go
pkg/store/sandbox/status_test.go

This PR changes the "failed to stop sandbox container" error message to show the state name instead of a numeric value, so it will look like this instead:
Old message example:
```
failed to stop sandbox container "91fc4d82d15624121520720bdf0c733bea8506bc129ea856bd6b2f0bb9d1c980" in '\x00' state
```
New message example:
```
failed to stop sandbox container "91fc4d82d15624121520720bdf0c733bea8506bc129ea856bd6b2f0bb9d1c980" in "StateReady" state
```

Change "failed to stop sandbox" error message to use state name instead of numeric value

---

.github/workflows/ci.yml

`apt-get update` is always required before `apt-get install` to avoid 404 errors

CI: run apt-get update befor apt-get install

---

docs/config.md
pkg/config/config.go
pkg/config/config_unix.go
pkg/containerd/opts/spec_unix.go
pkg/server/container_create_unix.go
pkg/server/container_update_resources_unix.go

ref: https://github.com/containerd/cri/pull/1519#issuecomment-652331640
Also, the TOML tag didn't correspond with the Go struct name and the JSON tag.

config: TolerateMissingHugePagesCgroupController -> TolerateMissingHugetlbController

---

.github/workflows/ci.yml

Hard to see why PRs are failing dco with -q(quiet) option..

set dco check to verbose

---

hack/release.sh

While the containerd build a file getting information about the architecture and the operating system it is running on. The cri assumes that you are using a Linux computer with x86. This commit makes the CRI adapt to the system and architecture of the computer on which it is being used.

Containerd-Cri with supports multi-architectures

---

pkg/config/config_unix.go

At least show users of / where runc.options should be added when they run containerd config default:
before
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"
runtime_engine = ""
runtime_root = ""
privileged_without_host_devices = false
base_runtime_spec = ""
```
after
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
runtime_type = "io.containerd.runc.v2"
runtime_engine = ""
runtime_root = ""
privileged_without_host_devices = false
base_runtime_spec = ""
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
```

show runc options tag

---

pkg/config/config_windows.go

The windows pause image was moved from `mcr.microsoft.com/k8s/core/pause` to `mcr.microsoft.com/oss/kubernetes/pause`.  The latest version `mcr.microsoft.com/oss/kubernetes/pause:1.4.0` of the pause image includes:
-  Windows versions 1809 (2019LTS), 1903, 1909, 2004 
- signed binaries from Microsoft built from https://github.com/kubernetes-sigs/windows-testing/tree/master/images/pause
This update is required to support 2004 in kubernetes upstream which sig-windows is supporting for k8s 1.19: https://github.com/kubernetes/website/pull/21652/files
This will enable folks to use `containerd.exe config default` without having to modify the config.

Update to latest Windows SandboxImage

---

pkg/config/config.go
pkg/config/config_unix.go
pkg/containerd/opts/spec_unix.go
pkg/server/container_create_unix.go
pkg/server/container_update_resources_unix.go
pkg/server/container_update_resources_unix_test.go

This helps with running rootless mode + cgroup v2 + systemd without hugetlb delegation.
Systemd does not (and will not, perhaps) support hugetlb delegation as of systemd v245. https://github.com/systemd/systemd/issues/14662
From https://github.com/rootless-containers/usernetes/blob/502bc5427e57236382db58a0af7996a145381803/src/patches/containerd/0001-DIRTY-VENDOR-cri-allow-disabling-hugepages.patch

allow disabling hugepages

---

.github/workflows/ci.yml

temporary workaround for issue #1538

switching to windows-2016.. latest is breaking due to wsl conflict with bash

---

.appveyor.yml
.github/workflows/ci.yml
README.md

full diff: https://github.com/golang/go/compare/go1.13.12...go1.13.14
- go1.13.14 (released 2020/07/16) includes fixes to the compiler, vet, and the
database/sql, net/http, and reflect packages. See the Go 1.13.14 milestone on
the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.14+label%3ACherryPickApproved
- go1.13.13 (released 2020/07/14) includes security fixes to the crypto/x509 and
net/http packages. See the Go 1.13.13 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.13+label%3ACherryPickApproved

Bump Golang 1.13.14

---

.appveyor.yml
.github/workflows/ci.yml
README.md

full diff: https://github.com/golang/go/compare/go1.13.14...go1.13.15
go1.13.15 (released 2020/08/06) includes security fixes to the encoding/binary
package. See the Go 1.13.15 milestone on the issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.15+label%3ACherryPickApproved

Bump Golang 1.13.15

---

pkg/server/container_start.go
pkg/server/events.go
pkg/server/opts.go
pkg/server/sandbox_run.go
vendor.conf
vendor/github.com/containerd/nri/LICENSE
vendor/github.com/containerd/nri/README.md
vendor/github.com/containerd/nri/client.go
vendor/github.com/containerd/nri/go.mod
vendor/github.com/containerd/nri/types/v1/types.go

This allows development with container to be done for NRI without the need for
custom builds.
This is an experimental feature and is not enabled unless a user has a global
`/etc/nri/conf.json` config setup with plugins on the system.  No NRI code will
be executed if this config file does not exist.
Signed-off-by: Michael Crosby <michael@thepasture.io>

Add experimental NRI injection points

---

pkg/server/container_create.go
pkg/server/helpers_unix.go
pkg/server/helpers_windows.go
pkg/server/sandbox_run.go
pkg/seutil/seutil.go

This handles kvm based runtimes for new and old versions of the selinux packages.  If the `container_kvm_t` label exists, then we use them, if not, we clear the process label. 
Signed-off-by: Michael Crosby <michael@thepasture.io>

Handle KVM based runtimes with selinux

---

README.md

I suppose that section is out of sync as the old link doesn't work anymore and the containerd/containerd repo's readme points to the CNCF slack instead of the docker community one.

README: Update slack reference to CNCF

---

pkg/server/image_pull.go
pkg/server/image_pull_test.go

Related: https://github.com/containerd/stargz-snapshotter/issues/144
In containerd, there is a size limit for label size ([4096 chars](https://github.com/containerd/containerd/blob/c862000ab96364d71559afadd82f6d8155dc5463/labels/validate.go)).
If an image has many layers (> (4096-39)/72 > 56), `containerd.io/snapshot/cri.image-layers` will hit the limit of label size and the unpack will fail because the annotation will be passed to the snapshotter as a label.
This commit fixes this by limiting the size of the annotation.

Limit size of additional annotation for avoiding unpack failure

---

vendor.conf
vendor/github.com/willf/bitset/README.md
vendor/github.com/willf/bitset/bitset.go
vendor/github.com/willf/bitset/go.mod

The changes needed by opencontainers/selinux are now in a tagged
release. This will make our dependency slightly ahead of what's
used by opencontainers/selinux until a v1.6.1 is tagged.
full diff: https://github.com/willf/bitset/compare/d5bec3311243...v1.1.11

vendor: github.com/willf/bitset v1.1.11

---

vendor.conf
vendor/github.com/willf/bitset/README.md
vendor/github.com/willf/bitset/bitset.go
vendor/github.com/willf/bitset/go.mod

backport of https://github.com/containerd/cri/pull/1578
The changes needed by opencontainers/selinux are now in a tagged
release. This will make our dependency slightly ahead of what's
used by opencontainers/selinux until a v1.6.1 is tagged.
full diff: https://github.com/willf/bitset/compare/d5bec3311243...v1.1.11
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
(cherry picked from commit 407c3eba2e144bb8c7dd2a2a6a912d023182443c)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

[release/1.4 backport] vendor: github.com/willf/bitset v1.1.11

---

cluster/gce/configure.sh

backport of https://github.com/containerd/cri/pull/1577
I wasn't 100% if this was needed, but noticed https://github.com/containerd/cri/pull/1577#issuecomment-692494275
> The change is used to fix Kubernetes upstream containerd test.
>
> The script change is GCE only and has been tested. I think it looks good to me.
@Random-Liu @vteratipally @mikebrow PTAL

[release/1.4 backport] Make script work for both python2.7 and 3.6

---

pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go

The default values of masked and readonly paths are defined
in populateDefaultUnixSpec, and are used when a sandbox is
created.  It is not, however, used for new containers.  If
a container definition does not contain a security context
specifying masked/readonly paths, a container created from
it does not have masked and readonly paths.
This patch applies the default values to masked and
readonly paths of a new container, when any specific values
are not specified.
Fixes #1569
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>

Set masked and readonly paths based on default Unix spec

---

pkg/server/container_create_unix.go
pkg/server/container_create_unix_test.go

backport of https://github.com/containerd/cri/pull/1570
The default values of masked and readonly paths are defined
in populateDefaultUnixSpec, and are used when a sandbox is
created.  It is not, however, used for new containers.  If
a container definition does not contain a security context
specifying masked/readonly paths, a container created from
it does not have masked and readonly paths.
This patch applies the default values to masked and
readonly paths of a new container, when any specific values
are not specified.
Fixes #1569
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>
(cherry picked from commit b582da44384edbf6b8c3fbf635979ec554f5bd6b)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

[release/1.4 backport] Set masked and readonly paths based on default Unix spec

---

vendor.conf
vendor/github.com/containerd/containerd/contrib/seccomp/seccomp_default.go
vendor/github.com/containerd/containerd/runtime/v1/shim/client/client.go
vendor/github.com/containerd/containerd/runtime/v1/shim/service.go
vendor/github.com/containerd/containerd/runtime/v2/bundle.go
vendor/github.com/containerd/containerd/services/tasks/local.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/containerd/version/version.go

backport of https://github.com/containerd/cri/pull/1587
(cherry picked from commit 9f61affa0967e4c5bec45b0de0041c9bec3dd035)

[release/1.4 backport] vendor: containerd/containerd v1.4.1

---

pkg/server/helpers_windows.go

similar to https://github.com/moby/moby/pull/41478.
The tricks performed by ensureRemoveAll only make sense for Linux and
other Unices, so separate it out, and make ensureRemoveAll for Windows
just an alias of os.RemoveAll.
@cpuguy83 @AkihiroSuda @kolyshkin

pkg/server: make ensureRemoveAll() an alias for os.RemoveAll() on Windows

---

pkg/server/container_start.go

The sandbox labels are missing when the create event is invoked, as far as i can tell this is a bug.
This is a important thing to have in order to be able to differenciate the containers using their pod name, namespace or uid. 
When creating the pod `sandbox` the labels are passed correctly:
https://github.com/containerd/cri/blob/d620c30d7ecbc756f8d818237f9bccbbb7353e9e/pkg/server/sandbox_run.go#L291-L300

Add missing sandbox labels when invoking nri
